import { apiError, idempotency, internalPost, json, requestId, requireJson } from "@/lib/aiow-v1/commercial-route";
import { readBoundedJson, validateContractDefinition } from "@/lib/aiow-v1/commercial-api-runtime.mjs";

export const runtime = "nodejs";
const LIMIT=8_000;
function canonical(value: any){if(!value||typeof value!=="object"||Array.isArray(value))return value; return {...value,details:typeof value.details==="string"?value.details.trim():value.details,name:typeof value.name==="string"?value.name.trim():value.name,email:typeof value.email==="string"?value.email.trim().toLowerCase():value.email,company:typeof value.company==="string"?value.company.trim():value.company};}
export async function POST(request:Request){const rid=requestId(); if(!requireJson(request))return apiError("booking","invalid_request",rid,415,"Content-Type must be application/json"); const key=idempotency(request); if(!key)return apiError("booking","invalid_request",rid,400); const url=process.env.AIOW_BOOKING_WEBHOOK_URL,secret=process.env.AIOW_BOOKING_WEBHOOK_SECRET; if(!url||!secret)return apiError("booking","unavailable",rid,503,"Booking is unavailable");
 let body; try{body=canonical((await readBoundedJson(request,LIMIT)).value);}catch(error:any){return apiError("booking","invalid_request",rid,error?.status===413?413:400);}
 if(!validateContractDefinition("BookingRequest",body)||body.date<=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Amsterdam",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()))return apiError("booking","invalid_request",rid,400);
 try{const response=await internalPost(url,secret,body,rid,key,process.env.AIOW_COMMERCIAL_TEST_MODE==="1"); let ack=null; try{ack=await response.json();}catch{} if(!response.ok||!validateContractDefinition("BookingACK",ack)||ack.requestId!==rid||ack.preference.date!==body.date||ack.preference.slot!==body.slot||ack.preference.subject!==body.subject)return apiError("booking","unavailable",rid,502,"Booking was not durably accepted"); return json(ack,202);}catch{return apiError("booking","unavailable",rid,502,"Booking was not durably accepted");}}
