import { pillars } from "@/lib/aiow-v1/pillars";
import { pricingContexts } from "@/lib/aiow-v1/pricing-contexts";
import { SITE_URL } from "@/lib/aiow-v1/seo";

function contextSection() {
  return `## Pricing contexts\n${pricingContexts.map((context) => `- [${context.labelNl}](${SITE_URL}/tarieven/${context.slug}): ${context.automations.map((item) => item.title).join(", ")}. Advice: ${context.advice} Worked calculation: ${context.calculationTotal}`).join("\n")}`;
}

function section(key: keyof typeof pillars) {
  const item = pillars[key];
  return `## ${item.title}\nURL: ${SITE_URL}/${item.slug}\n\n${item.answer}\n\n${item.introduction}\n\nBoundary: ${item.truth}\n\nPricing: ${item.pricing.headline}. ${item.pricing.items.join("; ")}. ${item.pricing.note}\n\nUse cases:\n${item.useCases.map((entry) => `- ${entry.title}: ${entry.body}`).join("\n")}\n\nFAQ:\n${item.faq.map((entry) => `- Q: ${entry.question}\n  A: ${entry.answer}`).join("\n")}`;
}

const pricing = `## AIOW v3.2 public rates\nURL: ${SITE_URL}/tarieven\n\nBusiness: Start <=10, €2,950 setup, €49/person/month, €295 monthly minimum. Growth 11–50, €7,500 setup, €59/person/month, €795 minimum. Accelerated 51–250, €19,500 setup, €69/person/month, €2,950 minimum. Private AI >250, from €49,500 setup, €89/person/month, €7,500 minimum.\n\nBuildings: Smart Office through 2,000 m², €65/m² setup with €9,500 minimum; €0.95/m²/month with €495 minimum. Office XL above 2,000 m² is estimate/quote only, from €45/m² setup and €0.75/m²/month with €1,950 monthly minimum. Home: €95/m² setup, minimum €7,500; €1.25/m²/month, minimum €225. Signature: €165/m² setup, minimum €19,500; €1.95/m²/month, minimum €495.\n\nStandard is default: customer contracts and pays third parties directly. Comfort requires automatic direct debit. Subscriptions use actual provider cost +25%; provider price increases are passed through 1-to-1 plus that 25% margin. Hardware uses cost +15% and requires full prepayment or a deposit at least equal to the hardware value before ordering. AIOW never provides interest-free financing. Unknown third-party costs are not a fixed package total.\n\nChange work: €135/hour; urgent/outside office hours €195/hour; on-site callout €95 plus hourly rate. Advice: €175/hour, €650 half-day, €1,200 day. Only the short standardized opportunity scan, about 30 minutes maximum, is free. Deep Scan for 50+ starts at €1,950 and is creditable when commissioned within 60 days.\n\nSmart Design: Scan €3.50/m², minimum €2,950; 50% of the Scan is credited when continuing to Blueprint. Projects above 10 homes use a quoted project scale, never below the published minima. Blueprint is the highest of €12.50/m², 12% technology budget or €9,500. Supervision is the highest of €7.50/m², 5% technology budget or €7,500. Smart Design is a separate premium design service, not a calculator mode.`;

const body = `# AIOW — full public service context\n\nAIOW provides AI for business processes, buildings and homes — designed and managed by one party. It separates AIOW Solutions delivery from AIOW Ventures product building. No customer, award, address, result, exclusivity, saving or ranking claim should be inferred beyond published proof.\n\n${pricing}\n\n${contextSection()}\n\n${section("ai-automatisering")}\n\n${section("lokale-ai")}\n\n${section("smart-office")}\n\n${section("home")}\n\n## Commercial boundary\nAll prices are indications/from-prices excluding VAT, hardware, physical installation, cloud, AI and supplier usage. No all-in labour, 24/7 availability, zero-cost-risk, guaranteed saving or guaranteed-margin claim is made. Definitive delivery requires a scan, written scope and acceptance criteria.\n\nLast updated: 2026-08-28\n`;

export function GET() { return new Response(body, { headers: { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "public, max-age=3600" } }); }
