export type Pillar = {
  slug: string; eyebrow: string; title: string; answer: string; introduction: string;
  truth: string; useCases: { title: string; body: string }[];
  process: { title: string; body: string }[];
  pricing: { headline: string; items: string[]; note: string };
  faq: { question: string; answer: string }[];
  related: { title: string; href: string; body: string }[];
};

export const pillars: Record<string, Pillar> = {
  "ai-automatisering": {
    slug: "ai-automatisering", eyebrow: "AIOW Solutions · Bedrijf", title: "AI-automatisering die echt onderdeel wordt van het werk.",
    answer: "AI-automatisering is het gecontroleerd overnemen of ondersteunen van terugkerend kenniswerk: informatie verzamelen, ordenen, voorstellen maken en acties klaarzetten. AIOW begint niet bij een model, maar bij één concrete werkstroom, de brondata en het beslismoment dat menselijk moet blijven.",
    introduction: "Een bruikbare automatisering heeft een eigenaar, invoer die gecontroleerd kan worden, zichtbare tussenstappen en een route voor uitzonderingen. Daarom leveren we geen losse promptbibliotheek als eindproduct. We ontwerpen de werkstroom, bouwen de koppelingen en spreken af wie fouten opvangt en wie wijzigingen goedkeurt.",
    truth: "Niet ieder proces moet autonoom worden. Werk met juridische, financiële of personele gevolgen vraagt expliciete controle. Waar brondata rommelig of systemen gesloten zijn, kan eerst opschoning of integratiewerk nodig zijn.",
    useCases: [
      { title: "Intake en triage", body: "Nieuwe aanvragen uitlezen, categoriseren en als voorstel naar de juiste eigenaar sturen—met de originele bron altijd zichtbaar." },
      { title: "Dossier- en documentwerk", body: "Informatie uit vaste documenten halen, ontbrekende velden markeren en een conceptdossier opbouwen zonder de bron te overschrijven." },
      { title: "Interne kennisvragen", body: "Antwoorden baseren op aangewezen interne bronnen en een medewerker laten zien waar het antwoord vandaan komt." },
      { title: "Conceptcommunicatie", body: "E-mails, voorstellen of updates voorbereiden binnen afgesproken taal en grenzen; verzending blijft een aparte, bevoegde stap." },
    ],
    process: [
      { title: "Werkstroomscan", body: "We volgen het proces zoals het werkelijk loopt, inclusief omwegen, uitzonderingen, rechten en gebruikte systemen." },
      { title: "Kleine verticale proef", body: "We bouwen één complete route van invoer tot gecontroleerde uitkomst. Dat maakt integratie- en datarisico vroeg zichtbaar." },
      { title: "Ingebruikname en beheer", body: "Gebruikers toetsen de uitkomst. Daarna leggen we monitoring, wijzigingen, kosten en foutafhandeling vast." },
    ],
    pricing: { headline: "Bedrijfspakketten vanaf € 4.950", items: ["Start · tot en met 10 mensen · € 4.950 implementatie + € 29 per persoon per maand, minimaal € 245", "Growth · tot en met 50 mensen · € 12.500 + € 49 per persoon per maand", "Accelerated · tot en met 250 mensen · € 24.500 + € 69 per persoon per maand", "Private AI · meer dan 250 mensen · vanaf € 49.500 + € 99 per persoon per maand"], note: "Dit zijn indicaties. Cloud- en AI-gebruik, hardware, installatie en niet vooraf bekende licenties zijn uitgesloten. De scan bepaalt de definitieve scope." },
    faq: [
      { question: "Kan AIOW ieder bestaand systeem koppelen?", answer: "Nee. Dat hangt af van beschikbare API’s, rechten, datakwaliteit en leveranciersvoorwaarden. De scan brengt die afhankelijkheden in kaart voordat ze in de scope komen." },
      { question: "Verdwijnen medewerkers door automatisering?", answer: "AIOW doet daar geen algemene belofte of voorspelling over. We ontwerpen per werkstroom welke handelingen ondersteund worden en welke verantwoordelijkheid bij mensen blijft." },
      { question: "Kan de AI zelfstandig berichten versturen?", answer: "Alleen wanneer dat technisch en organisatorisch expliciet is toegestaan. Voor impactvolle communicatie adviseren we een controle- en goedkeuringsstap." },
    ],
    related: [{ title: "Lokale AI", href: "/lokale-ai", body: "Voor werkstromen waarbij data en modellen dichter bij de eigen omgeving moeten blijven." }, { title: "Smart Office", href: "/smart-office", body: "Voor processen die ook signalen uit een fysieke werkomgeving gebruiken." }],
  },
  "lokale-ai": {
    slug: "lokale-ai", eyebrow: "AIOW Solutions · Infrastructuur", title: "Lokale AI voor meer grip op data, modellen en continuïteit.",
    answer: "Lokale AI betekent dat een deel van de AI-verwerking op eigen of toegewezen infrastructuur draait, in plaats van uitsluitend via een publieke clouddienst. Het kan de controle over gegevensstromen vergroten, maar is geen automatische garantie voor privacy, veiligheid of lagere kosten.",
    introduction: "De juiste architectuur kan volledig lokaal, hybride of cloud-gebaseerd zijn. AIOW kiest pas na beoordeling van data, taak, kwaliteitsniveau, capaciteit en beheer. Een klein lokaal model kan uitstekend zijn voor afgebakende taken en ongeschikt voor een andere. Meetbare taakprestatie is belangrijker dan modelnaam of parameteromvang.",
    truth: "Lokale modellen vragen hardwarecapaciteit, updates, toegangsbeheer, logging en onderhoud. Externe bronnen of koppelingen kunnen alsnog data buiten de omgeving brengen. Daarom beschrijven we de volledige gegevensroute en niet alleen de plek waar het model draait.",
    useCases: [
      { title: "Zoeken in interne kennis", body: "Aangewezen documenten indexeren en antwoorden met bronverwijzingen aanbieden binnen de afgesproken omgeving." },
      { title: "Afgeschermde conceptvorming", body: "Samenvattingen of concepten maken met gevoelige input, wanneer de gekozen infrastructuur en rechten dat toelaten." },
      { title: "Lokale classificatie", body: "Tekst of signalen indelen zonder elke invoer naar een externe modelprovider te sturen." },
      { title: "Hybride routering", body: "Eenvoudige of gevoelige taken lokaal uitvoeren en alleen expliciet geschikte taken naar een externe dienst sturen." },
    ],
    process: [{ title: "Data- en taakclassificatie", body: "We leggen vast welke informatie wordt verwerkt, wie toegang heeft en welk kwaliteitsniveau nodig is." }, { title: "Architectuurproef", body: "We vergelijken een lokaal of hybride ontwerp op taakprestatie, latency, capaciteit en beheerlast." }, { title: "Operationele grens", body: "We documenteren updates, toegangsrechten, logging, herstel en wanneer een externe dienst wel of niet gebruikt mag worden." }],
    pricing: { headline: "Private AI vanaf € 49.500", items: ["Voor organisaties boven 250 mensen: vanaf € 49.500 implementatie", "Beheerindicatie: € 99 per persoon per maand", "Kleinere lokale of hybride ontwerpen worden na scan binnen een passende bedrijfsscope begroot"], note: "Hardware, installatie, energie, cloud- en AI-gebruik en leverancierslicenties zijn niet inbegrepen. Capaciteit en beveiliging worden pas na technische inventarisatie definitief geprijsd." },
    faq: [{ question: "Is lokale AI altijd veiliger dan cloud-AI?", answer: "Nee. Veiligheid hangt ook af van configuratie, toegangsbeheer, updates, logging en de volledige gegevensroute. Lokale plaatsing lost die verantwoordelijkheden niet vanzelf op." }, { question: "Werkt lokale AI zonder internet?", answer: "Sommige afgebakende functies kunnen dat, mits model, data en applicatie lokaal beschikbaar zijn. Updates, externe bronnen of gekoppelde diensten kunnen nog steeds verbinding vereisen." }, { question: "Moeten we meteen eigen GPU-servers kopen?", answer: "Nee. Eerst toetsen we taak en capaciteit. Hardware wordt alleen als aparte afhankelijkheid voorgesteld wanneer de proef daar aanleiding toe geeft." }],
    related: [{ title: "AI-automatisering", href: "/ai-automatisering", body: "Ontwerp de werkstroom waarin lokale of hybride modellen bruikbaar worden." }, { title: "Smart Office", href: "/smart-office", body: "Verbind lokale verwerking waar passend met de operationele omgeving van een gebouw." }],
  },
  "smart-office": {
    slug: "smart-office", eyebrow: "AIOW Solutions · Gebouw", title: "Een Smart Office begint bij bruikbare signalen, niet bij gadgets.",
    answer: "AIOW Smart Office verbindt beschikbare gebouw- en werkprocessignalen met duidelijke acties: inzicht geven, een melding voorbereiden of een werkstroom starten. De gepubliceerde prijs is een software- en implementatie-indicatie; sensoren, hardware en fysieke installatie zijn niet inbegrepen.",
    introduction: "Een kantoor wordt niet slim door meer dashboards. Het wordt bruikbaarder wanneer een verantwoordelijke op het juiste moment voldoende context krijgt. We beginnen daarom bij een operationele vraag en controleren welke signalen al betrouwbaar beschikbaar zijn. Nieuwe fysieke componenten worden alleen met een passende installatiepartner gescoped.",
    truth: "Aanwezigheids-, klimaat- of toegangsgegevens kunnen gevoelig zijn. Doel, bewaartermijn, toegang en medewerkerscommunicatie moeten vooraf duidelijk zijn. AIOW doet geen generieke besparingsclaim: de uitkomst hangt af van gebouw, gebruik en technische basis.",
    useCases: [{ title: "Ruimtegebruik", body: "Bestaande bezettingssignalen vertalen naar bruikbare inzichten voor planning, zonder individuele observatie als verborgen doel." }, { title: "Facilitaire triage", body: "Meldingen bundelen, context toevoegen en als voorstel naar de juiste facilitaire eigenaar sturen." }, { title: "Klimaatcontext", body: "Beschikbare metingen combineren en afwijkingen tonen; aansturing volgt alleen binnen goedgekeurde technische en veiligheidsgrenzen." }, { title: "Werkplekondersteuning", body: "Terugkerende vragen of reserveringshandelingen ondersteunen via gekoppelde, bevoegde systemen." }],
    process: [{ title: "Gebouw- en procesopname", body: "We inventariseren doelen, bestaande systemen, databronnen, rechten en de fysieke beheerpartij." }, { title: "Signaalproef", body: "Eén signaal wordt van bron tot bruikbare actie getest, inclusief ontbrekende data en foutstatus." }, { title: "Partner- en beheerscope", body: "Software, fysieke werkzaamheden, verantwoordelijkheden en terugkerend beheer worden afzonderlijk vastgelegd." }],
    pricing: { headline: "Smart Office: € 35 per m²", items: ["Implementatie: € 35 per m², minimaal € 4.950", "Beheer: € 0,75 per m² per maand, minimaal € 345", "Signature: € 85 per m², minimaal € 19.500 + € 1,95 per m² per maand, minimaal € 595"], note: "Indicatief en exclusief hardware, sensoren, bekabeling, fysieke installatie, cloud- en AI-gebruik. De technische opname bepaalt wat herbruikbaar is en wat een gekwalificeerde partner moet leveren." },
    faq: [{ question: "Levert AIOW ook sensoren en installatie?", answer: "Niet binnen deze prijs. Benodigde hardware en fysieke installatie worden apart gescoped en waar nodig door een gekwalificeerde partner geleverd." }, { question: "Kan dit op ons bestaande gebouwbeheersysteem?", answer: "Mogelijk, maar alleen als interfaces, rechten en technische staat dat toelaten. Dat wordt tijdens de opname gecontroleerd." }, { question: "Volgt AIOW individuele medewerkers?", answer: "Dat is geen standaarddoel. Dataminimalisatie, transparantie en passende toegangsrechten zijn onderdeel van de scope; gevoelige toepassingen vragen aanvullende beoordeling." }],
    related: [{ title: "Lokale AI", href: "/lokale-ai", body: "Onderzoek of verwerking van gevoelige gebouwsignalen lokaal of hybride moet plaatsvinden." }, { title: "AIOW Home", href: "/home", body: "Bekijk de afzonderlijke, partner-afhankelijke route voor woningen." }],
  },
  home: {
    slug: "home", eyebrow: "AIOW Solutions · Woning", title: "Praktische woningintelligentie, met een eerlijke fysieke grens.",
    answer: "AIOW Home ontwerpt softwarematige automatisering en bediening rond een woning. Fysieke levering is partner-afhankelijk: hardware, elektrotechnisch werk, montage en installatie zijn niet inbegrepen en mogen alleen door passende, gekwalificeerde partijen worden uitgevoerd.",
    introduction: "De route begint bij concrete dagelijkse handelingen, bestaande systemen en bewonersvoorkeuren. We maken zichtbaar wat lokaal kan werken, wat een cloudverbinding gebruikt en wat bij uitval handmatig beschikbaar moet blijven. Veiligheidskritische functies worden niet als experimentele automatisering behandeld.",
    truth: "AIOW Home is geen kant-en-klaar hardwarepakket. Compatibiliteit verschilt per woning en leverancier. We beloven geen energiebesparing of universele ondersteuning; eerst moeten de woning, aanwezige installaties en partnercapaciteit worden beoordeeld.",
    useCases: [{ title: "Eén bedienlaag", body: "Geschikte bestaande functies overzichtelijk samenbrengen zonder noodzakelijke handmatige bediening weg te nemen." }, { title: "Rustige routines", body: "Niet-kritische scènes voorbereiden rond afgesproken momenten of signalen, met eenvoudige uitschakeling en override." }, { title: "Lokale voorkeuren", body: "Waar technisch passend, voorkeuren en eenvoudige beslislogica lokaal laten draaien." }, { title: "Onderhoudssignalen", body: "Beschikbare systeemmeldingen begrijpelijk bundelen; diagnose en fysiek herstel blijven werk voor de bevoegde specialist." }],
    process: [{ title: "Woninginventarisatie", body: "We bekijken doelen, bewoners, bestaande systemen, netwerk en de functies die altijd handmatig beschikbaar moeten blijven." }, { title: "Ontwerp en compatibiliteit", body: "Software, hardware-afhankelijkheden en fysieke werkzaamheden worden apart beschreven en getoetst." }, { title: "Partneruitvoering en overdracht", body: "Een gekwalificeerde partner voert fysieke werkzaamheden uit; AIOW verifieert de afgesproken softwareflow en documenteert beheer." }],
    pricing: { headline: "Home: € 55 per m²", items: ["Implementatie-indicatie: € 55 per m², minimaal € 9.950", "Beheer: € 1,25 per m² per maand, minimaal € 395", "Uitgebreide Signature-route: € 85 per m², minimaal € 19.500 + € 1,95 per m² per maand, minimaal € 595"], note: "Hardware, installatie, montage, bekabeling, bouwkundige werkzaamheden en cloud- of AI-gebruik zijn uitgesloten. Levering is afhankelijk van woningopname en beschikbaarheid van een gekwalificeerde partner." },
    faq: [{ question: "Is hardware inbegrepen?", answer: "Nee. Alle hardware, installatie en fysieke werkzaamheden vallen buiten de gepubliceerde prijs en worden alleen na opname apart aangeboden via passende partners." }, { question: "Kan AIOW ieder merk koppelen?", answer: "Nee. Compatibiliteit, lokale toegang en leveranciersvoorwaarden verschillen. We nemen alleen geverifieerde koppelingen op in de definitieve scope." }, { question: "Blijft de woning bruikbaar als AI of internet uitvalt?", answer: "Dat is een belangrijk ontwerpdoel voor essentiële bediening. De precieze fallback hangt af van bestaande systemen en wordt per functie vastgelegd." }],
    related: [{ title: "Smart Office", href: "/smart-office", body: "De aparte route voor werkplekken, facilitaire processen en gebouwsignalen." }, { title: "Lokale AI", href: "/lokale-ai", body: "Meer over lokale en hybride verwerking van gegevens." }],
  },
};
