export const PRICING_CONTEXT_SLUGS = [
  "accountants", "logistiek", "bouw", "makelaars", "advocatuur", "zorg", "horeca-retail", "industrie", "vermogende-particulieren",
  "kantoorpand", "bedrijfshal-industrie", "woning", "villa-signature", "woonproject-vve", "nieuwbouwproject",
] as const;

export type PricingContextSlug = (typeof PRICING_CONTEXT_SLUGS)[number];
export type PricingPackage = "business-start" | "business-growth" | "business-accelerated" | "private-ai" | "smart-office" | "office-xl" | "home" | "signature" | "smart-design-blueprint";

export type PricingContext = Readonly<{
  slug: PricingContextSlug;
  labelNl: string;
  labelEn: string;
  category: "business" | "building";
  title: string;
  introduction: string;
  automations: readonly Readonly<{ title: string; body: string }>[];
  advice: string;
  package: PricingPackage;
  packageLabel: string;
  calculationTitle: string;
  calculation: readonly string[];
  calculationTotal: string;
  links: readonly Readonly<{ href: string; label: string }>[];
}>;

export const pricingContexts: readonly PricingContext[] = [
  { slug:"accountants",labelNl:"Accountants",labelEn:"Accountancy",category:"business",title:"AI-automatisering voor accountants",introduction:"Automatiseer repeterend dossierwerk met controlepunten voor de accountant; AIOW claimt geen foutloze boekhouding en neemt het professionele oordeel niet over.",automations:[{title:"Dossierintake",body:"Classificeer aangeleverde stukken, signaleer ontbrekende documenten en zet uitzonderingen in een menselijke werklijst."},{title:"Concept-cliëntvragen",body:"Maak op basis van dossierstatus een controleerbaar concept voor ontbrekende informatie; verzending blijft een expliciete keuze."},{title:"Interne kenniszoeker",body:"Zoek met bronverwijzingen in eigen werkinstructies en vaktechnische notities, binnen afgesproken toegangsrechten."}],advice:"Voor 18 gebruikers past Growth als publieke rekenbasis. Kies Private AI pas als de scan aantoont dat data, beleid of integraties een afgescheiden omgeving vereisen.",package:"business-growth",packageLabel:"Growth",calculationTitle:"Voorbeeld · 18 gebruikers",calculation:["Aansluiting: € 7.500","Beheer op verbruik: 18 × € 59 = € 1.062","Pakketminimum: € 795; het hoogste bedrag geldt"],calculationTotal:"Indicatie: € 7.500 aansluiting + € 1.062 per maand",links:[{href:"/ai-automatisering",label:"AI-automatisering"},{href:"/tarieven#bedrijf",label:"Bedrijfstarieven"}]},
  { slug:"logistiek",labelNl:"Logistiek",labelEn:"Logistics",category:"business",title:"AI-workflows voor logistiek",introduction:"Verbind operationele signalen zonder te doen alsof voorspellingen of externe vervoerders altijd beschikbaar zijn.",automations:[{title:"Afwijkingsinbox",body:"Bundel statusafwijkingen uit toegestane bronnen en routeer ze naar de juiste planner."},{title:"Documentcontrole",body:"Vergelijk vracht- en leverdocumenten op ontbrekende velden en laat uitzonderingen beoordelen."},{title:"Overdrachtsrapport",body:"Stel per dienst een conceptoverdracht op uit vastgelegde gebeurtenissen, met bronlinks."}],advice:"Voor 42 gebruikers is Growth de publieke basis. Integraties met TMS, scanners en vervoerders worden pas na technische scan toegezegd.",package:"business-growth",packageLabel:"Growth",calculationTitle:"Voorbeeld · 42 gebruikers",calculation:["Aansluiting: € 7.500","Beheer op verbruik: 42 × € 59 = € 2.478","Dit ligt boven het minimum van € 795"],calculationTotal:"Indicatie: € 7.500 aansluiting + € 2.478 per maand",links:[{href:"/ai-automatisering",label:"Procesautomatisering"},{href:"/tarieven#bedrijf",label:"Alle bedrijfspakketten"}]},
  { slug:"bouw",labelNl:"Bouw",labelEn:"Construction",category:"business",title:"AI-automatisering in de bouw",introduction:"Maak projectinformatie beter vindbaar en overdraagbaar, zonder planning, veiligheid of contractbesluiten autonoom te laten nemen.",automations:[{title:"Werkbonverwerking",body:"Lees werkbonnen uit, koppel ze aan een project en zet onduidelijke regels apart voor controle."},{title:"Projectvraagbaak",body:"Zoek in goedgekeurde tekeningen, notulen en werkinstructies met zichtbare bronverwijzingen."},{title:"Meerwerksignaal",body:"Markeer mogelijke scope-afwijkingen voor beoordeling; AIOW stelt niet zelfstandig een change order vast."}],advice:"Voor 65 gebruikers valt de rekenbasis in Accelerated. Bouwplaatsconnectiviteit, devices en koppelingen zijn uitgesloten totdat de scan ze bevestigt.",package:"business-accelerated",packageLabel:"Accelerated",calculationTitle:"Voorbeeld · 65 gebruikers",calculation:["Aansluiting: € 19.500","Beheer op verbruik: 65 × € 69 = € 4.485","Dit ligt boven het minimum van € 2.950"],calculationTotal:"Indicatie: € 19.500 aansluiting + € 4.485 per maand",links:[{href:"/lokale-ai",label:"Lokale AI"},{href:"/tarieven#meerwerk",label:"Meerwerk en hulp"}]},
  { slug:"makelaars",labelNl:"Makelaars",labelEn:"Real estate agents",category:"business",title:"AI-workflows voor makelaars",introduction:"Versnel voorbereiding en opvolging, maar publiceer geen objectinformatie of waardering zonder menselijke controle.",automations:[{title:"Objectintake",body:"Structureer aangeleverde kenmerken en signaleer ontbrekende bewijsstukken vóór publicatie."},{title:"Bezichtigingsopvolging",body:"Maak conceptantwoorden en taken uit vastgelegde vragen; een medewerker controleert en verstuurt."},{title:"Dossieroverdracht",body:"Bundel besluiten, documenten en open punten voor de volgende behandelaar."}],advice:"Een kantoor met 9 gebruikers rekent met Start. Portalen, woningdata en communicatiekanalen blijven externe afhankelijkheden.",package:"business-start",packageLabel:"Start",calculationTitle:"Voorbeeld · 9 gebruikers",calculation:["Aansluiting: € 2.950","Beheer op verbruik: 9 × € 49 = € 441","Dit ligt boven het minimum van € 295"],calculationTotal:"Indicatie: € 2.950 aansluiting + € 441 per maand",links:[{href:"/ai-automatisering",label:"AI-automatisering"},{href:"/tarieven#bedrijf",label:"Start-tarieven"}]},
  { slug:"advocatuur",labelNl:"Advocatuur",labelEn:"Legal practices",category:"business",title:"Beheerste AI voor de advocatuur",introduction:"Ondersteun dossierwerk met broncontrole en afgeschermde toegang; juridisch advies en finale beoordeling blijven bij de professional.",automations:[{title:"Dossiertijdlijn",body:"Orden geautoriseerde stukken chronologisch en link iedere gebeurtenis terug naar de bron."},{title:"Conceptsamenvatting",body:"Maak een controleerbare samenvatting van geselecteerde documenten zonder die als juridisch oordeel te presenteren."},{title:"Conflict- en toegangssignalen",body:"Routeer mogelijke matches en toegangsafwijkingen naar bevoegde medewerkers; blokkeer geen dossier autonoom."}],advice:"Voor 28 gebruikers is Growth de openbare basis. Private AI is alleen passend na toetsing van geheimhouding, datalocatie en integraties.",package:"business-growth",packageLabel:"Growth",calculationTitle:"Voorbeeld · 28 gebruikers",calculation:["Aansluiting: € 7.500","Beheer op verbruik: 28 × € 59 = € 1.652","Dit ligt boven het minimum van € 795"],calculationTotal:"Indicatie: € 7.500 aansluiting + € 1.652 per maand",links:[{href:"/lokale-ai",label:"Lokale en private AI"},{href:"/tarieven#bedrijf",label:"Bedrijfstarieven"}]},
  { slug:"zorg",labelNl:"Zorg",labelEn:"Healthcare",category:"business",title:"Ondersteunende AI-workflows in de zorg",introduction:"Automatiseer administratieve stappen, niet de medische beslissing. Beschikbaarheid, privacy en menselijke escalatie worden in de scan afgebakend.",automations:[{title:"Aanmeldingscontrole",body:"Controleer of vereiste administratieve velden en documenten aanwezig zijn en routeer uitzonderingen."},{title:"Interne protocolzoeker",body:"Zoek in goedgekeurde interne protocollen met bronlinks en versie-informatie."},{title:"Dienstoverdracht",body:"Maak een conceptoverzicht van administratieve open punten; zorginhoud blijft onder menselijke verantwoordelijkheid."}],advice:"Voor 120 gebruikers geldt Accelerated als indicatie. Medische systemen, bijzondere persoonsgegevens en continuïteitseisen kunnen Private AI of extra scope vereisen.",package:"business-accelerated",packageLabel:"Accelerated",calculationTitle:"Voorbeeld · 120 gebruikers",calculation:["Aansluiting: € 19.500","Beheer op verbruik: 120 × € 69 = € 8.280","Dit ligt boven het minimum van € 2.950"],calculationTotal:"Indicatie: € 19.500 aansluiting + € 8.280 per maand",links:[{href:"/lokale-ai",label:"Lokale AI"},{href:"/tarieven#advies",label:"Scan en advies"}]},
  { slug:"horeca-retail",labelNl:"Horeca & retail",labelEn:"Hospitality & retail",category:"business",title:"AI-workflows voor horeca en retail",introduction:"Breng vestigingswerk samen zonder omzet, voorraad of personeelsbehoefte als gegarandeerde voorspelling te presenteren.",automations:[{title:"Dagstart",body:"Bundel goedgekeurde operationele signalen en open acties per vestiging."},{title:"Leveranciersafwijkingen",body:"Vergelijk bevestigingen met bestellingen en zet verschillen in een controlelijst."},{title:"Reviewroute",body:"Classificeer binnenkomende feedback en maak antwoordconcepten; publicatie blijft menselijk."}],advice:"Voor 14 gebruikers is Growth volgens de pakketgrens van toepassing, ook als Start goedkoper lijkt. Kassakoppelingen en platforms zijn derde-partijafhankelijk.",package:"business-growth",packageLabel:"Growth",calculationTitle:"Voorbeeld · 14 gebruikers",calculation:["Aansluiting: € 7.500","Beheer op verbruik: 14 × € 59 = € 826","Dit ligt boven het minimum van € 795"],calculationTotal:"Indicatie: € 7.500 aansluiting + € 826 per maand",links:[{href:"/ai-automatisering",label:"Workflowautomatisering"},{href:"/tarieven#routes",label:"Standaard en Comfort"}]},
  { slug:"industrie",labelNl:"Industrie",labelEn:"Industrial operations",category:"business",title:"AI voor industriële kennisstromen",introduction:"Ondersteun onderhouds- en kwaliteitsinformatie; besturing, machineveiligheid en fysieke installatie vallen niet stilzwijgend binnen softwaretarieven.",automations:[{title:"Storingsclassificatie",body:"Orden meldingen op bekende categorieën en stuur onbekende patronen naar een specialist."},{title:"Werkinstructiezoeker",body:"Vind de geldende instructie op basis van rol en asset, met bron en revisiedatum."},{title:"Kwaliteitsdossier",body:"Controleer administratieve compleetheid en maak een conceptoverzicht van afwijkingen."}],advice:"Voor 280 gebruikers begint Private AI vanaf € 49.500. OT-koppelingen, edge hardware en veiligheidsvalidatie worden apart onderzocht en geoffreerd.",package:"private-ai",packageLabel:"Private AI",calculationTitle:"Voorbeeld · 280 gebruikers",calculation:["Aansluiting: vanaf € 49.500","Beheer op verbruik: 280 × € 89 = € 24.920","Dit ligt boven het minimum van € 7.500"],calculationTotal:"Vanaf-indicatie: € 49.500 aansluiting + € 24.920 per maand",links:[{href:"/lokale-ai",label:"Private en lokale AI"},{href:"/tarieven#bedrijf",label:"Private AI-tarief"}]},
  { slug:"vermogende-particulieren",labelNl:"Vermogende particulieren",labelEn:"Private households",category:"business",title:"Beheerste digitale workflows voor privéomgevingen",introduction:"Structureer persoonlijke administratie en woninginformatie met strikte toegang; AIOW geeft geen financieel, fiscaal of juridisch advies.",automations:[{title:"Documentinbox",body:"Classificeer geselecteerde documenten en routeer acties naar de aangewezen persoon of adviseur."},{title:"Privé-kennisarchief",body:"Zoek binnen geautoriseerde handleidingen, contracten en woningdocumentatie met bronlinks."},{title:"Goedkeuringsworkflow",body:"Laat betalingen of instructies nooit autonoom uitvoeren, maar zet ze klaar voor expliciete goedkeuring."}],advice:"Voor een kleine beheerkring kan Start de procesbasis zijn; voor de woning zelf rekent AIOW apart met Home of Signature.",package:"business-start",packageLabel:"Start",calculationTitle:"Voorbeeld · 4 gebruikers",calculation:["Aansluiting: € 2.950","4 × € 49 = € 196","Het maandminimum van € 295 is hoger en geldt"],calculationTotal:"Indicatie: € 2.950 aansluiting + € 295 per maand",links:[{href:"/tarieven/villa-signature",label:"Villa · Signature"},{href:"/tarieven#routes",label:"Derde-kosten"}]},
  { slug:"kantoorpand",labelNl:"Kantoorpand",labelEn:"Office building",category:"building",title:"Smart Office voor een kantoorpand",introduction:"Verbind gebouwsignalen met praktische workflows. Sensoren, bekabeling, montage en fysieke regeltechniek worden apart gescoped.",automations:[{title:"Ruimte- en bezettingssignalen",body:"Maak geautoriseerde signalen bruikbaar voor facilitaire acties zonder bezetting als perfecte waarheid te behandelen."},{title:"Klimaatafwijkingen",body:"Routeer afwijkingen naar beheer en leg opvolging vast; AIOW vervangt geen gecertificeerde gebouwbesturing."},{title:"Facilitaire meldingen",body:"Classificeer meldingen, verrijk ze met locatiecontext en bewaak menselijke opvolging."}],advice:"Een bestaand kantoor van 1.200 m² valt binnen Smart Office. Boven 2.000 m² schakelt de publieke rekenregel automatisch naar Office XL/offerte.",package:"smart-office",packageLabel:"Smart Office",calculationTitle:"Voorbeeld · 1.200 m²",calculation:["Aansluiting: 1.200 × € 65 = € 78.000","Beheer: 1.200 × € 0,95 = € 1.140 per maand","Beide uitkomsten liggen boven de minima"],calculationTotal:"Indicatie: € 78.000 aansluiting + € 1.140 per maand",links:[{href:"/smart-office",label:"Smart Office"},{href:"/tarieven#pand",label:"Pandtarieven"}]},
  { slug:"bedrijfshal-industrie",labelNl:"Bedrijfshal & industrie",labelEn:"Industrial building",category:"building",title:"Smart Office XL voor bedrijfshal en industrie",introduction:"Een grote of technische locatie vraagt inventarisatie van bestaande installaties, interfaces en veiligheid voordat uitvoering kan worden beloofd.",automations:[{title:"Energie- en statusoverzicht",body:"Bundel beschikbare metersignalen voor analyse, zonder een besparingsgarantie te geven."},{title:"Onderhoudsroutering",body:"Vertaal toegestane assetmeldingen naar taken en escalaties voor bevoegde teams."},{title:"Toegangsgebeurtenissen",body:"Koppel relevante gebeurtenissen aan procedures; alarmopvolging en beveiligingscertificering blijven apart."}],advice:"Bij 3.000 m² geldt Office XL: offerte/indicatie vanaf de gepubliceerde m²-prijzen, met een hard maandminimum.",package:"office-xl",packageLabel:"Smart Office XL",calculationTitle:"Voorbeeld · 3.000 m²",calculation:["Aansluiting: vanaf 3.000 × € 45 = € 135.000","Beheer op m²: 3.000 × € 0,75 = € 2.250 per maand","Dit ligt boven het maandminimum van € 1.950"],calculationTotal:"Vanaf-indicatie: € 135.000 aansluiting + € 2.250 per maand; definitief per offerte",links:[{href:"/smart-office",label:"Gebouwroute"},{href:"/tarieven#pand",label:"Office XL-voorwaarden"}]},
  { slug:"woning",labelNl:"Woning",labelEn:"Home",category:"building",title:"AIOW Home voor een woning",introduction:"Maak woningtechniek bruikbaar rond comfort, inzicht en routines, met aparte scope voor hardware en fysieke installatie.",automations:[{title:"Woonroutines",body:"Combineer geautoriseerde triggers tot voorspelbare scènes met handmatige bediening als terugval."},{title:"Energie-inzicht",body:"Maak beschikbare meetdata begrijpelijk zonder gegarandeerde besparing of volledige meetdekking te claimen."},{title:"Onderhoudssignalen",body:"Routeer batterij-, connectiviteits- en storingssignalen naar een controleerbare actielijst."}],advice:"Voor een reguliere woning is AIOW Home de basis. Signature is de aparte premium woningroute, niet een Pand-subtype.",package:"home",packageLabel:"AIOW Home",calculationTitle:"Voorbeeld · 140 m²",calculation:["Aansluiting: 140 × € 95 = € 13.300","Beheer op m²: 140 × € 1,25 = € 175","Het maandminimum van € 225 is hoger en geldt"],calculationTotal:"Indicatie: € 13.300 aansluiting + € 225 per maand",links:[{href:"/home",label:"AIOW Home"},{href:"/tarieven#woning",label:"Woningtarieven"}]},
  { slug:"villa-signature",labelNl:"Villa · Signature",labelEn:"Villa · Signature",category:"building",title:"AIOW Signature voor een villa",introduction:"Signature is de premium woningroute voor omvangrijke integratie en regie; het blijft afhankelijk van hardware, partners en technische opname.",automations:[{title:"Geïntegreerde woonmodi",body:"Orkestreer goedgekeurde klimaat-, licht- en mediascènes met zichtbare bediening en fallback."},{title:"Technische statuslaag",body:"Bundel beschikbare subsystemen in één beheerbeeld zonder fabrikantgaranties over te nemen."},{title:"Privé-assistentflows",body:"Routeer huishoudelijke verzoeken en informatie binnen afgesproken privacy- en goedkeuringsgrenzen."}],advice:"Een villa van 300 m² rekent met Signature. Smart Design kan aanvullend en zelfstandig worden gekozen voor een overdraagbare Blauwdruk.",package:"signature",packageLabel:"AIOW Signature",calculationTitle:"Voorbeeld · 300 m²",calculation:["Aansluiting: 300 × € 165 = € 49.500","Beheer: 300 × € 1,95 = € 585 per maand","Dit ligt boven het maandminimum van € 495"],calculationTotal:"Indicatie: € 49.500 aansluiting + € 585 per maand",links:[{href:"/home",label:"Woningintelligentie"},{href:"/tarieven#smart-design",label:"Smart Design"}]},
  { slug:"woonproject-vve",labelNl:"Woonproject & VvE",labelEn:"Residential project & owners’ association",category:"building",title:"Smart Design voor woonproject en VvE",introduction:"Ontwerp eerst de technische en organisatorische kaders; individuele woningen, collectieve delen en besluitvorming vragen elk een eigen grens.",automations:[{title:"Collectieve eisenmatrix",body:"Leg functies, bevoegdheden, gegevensstromen en fysieke afhankelijkheden per gemeenschappelijk deel vast."},{title:"Bewonersscenario’s",body:"Werk concrete gebruiksscenario’s en uitzonderingen uit zonder deelname of compatibiliteit te veronderstellen."},{title:"Overdraagbare Blauwdruk",body:"Lever een zelfstandig ontwerp dat ook aan een andere installateur kan worden verstrekt."}],advice:"Voor meer dan 10 woningen volgt altijd een projectstaffel via offerte, nooit onder de gepubliceerde Smart Design-minima. AIOW financiert hardware nooit renteloos voor.",package:"smart-design-blueprint",packageLabel:"Smart Design Blauwdruk",calculationTitle:"Voorbeeld · 2.400 m² BVO · € 180.000 techbudget",calculation:["Oppervlakte: 2.400 × € 12,50 = € 30.000","Technologiebudget: 12% × € 180.000 = € 21.600","Minimum: € 9.500; het hoogste bedrag is € 30.000"],calculationTotal:"Vanaf-indicatie Blauwdruk: € 30.000; bij >10 woningen volgt offerte, nooit onder het minimum",links:[{href:"/tarieven#smart-design",label:"Smart Design-tarieven"},{href:"/tarieven#routes",label:"Hardwarevoorwaarden"}]},
  { slug:"nieuwbouwproject",labelNl:"Nieuwbouwproject",labelEn:"New-build project",category:"building",title:"Smart Design voor nieuwbouw",introduction:"Leg AI, data, gebouwtechniek en eigenaarschap vast vóór keuzes onomkeerbaar worden; uitvoering is geen voorwaarde voor een zelfstandige Blauwdruk.",automations:[{title:"Technologieprogramma",body:"Vertaal gebruikersdoelen naar toetsbare functies, interfaces, verantwoordelijkheden en uitsluitingen."},{title:"Ontwerpcontroles",body:"Toets ontwerpbesluiten op afgesproken digitale en operationele eisen en registreer afwijkingen."},{title:"Uitvoeringsregie",body:"Bewaar besluiten, afhankelijkheden en acceptatiepunten over ontwerp- en bouwpartners heen."}],advice:"Start met Scan of Blauwdruk. Bij doorgang is 50% van de Scan verrekenbaar met de Blauwdruk; de Blauwdruk is niet verrekenbaar met uitvoering.",package:"smart-design-blueprint",packageLabel:"Smart Design Blauwdruk",calculationTitle:"Voorbeeld · 4.000 m² BVO",calculation:["Oppervlakte: 4.000 × € 12,50 = € 50.000","Zonder opgegeven techbudget is de budgetanker € 0","Minimum € 9.500; € 50.000 is het hoogste bedrag"],calculationTotal:"Vanaf-indicatie Blauwdruk: € 50.000",links:[{href:"/tarieven#smart-design",label:"Smart Design"},{href:"/tarieven#advies",label:"Scan en advies"}]},
] as const satisfies readonly PricingContext[];

export function getPricingContext(slug: string): PricingContext | undefined {
  return pricingContexts.find((context) => context.slug === slug);
}
