import type { PriceResult, SmartDesignResult } from "./pricing.mjs";
export type QuoteSegment = "business" | "building" | "home";
export type QuoteServiceRoute = "standard" | "comfort";
export type QuoteLocale = "nl" | "en";
export type QuoteSmartDesignModule = "scan" | "blueprint" | "supervision";
export type QuoteConfiguration = Readonly<{ segment: QuoteSegment; homeSubtype?: "home" | "signature"; serviceRoute: QuoteServiceRoute; people?: number; squareMetres?: number; contextSlug?: string; smartDesign: Readonly<{ modules: readonly QuoteSmartDesignModule[]; squareMetres?: number; technologyBudgetEuros?: number }> }>;
export type QuoteContact = Readonly<{ name: string; email: string; phone: string; company?: string; postcode?: string; kvk?: string; startDate?: string; note?: string }>;
export type QuoteSource = Readonly<{ route: string; utm?: string; locale: QuoteLocale }>;
export type NormalizedQuoteRequest = Readonly<{ configuration: QuoteConfiguration; contact: QuoteContact; consent: Readonly<{ accepted: true; version: "aiow-quote-v1" }>; source: QuoteSource }>;
export type QuoteValidationResult = { ok: false; errors: Record<string, string> } | { ok: true; data: NormalizedQuoteRequest };
export type QuoteSnapshot = Readonly<{ schemaVersion: 1; locale: QuoteLocale; issueDate: string; validUntil: string; configuration: QuoteConfiguration; primary: PriceResult; smartDesign: readonly SmartDesignResult[]; comfort: Readonly<{ subscriptions: string; providerIncreases: string; hardware: string; thirdPartyCostsIncluded: false }> | null; qualification: string; bookingUrl: string }>;
export const QUOTE_CONTEXT_SLUGS: readonly string[];
export const QUOTE_SMART_DESIGN_MODULES: readonly QuoteSmartDesignModule[];
export const QUOTE_CONSENT_VERSION: "aiow-quote-v1";
export const QUOTE_VALIDITY_DAYS: 30;
export const QUOTE_QUALIFICATION_NL: string;
export const QUOTE_QUALIFICATION_EN: string;
export function validateQuoteRequest(input: unknown): QuoteValidationResult;
export function buildQuoteSnapshot(normalized: NormalizedQuoteRequest, options?: { now?: Date; issueDate?: string; bookingUrl?: string }): QuoteSnapshot;
export function buildQuoteMailContent(input: { quoteNumber: string; snapshot: QuoteSnapshot; contact: QuoteContact; source: QuoteSource; country?: string; receivedAt: string }): Readonly<{ customerMail: Readonly<{ from: "info@aiow.io"; to: string[]; subject: string; text: string; html: string }>; internalMail: Readonly<{ from: "info@aiow.io"; to: string[]; subject: string; text: string; html: string }> }>;
export function escapeHtml(value: unknown): string;
export function validateQuoteNumber(value: unknown, expectedYear: number): boolean;
export function amsterdamDateISO(now?: Date): string;
