import type { AiowLocale } from "./locale";

const terms: Record<string, string> = {
  "Aansluiting":"Implementation", "Aansluiting vanaf":"Implementation from", "Aansluiting per m²":"Implementation per m²", "Aansluiting vanaf per m²":"Implementation from per m²",
  "Beheer per persoon per maand":"Management per person per month", "Beheer per m² per maand":"Management per m² per month", "Beheer vanaf per m² per maand":"Management from per m² per month",
  "Minimum beheer per maand":"Minimum management per month", "Minimum aansluiting":"Minimum implementation", "Hard maandminimum.":"Hard monthly minimum.", "Hard eenmalig minimum.":"Hard one-off minimum.",
  "persoon":"person", "vierkante meter":"square metre", "maand":"month", "uur":"hour", "dag":"day",
  "Eenmalige aansluiting voor maximaal 10 personen.":"One-off implementation for up to 10 people.", "Eenmalige aansluiting voor 11–50 personen.":"One-off implementation for 11–50 people.", "Eenmalige aansluiting voor 51–250 personen.":"One-off implementation for 51–250 people.",
  "Maandelijks per persoon; minimum €295 per maand.":"Monthly per person; minimum €295 per month.", "Maandelijks per persoon; minimum €795 per maand.":"Monthly per person; minimum €795 per month.", "Maandelijks per persoon; minimum €2.950 per maand.":"Monthly per person; minimum €2,950 per month.", "Maandelijks per persoon; minimum €7.500 per maand.":"Monthly per person; minimum €7,500 per month.",
  "Vanafprijs en indicatie; definitief na technische scan.":"Starting price and indication; final after the technical scan.", "Eenmalige vanafprijs voor meer dan 250 personen of gevoelige data.":"One-off starting price for more than 250 people or sensitive data.",
  "Eenmalig; minimum aansluiting €9.500.":"One-off; minimum implementation €9,500.", "Eenmalig; minimum aansluiting €7.500.":"One-off; minimum implementation €7,500.", "Eenmalig; minimum aansluiting €19.500.":"One-off; minimum implementation €19,500.", "Maandelijks; minimum €495 per maand.":"Monthly; minimum €495 per month.", "Maandelijks; minimum €225 per maand.":"Monthly; minimum €225 per month.",
  "Alleen indicatie/offerte voor meer dan 2.000 m²; gepubliceerde bedragen zijn vanafprijzen.":"Indication/quote only above 2,000 m²; published amounts are starting prices.", "Eenmalige vanafprijs; definitief per offerte.":"One-off starting price; final by quote.", "Maandelijkse vanafprijs; minimum €1.950 per maand.":"Monthly starting price; minimum €1,950 per month.",
  "Smart Design Blauwdruk":"Smart Design Blueprint", "Hoogste van €12,50 per m² BVO, 12% technologiebudget of €9.500. Vanafprijs; boven 10 woningen offerte, nooit onder minimum.":"Highest of €12.50 per m² GFA, 12% of the technology budget or €9,500. Starting price; above 10 homes by quote, never below the minimum.", "Blauwdruk per m² BVO":"Blueprint per m² GFA", "Minimum Blauwdruk":"Minimum Blueprint", "Eenmalig; hoogste anker geldt.":"One-off; the highest anchor applies.", "Hard minimum; 12% van technologiebudget kan hoger zijn.":"Hard minimum; 12% of the technology budget may be higher.",
  "Optioneel en alleen met verplichte automatische incasso. Abonnementen: werkelijke providerkostprijs +25%. Providerprijsstijgingen worden 1-op-1 doorbelast plus die 25% marge. Hardware: kostprijs +15%, met volledige vooruitbetaling of een aanbetaling van ten minste de hardwarewaarde vóór bestelling. AIOW financiert nooit renteloos voor. Onbekende derde-kosten vormen geen vast eindbedrag.":"Optional and only with mandatory automatic direct debit. Subscriptions: actual provider cost +25%. Provider price increases are passed through 1-to-1 plus that 25% margin. Hardware: cost +15%, with full prepayment or a deposit of at least the hardware value before ordering. AIOW never provides interest-free financing. Unknown third-party costs do not form a fixed final amount.",
  "Abonnementenmarge":"Subscription margin", "Hardwaremarge":"Hardware margin", "Automatische incasso":"Automatic direct debit", "verplicht":"mandatory",
  "Regie & engineering":"Direction & engineering", "Meerwerk per uur":"Additional work per hour", "Per kwartier, vooraf gemeld.":"Per quarter-hour, notified in advance.", "Spoed / buiten kantooruren":"Urgent / outside office hours", "Spoed per uur":"Urgent work per hour", "Na expliciete afstemming.":"After explicit agreement.", "Bezoek op locatie":"On-site visit", "Voorrijtarief":"Call-out charge", "Naast uurtarief en reis-/werkafspraken.":"In addition to hourly rate and agreed travel/work terms.",
  "Verdiepend advies":"In-depth advice", "Advies per uur":"Advice per hour", "Workshops, second opinions, architectuur en strategie.":"Workshops, second opinions, architecture and strategy.", "Advies dagdeel":"Advice half-day", "Dagdeel":"Half-day", "Vooraf afgebakend dagdeel.":"Pre-scoped half-day.", "Advies dag":"Advice day", "Dag":"Day", "Vooraf afgebakend.":"Pre-scoped.",
  "Diepe Kansenscan · 50+":"Deep Opportunity Scan · 50+", "Vanafprijs; verrekenbaar bij opdracht binnen 60 dagen.":"Starting price; creditable against an engagement within 60 days.", "Vanafprijs Diepe Kansenscan":"Deep Opportunity Scan starting price", "Eenmalige vanafprijs.":"One-off starting price.",
  "50% van de Scan is verrekenbaar bij doorgang naar Blauwdruk.":"50% of the Scan is creditable when proceeding to Blueprint.", "Scan per m² BVO":"Scan per m² GFA", "Eenmalig.":"One-off.", "Minimum Scan":"Minimum Scan", "Hard minimum.":"Hard minimum.", "Smart Design Regie":"Smart Design Direction", "Hoogste van €7,50 per m² BVO, 5% technologiebudget of €7.500.":"Highest of €7.50 per m² GFA, 5% of the technology budget or €7,500.", "Regie per m² BVO":"Direction per m² GFA", "Minimum Regie":"Minimum Direction", "Hard minimum; 5% technologiebudget kan hoger zijn.":"Hard minimum; 5% of the technology budget may be higher.",
};

export function localizedSchema<T>(value: T, locale: AiowLocale): T {
  if (locale === "nl") return value;
  if (typeof value === "string") return (terms[value] ?? value) as T;
  if (Array.isArray(value)) return value.map((item) => localizedSchema(item, locale)) as T;
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, localizedSchema(item, locale)])) as T;
  return value;
}
