import Link from "next/link";
import type { AiowLocale } from "@/lib/aiow-v1/locale";
import { PublicFooter } from "./PublicFooter";
import { PublicHeader } from "./PublicHeader";
import shared from "./AiowV1Homepage.module.css";
import styles from "@/app/info.module.css";

type Section = { id?: string; title: string; paragraphs?: readonly React.ReactNode[]; items?: readonly React.ReactNode[]; cards?: readonly { readonly title: string; readonly body: React.ReactNode }[] };

export function InfoPage({ locale, eyebrow, title, lead, sections, footer }: { locale: AiowLocale; eyebrow: string; title: string; lead: string; sections: readonly Section[]; footer?: string }) {
  return <div className={`${shared.site} ${styles.page}`}><PublicHeader locale={locale} /><main className={styles.main}><p className={styles.eyebrow}>{eyebrow}</p><h1>{title}</h1><p className={styles.lead}>{lead}</p>{sections.map((section) => <section id={section.id} className={styles.section} key={section.title}><h2>{section.title}</h2>{section.cards && <div className={styles.cards}>{section.cards.map((card) => <article className={styles.card} key={card.title}><h3>{card.title}</h3><p>{card.body}</p></article>)}</div>}{section.paragraphs?.map((paragraph, index) => <p key={index}>{paragraph}</p>)}{section.items && <ul>{section.items.map((item, index) => <li key={index}>{item}</li>)}</ul>}</section>)}</main>{footer ? <p className={styles.version}>{footer}</p> : null}<PublicFooter locale={locale} showYear /></div>;
}

export const privacyContent = {
  nl: {
    eyebrow: "Privacy", title: "Alleen gegevens die nodig zijn voor je aanvraag.", lead: "AIOW gebruikt persoonsgegevens uit de publieke booking- en offerteflow uitsluitend voor de aangevraagde intake of offerte-indicatie, praktisch contact daarover en het beperken van misbruik.",
    sections: [
      { id: "booking", title: "Bookingintake", items: ["We vragen onderwerp, datum, tijdslot, naam, e-mailadres, optionele organisatie en optionele toelichting.", "De aanvraag wordt pas geaccepteerd nadat de geconfigureerde intakevoorziening hem duurzaam heeft bevestigd. Zonder die voorziening geeft de site geen nepbevestiging.", "De intakevoorziening ontvangt de ingevulde gegevens, een technisch request-ID, ontvangsttijd en idempotency key. Volledige persoonsgegevens worden niet in applicatielogs geschreven.", "Een verkorte technische hash en tijdelijke tellers kunnen worden gebruikt om buitensporige formulierpogingen af te remmen."] },
      { id: "quote", title: "Offerte-indicatie", items: ["We gebruiken de gekozen configuratie, contactgegevens, toestemming en beperkte brongegevens uitsluitend om je offerte-indicatie te berekenen, als PDF vast te leggen en over deze aanvraag contact op te nemen.", "Bedragen uit de browser worden niet vertrouwd: de server valideert de aanvraag en berekent de indicatie opnieuw volgens de gepubliceerde prijsregels.", "Vrijgave gebeurt in twee fasen. Eerst wordt de lead duurzaam voorbereid; daarna moet de geconfigureerde adapter de lead, PDF en precies twee transactionele mailtaken — één voor de klant en één intern — duurzaam accepteren. Zonder adapter of bij een fout volgt geen PDF of ontvangstbewijs.", "De mailtaken zijn alleen voor deze aanvraag en vormen geen nieuwsbriefinschrijving.", "We verwerken geen ruw IP-adres in de offertegegevens. Alleen een door de vertrouwde hostinglaag aangeleverd land kan worden vastgelegd; ontbreekt die betrouwbare landcode, dan blijft het land onbekend.", "Offertegegevens worden alleen bewaard zolang dat nodig is voor de aanvraag, de eventuele klantrelatie en toepasselijke wettelijke verplichtingen.", "Deze publieke flow activeert geen productie-, cloud-, AI- of andere leveranciersdienst namens de aanvrager."] },
      { id: "analytics", title: "Privacyvriendelijke productanalyse", items: ["Velden: event-ID, gebeurtenisnaam, tijdstip, route, taal en alleen waar nodig een beperkte categorie voor viewport, gekozen segment of serviceroute, context, foutklasse of experimentvariant. We verzamelen hiervoor geen naam, e-mailadres, vrije tekst, ruw IP-adres of verwijzende URL.", "Doel: begrijpen welke publieke pagina’s en stappen worden gebruikt, conversie en storingen op geaggregeerd niveau meten en de site verbeteren. De rechtsgrond is ons gerechtvaardigd belang bij een bruikbare, betrouwbare en privacyvriendelijke website; we gebruiken deze gegevens niet voor advertentieprofielen.", "Ontvangers: AIOW en onze contractuele hosting- en databaseverwerkers voor dit doel. We verkopen de gegevens niet en delen ze niet met advertentienetwerken.", "Ruwe analyticsgebeurtenissen en bijbehorend idempotentiemateriaal worden na 30 dagen verwijderd.", "Geaggregeerde dagtotalen bevatten geen event-ID of direct identificerende velden. AIOW bepaalt en beoordeelt de bewaartermijn, beperkt toegang en kan deze totalen verwijderen wanneer ze niet langer nodig zijn voor trendanalyse."] },
      { title: "Bewaren en delen", paragraphs: ["Bookinggegevens worden in de pilot maximaal 90 dagen bewaard, tenzij eerder verwijderen mogelijk is of een lopende klantrelatie of wettelijke verplichting langere bewaring rechtvaardigt. Gegevens worden niet verkocht. Alleen AIOW en de contractueel gekozen intake-/hostingdienst verwerken ze voor dit doel."] },
      { title: "Je rechten en contact", paragraphs: [<>Je kunt vragen om inzage, correctie of verwijdering. Gebruik daarvoor <a href="mailto:info@aiow.io">info@aiow.io</a> of de contactgegevens uit je bestaande AIOW-relatie. Vermeld geen gevoelige inhoud die niet nodig is om je verzoek te vinden.</>] },
    ], footer: "Versie 2026-08-30 · van toepassing op de publieke AIOW-bookingintake, offerte-indicatie en productanalyse.",
  },
  en: {
    eyebrow: "Privacy", title: "Only the data needed for your request.", lead: "AIOW uses personal data from the public booking and quote flow solely for the requested intake or quote indication, practical contact about it and limiting misuse.",
    sections: [
      { id: "booking", title: "Booking intake", items: ["We ask for the subject, date, time slot, name, email address, optional organisation and optional explanation.", "The request is accepted only after the configured intake facility has confirmed it durably. Without that facility, the site does not show a false confirmation.", "The intake facility receives the entered data, a technical request ID, receipt time and idempotency key. Full personal data is not written to application logs.", "A shortened technical hash and temporary counters may be used to slow excessive form attempts."] },
      { id: "quote", title: "Quote indication", items: ["We use the selected configuration, contact details, consent and limited source data solely to calculate your quote indication, record it as a PDF and contact you about this request.", "Amounts from the browser are not trusted: the server validates the request and recalculates the indication according to the published pricing rules.", "Release takes place in two phases. First, the lead is durably prepared; then the configured adapter must durably accept the lead, PDF and exactly two transactional mail tasks — one for the client and one internal. Without an adapter or if an error occurs, no PDF or receipt is issued.", "The mail tasks relate only to this request and do not constitute a newsletter subscription.", "We do not process a raw IP address in the quote data. Only a country supplied by the trusted hosting layer may be recorded; if that reliable country code is absent, the country remains unknown.", "Quote data is retained only for as long as needed for the request, any resulting client relationship and applicable legal obligations.", "This public flow does not activate any production, cloud, AI or other supplier service on behalf of the applicant."] },
      { id: "analytics", title: "Privacy-friendly product analytics", items: ["Fields: event ID, event name, timestamp, route, language and, only where needed, a limited category for viewport, selected segment or service route, context, failure class or experiment variant. We do not collect a name, email address, free text, raw IP address or referring URL for this purpose.", "Purpose: understand which public pages and steps are used, measure conversion and failures at aggregate level and improve the site. The lawful basis is our legitimate interests in a usable, reliable and privacy-friendly website; we do not use these data for advertising profiles.", "Recipients: AIOW and our contracted hosting and database processors for this purpose. We do not sell the data or share them with advertising networks.", "Raw analytics events and associated idempotency material are deleted after 30 days.", "Aggregated daily totals do not contain an event ID or directly identifying fields. AIOW determines and reviews their retention period, restricts access and can delete these totals when they are no longer needed for trend analysis."] },
      { title: "Retention and sharing", paragraphs: ["Booking data is retained for no more than 90 days during the pilot, unless earlier deletion is possible or an ongoing client relationship or legal obligation justifies longer retention. Data is not sold. Only AIOW and the contractually selected intake/hosting service process it for this purpose."] },
      { title: "Your rights and contact", paragraphs: [<>You may request access, correction or deletion. Use <a href="mailto:info@aiow.io">info@aiow.io</a> or the contact details from your existing AIOW relationship. Do not include sensitive content that is not needed to locate your request.</>] },
    ], footer: "Version 2026-08-30 · applies to the public AIOW booking intake, quote indication and product analytics.",
  },
} as const;

export const venturesContent = {
  nl: { eyebrow: "AIOW Ventures", title: "Productbouw is een andere overeenkomst.", lead: "Ventures ontwikkelt eigen digitale proposities en selectieve samenwerkingen. Het is geen verborgen onderdeel van een Solutions-implementatie en heeft een afzonderlijke scope, governance en commerciële afspraak.", sections: [{ title: "Wat hier thuishoort", cards: [{ title: "Eigen producten", body: "Proposities die AIOW zelf ontwikkelt, test en beheert als product." }, { title: "Selectieve ventures", body: "Samenwerkingen waarbij eigenaarschap, investering, risico en opbrengst vooraf expliciet worden vastgelegd." }] }, { title: "Wat niet automatisch meegaat", paragraphs: ["Een AI-scan, implementatiepakket of maandelijkse Solutions-beheerovereenkomst geeft geen recht op producteigendom, investering, omzetdeling of venturecapaciteit. Zo blijven verwachtingen en verantwoordelijkheden zuiver.", <>De eerder opgebouwde venture-ervaring blijft beschikbaar via de <Link href="/legacy-aiow">bestaande venture-omgeving</Link>.</>] }] },
  en: { eyebrow: "AIOW Ventures", title: "Product development is a different agreement.", lead: "Ventures develops its own digital propositions and selective collaborations. It is not a hidden part of a Solutions implementation and has a separate scope, governance and commercial agreement.", sections: [{ title: "What belongs here", cards: [{ title: "Our own products", body: "Propositions that AIOW develops, tests and manages as products itself." }, { title: "Selective ventures", body: "Collaborations in which ownership, investment, risk and returns are explicitly agreed in advance." }] }, { title: "What is not included automatically", paragraphs: ["An AI scan, implementation package or monthly Solutions management agreement does not confer any right to product ownership, investment, revenue sharing or venture capacity. This keeps expectations and responsibilities clear.", <>Previously developed venture experience remains available through the <Link href="/legacy-aiow">existing venture environment</Link>.</>] }] },
} as const;
