import Link from "next/link";
import { PublicHeader } from "./PublicHeader";
import { PublicFooter } from "./PublicFooter";
import { LivingBlueprintStage } from "./LivingBlueprintStage";
import { LivingBlueprintCalculator } from "./LivingBlueprintCalculator";
import styles from "./LivingBlueprintHomepage.module.css";

type Locale="nl"|"en";
const copy={
 nl:{eyebrow:"AIOW · ontwerp, bouw en beheer",title:<>Hier laat u <em>uw AI bouwen.</em></>,lead:"Voor uw werkprocessen, uw pand en uw privéleven. AIOW ontwerpt, implementeert en beheert het systeem rond uw regels. U houdt het laatste woord.",cta:"Vraag een systeemscan aan",secondary:"Bekijk een systeem in opbouw",trust:["AIOW B.V. · Hoofddorp","Menselijke goedkeuring waar nodig","Tarieven en grenzen gepubliceerd"],
 buildEyebrow:"Zo bouwt AIOW",buildTitle:"Van uw regel naar een werkend systeem.",buildBody:"We beginnen met één echt proces of één ruimte. We leggen bronnen, uitzonderingen, bevoegdheden en beheer vast. Pas daarna bouwen we.",chain:[["Bron","Wat komt binnen","Alleen afgesproken informatie en signalen."],["Regel","Wat mag gebeuren","Grenzen worden zichtbaar en toetsbaar."],["AI","Voorstel","AI bereidt voor, classificeert of signaleert."],["Gezag","Menselijk akkoord","De bevoegde persoon beslist."],["Actie","Uitvoering","Een systeem, taak of partnerroute handelt."],["Beheer","AIOW blijft","Monitoring, onderhoud en gecontroleerde verbetering."]],
 worldsEyebrow:"Drie werelden · één bouwdiscipline",worldsTitle:"Gebouwd rond de wereld waarin het moet werken.",worlds:[["Werkprocessen","Terugkerend werk wordt een gecontroleerde stroom.","Van intake en dossiers tot planning en klantcontact. AI bereidt het werk voor; uw mensen houden oordeel en relatie.","/ai-automatisering","Bekijk AI voor werkprocessen"],["Bedrijfspanden","Uw pand maakt afwijkingen bruikbaar.","Gebouwsignalen worden taken met context. Uw beheerder houdt de regie en bevoegde installateurs doen het fysieke werk.","/smart-office","Bekijk AI voor uw pand"],["Woning & privéleven","Meer gemak, zonder controle of discretie te verliezen.","Woning, agenda, documenten, leveranciers en dagelijkse routines komen rustig samen. U bepaalt wie toegang heeft en kunt altijd ingrijpen.","/home","Bekijk AIOW voor thuis"]],
 authorityEyebrow:"Gezag en grenzen",authorityTitle:"AI voert uit. Een mens blijft bevoegd.",authority:[["Voorstellen","AI mag voorbereiden binnen afgesproken bronnen en regels.","Begrensd"],["Goedkeuren","De aangewezen persoon beslist bij belangrijke stappen.","Mens"],["Uitvoeren","Systemen handelen alleen waar de scope dat toestaat.","Controleerbaar"],["Stoppen","U kunt altijd ingrijpen; AIOW bewaakt de beheerroute.","Altijd mogelijk"]],
 methodEyebrow:"De bouwmethode",methodTitle:"Scan. Scope. Bouw. Beheer.",method:[["Scan","Het echte proces, de ruimte, databronnen en afhankelijkheden."],["Scope","Het systeemplan, de grenzen en menselijke beslismomenten."],["Bouw","Gefaseerde implementatie, getoetst met de mensen die ermee werken."],["Beheer","Onderhoud, wijzigingen en inzicht in wat het systeem doet."]],
 priceEyebrow:"Publieke indicatie",priceTitle:"Eerst zien wat gebouwd wordt. Dan wat het kost.",priceBody:"De calculator toont een deterministisch startpunt op basis van uw keuzes. De definitieve prijs volgt nadat scope en afhankelijkheden zijn geverifieerd.",finalEyebrow:"Een nuttig eerste gesprek",finalTitle:"Neem één proces of één ruimte mee.",finalBody:"U ontvangt een beslismemo: wat nu gebouwd kan worden, wat van hardware of partners afhangt en wat u bewust niet automatiseert."},
 en:{eyebrow:"AIOW · design, build and manage",title:<>This is where you have <em>your AI built.</em></>,lead:"For your work processes, your property and your private life. AIOW designs, implements and manages the system around your rules. You keep the final say.",cta:"Request a system scan",secondary:"See a system taking shape",trust:["AIOW B.V. · Hoofddorp","Human approval where needed","Rates and boundaries published"],
 buildEyebrow:"How AIOW builds",buildTitle:"From your rule to a working system.",buildBody:"We start with one real process or one space. We define sources, exceptions, authority and management before we build.",chain:[["Source","What comes in","Only agreed information and signals."],["Rule","What may happen","Boundaries become visible and testable."],["AI","Proposal","AI prepares, classifies or signals."],["Authority","Human approval","The authorised person decides."],["Action","Execution","A system, task or partner route acts."],["Management","AIOW stays","Monitoring, maintenance and controlled improvement."]],
 worldsEyebrow:"Three worlds · one build discipline",worldsTitle:"Built around the world where it must work.",worlds:[["Work processes","Recurring work becomes a controlled flow.","From intake and files to planning and customer contact. AI prepares the work; your people retain judgement and relationships.","/en/ai-automation","Explore AI for work processes"],["Commercial property","Your property turns deviations into useful action.","Building signals become contextual tasks. Your operator stays in control and qualified installers handle physical work.","/en/smart-office","Explore AI for your property"],["Home & private life","More ease, without losing control or discretion.","Home, calendar, documents, suppliers and daily routines come together calmly. You decide who has access and can always intervene.","/en/home","Explore AIOW at home"]],
 authorityEyebrow:"Authority and boundaries",authorityTitle:"AI executes. A person remains authorised.",authority:[["Propose","AI may prepare within agreed sources and rules.","Bounded"],["Approve","The appointed person decides at important steps.","Human"],["Execute","Systems act only where the scope permits it.","Inspectable"],["Stop","You can always intervene; AIOW guards the management route.","Always possible"]],
 methodEyebrow:"The build method",methodTitle:"Scan. Scope. Build. Manage.",method:[["Scan","The real process, space, data sources and dependencies."],["Scope","The system plan, boundaries and human decisions."],["Build","Phased implementation, tested with the people who use it."],["Manage","Maintenance, changes and insight into what the system does."]],
 priceEyebrow:"Public indication",priceTitle:"First see what is built. Then what it costs.",priceBody:"The calculator provides a deterministic starting point from your choices. The final price follows after scope and dependencies are verified.",finalEyebrow:"A useful first conversation",finalTitle:"Bring one process or one space.",finalBody:"You receive a decision memo: what can be built now, what depends on hardware or partners and what should deliberately not be automated."}
} as const;

function WorldVisual({index}:{index:number}){if(index===1)return <svg viewBox="0 0 500 260" aria-hidden="true"><path className={styles.mass} d="M42 222V74h140v148M202 222V28h254v194"/><path d="M76 186h72M76 148h72M240 72h50v42h-50zM322 72h96M322 104h70M248 170h165"/><circle cx="275" cy="191" r="10"/><path d="M70 234H440"/></svg>;if(index===2)return <svg viewBox="0 0 500 260" aria-hidden="true"><path className={styles.mass} d="M54 132 250 28l196 104v104H54z"/><path d="M118 214v-76h88v76M280 88h110v126H280z"/><path d="M88 116h90M330 42v58M314 58h32"/><circle cx="332" cy="148" r="12"/><path d="M206 176h74"/></svg>;return <svg viewBox="0 0 500 260" aria-hidden="true"><rect className={styles.mass} x="28" y="32" width="150" height="74"/><rect className={styles.mass} x="300" y="144" width="164" height="84"/><path d="M50 190H170L240 130H350L430 60"/><circle cx="50" cy="190" r="8"/><circle cx="240" cy="130" r="8"/><circle cx="350" cy="130" r="10"/><circle cx="430" cy="60" r="8"/></svg>}

export function LivingBlueprintHomepage({locale="nl"}:{locale?:Locale}){const c=copy[locale];const scanHref=locale==="en"?"/en/scan":"/scan";return <div className={styles.site}>
 <PublicHeader locale={locale} compactMobile/><main>
  <section className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}>{c.eyebrow}</p><h1>{c.title}</h1><p className={styles.lead}>{c.lead}</p><div className={styles.heroActions}><Link className={styles.primaryButton} href={scanHref}>{c.cta}</Link><a className={styles.textLink} href="#system-in-opbouw">{c.secondary} ↓</a></div><div className={styles.trustRail}>{c.trust.map(item=><span key={item}>{item}</span>)}</div></div><LivingBlueprintStage locale={locale}/></section>
  <section id="system-in-opbouw" className={styles.buildStory}><div className={styles.buildIntro}><div><p className={styles.eyebrow}>{c.buildEyebrow}</p><h2>{c.buildTitle}</h2></div><p>{c.buildBody}</p></div><ol className={styles.causalChain}>{c.chain.map(([label,title,body],index)=><li key={label} data-human={index===3?"true":undefined}><span>0{index+1} · {label}</span><i aria-hidden="true"/><h3>{title}</h3><p>{body}</p></li>)}</ol></section>
  <section id={locale==="en"?"solutions":"oplossingen"} className={styles.worlds}><div className={styles.worldsHead}><p className={styles.eyebrow}>{c.worldsEyebrow}</p><h2>{c.worldsTitle}</h2></div><div className={styles.worldList}>{c.worlds.map(([label,title,body,href,link],index)=><article className={styles.worldCard} key={label}><div className={styles.worldCardCopy}><span>{label}</span><h3>{title}</h3><p>{body}</p><Link href={href}>{link} ↗</Link></div><div className={styles.worldVisual}><WorldVisual index={index}/></div></article>)}</div></section>
  <section className={styles.authority}><div><p className={styles.eyebrow}>{c.authorityEyebrow}</p><h2>{c.authorityTitle}</h2></div><div className={styles.authorityLedger}>{c.authority.map(([title,body,state])=><article key={title}><h3>{title}</h3><p>{body}</p><span>{state}</span></article>)}</div></section>
  <section id={locale==="en"?"approach":"aanpak"} className={styles.method}><div><p className={styles.eyebrow}>{c.methodEyebrow}</p><h2>{c.methodTitle}</h2></div><ol>{c.method.map(([title,body],index)=><li key={title}><span>0{index+1}</span><i aria-hidden="true"/><h3>{title}</h3><p>{body}</p></li>)}</ol></section>
  <section id="booking" className={styles.pricing}><div className={styles.pricingIntro}><p className={styles.eyebrow}>{c.priceEyebrow}</p><h2>{c.priceTitle}</h2><p>{c.priceBody}</p></div><LivingBlueprintCalculator locale={locale}/></section>
  <section className={styles.finalCta}><div><p className={styles.eyebrow}>{c.finalEyebrow}</p><h2>{c.finalTitle}</h2><p>{c.finalBody}</p><Link className={styles.primaryButton} href={scanHref}>{c.cta}</Link></div></section>
 </main><PublicFooter locale={locale} showYear/></div>}
