"use client";

import Link from "next/link";
import { useRef, useState, type KeyboardEvent, type MouseEvent, type ReactNode } from "react";
import type { AiowLocale } from "@/lib/aiow-v1/locale";
import { BookingModal } from "./BookingModal";
import { PublicFooter } from "./PublicFooter";
import { PublicHeader } from "./PublicHeader";
import shared from "./AiowV1Homepage.module.css";
import styles from "./TariffsPage.module.css";

type Row = readonly [ReactNode, ...ReactNode[]];
type TableContent = { label: string; caption: string; headings: readonly string[]; rows: readonly Row[]; note?: string };

function scrollTariffTable(event: KeyboardEvent<HTMLDivElement>) {
  if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return;
  event.preventDefault();
  event.currentTarget.scrollBy({ left: event.key === "ArrowRight" ? 120 : -120, behavior: "instant" });
}

function TariffTable({ table }: { table: TableContent }) {
  return <><div className={styles.tableWrap} tabIndex={0} role="region" onKeyDown={scrollTariffTable} aria-label={table.label}><table><caption>{table.caption}</caption><thead><tr>{table.headings.map((heading) => <th scope="col" key={heading}>{heading}</th>)}</tr></thead><tbody>{table.rows.map((row, index) => <tr key={index}><th scope="row">{row[0]}</th>{row.slice(1).map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>{table.note && <p className={styles.tableNote}>{table.note}</p>}</>;
}

const content = {
  nl: {
    breadcrumb: "Kruimelpad", rates: "Tarieven", eyebrow: "Tarieven · v3.2", title: "Wat AIOW kost, vóórdat u een gesprek plant.",
    intro: "AI voor bedrijfsprocessen, gebouwen en woningen — ontworpen en beheerd door één partij. We publiceren de rekenregels, minima en uitsluitingen. De scan bepaalt daarna wat technisch en organisatorisch in uw definitieve scope past.", view: "Bekijk de tabellen ↓", book: "Vraag een scan aan",
    noticeLabel: "Prijsgrens", notice: "Een indicatie is geen eindofferte.", qualification: "Alle bedragen zijn indicaties/vanafprijzen excl. btw, hardware en fysieke installatie, cloud-, AI- en leveranciersgebruik. Definitieve scope en prijs volgen na de kansenscan.",
    business: { kicker: "Bedrijfsprocessen", title: "Per persoon, met een hard minimum per maand.", table: { label: "Bedrijfstarieven — horizontaal scrollbaar", caption: "Bedrijfstarieven", headings: ["Pakket", "Omvang", "Aansluiting", "Per persoon / maand", "Minimum / maand"], rows: [["Start", "t/m 10", "€ 2.950", "€ 49", "€ 295"], ["Growth", "11–50", "€ 7.500", "€ 59", "€ 795"], ["Accelerated", "51–250", "€ 19.500", "€ 69", "€ 2.950"], ["Private AI", "meer dan 250 / gevoelige data", "vanaf € 49.500", "€ 89", "€ 7.500"]], note: "Maandprijs = het hoogste bedrag van personen × tarief of het pakketminimum. Private AI is een vanaf-indicatie en wordt na technische scan geoffreerd." } },
    office: { kicker: "Pand", title: "Smart Office per vierkante meter.", table: { label: "Smart Office-tarieven — horizontaal scrollbaar", caption: "Smart Office-tarieven", headings: ["Pakket", "Omvang", "Aansluiting", "Beheer / maand", "Minimum / maand"], rows: [["Smart Office", "t/m 2.000 m²", "€ 65/m², min. € 9.500", "€ 0,95/m²", "€ 495"], ["Smart Office XL", "meer dan 2.000 m²", "offerte, vanaf € 45/m²", "vanaf € 0,75/m²", "€ 1.950"]], note: "Office XL blijft nadrukkelijk een indicatie/offerte. Bestaande techniek, interfaces, partners en fysieke werkzaamheden worden eerst opgenomen." } },
    home: { kicker: "Woning", title: "Home en Signature per vierkante meter.", table: { label: "Woningtarieven — horizontaal scrollbaar", caption: "Woningtarieven", headings: ["Pakket", "Aansluiting", "Beheer / maand", "Minimum / maand"], rows: [["AIOW Home", "€ 95/m², min. € 7.500", "€ 1,25/m²", "€ 225"], ["AIOW Signature", "€ 165/m², min. € 19.500", "€ 1,95/m²", "€ 495"]], note: "Fysieke woninginstallatie is partner-afhankelijk. Hardware, bekabeling, montage, paneelwerk en andere fysieke werkzaamheden zijn niet inbegrepen." } },
    routes: { kicker: "Betalen van derden", title: "Standaard is transparant. Comfort is een formule.", standardLabel: "Standaard · default", standardTitle: "U contracteert en betaalt derden rechtstreeks.", standardBody: "Abonnementen, cloud- en AI-providers, internet, alarm, media, telefonie en hardware staan op uw naam en betaalmethode. AIOW richt in en beheert met least-privilege toegang. AIOW schiet niets voor.", comfortLabel: "Comfort · optioneel", comfortTitle: "Alles regelen via één AIOW-factuur.", comfortItems: ["Automatische incasso is verplicht", "Abonnementen: providerkostprijs + 25%", "Providerprijsstijgingen: 1-op-1 doorbelast plus de 25% marge", "Hardware: kostprijs + 15%", "Vóór bestelling: volledige vooruitbetaling of een aanbetaling van ten minste de hardwarewaarde", "AIOW financiert nooit renteloos voor"], comfortBody: "Derde-kosten zijn vooraf onbekend. Daarom publiceren of berekenen we geen misleidend vast Comfort-eindbedrag boven op een pakket." },
    extra: { kicker: "Buiten pakketscope", title: "Meerwerk en hulp.", table: { label: "Meerwerktarieven — horizontaal scrollbaar", caption: "Meerwerktarieven", headings: ["Werk", "Tarief", "Voorwaarde"], rows: [["Regie & engineering", "€ 135/uur", "Per kwartier, vooraf gemeld"], ["Spoed / buiten kantooruren", "€ 195/uur", "Na expliciete afstemming"], ["Bezoek op locatie", "€ 95 voorrijtarief + uurtarief", "Naast reis-/werkafspraken in de scope"]], note: "Werk buiten de vaste pakketscope en buiten afgesproken wijzigingsruimte wordt als change order of op uurtarief uitgevoerd." } },
    advice: { kicker: "Advies", title: "Een korte scan is gratis. Verdieping is betaald werk.", table: { label: "Adviestarieven — horizontaal scrollbaar", caption: "Adviestarieven", headings: ["Dienst", "Tarief", "Grens"], rows: [["Korte kansenscan", "Gratis", "Max. circa 30 min., gestandaardiseerd"], ["Verdiepend advies", "€ 175/uur", "Workshops, second opinions, architectuur en strategie"], ["Dagdeel", "€ 650", "Vooraf afgebakend"], ["Dag", "€ 1.200", "Vooraf afgebakend"], ["Diepe Kansenscan · 50+", "vanaf € 1.950", "Verrekenbaar bij opdracht binnen 60 dagen"]] } },
    design: { kicker: "Aparte premium ontwerplijn", title: "AIOW Smart Design.", intro: "Betaald advies en ontwerp voor nieuwbouw, renovatie en projectontwikkeling. Dit is geen calculatorstand en geen verplichte koppeling aan uitvoering: een Blauwdruk is een zelfstandig product dat de klant ook aan een andere installateur kan geven.", table: { label: "Smart Design-tarieven — horizontaal scrollbaar", caption: "Smart Design-tarieven", headings: ["Dienst", "Per m² BVO", "Of techbudget", "Minimum"], rows: [["Scan", "€ 3,50/m²", "—", "€ 2.950"], ["Blauwdruk", "€ 12,50/m²", "12%", "€ 9.500"], ["Regie", "€ 7,50/m²", "5%", "€ 7.500"]], note: "Het hoogste bedrag geldt: per m², percentage van het geraamde technologiebudget of minimum. Bij meer dan 10 woningen volgt een projectstaffel via offerte, nooit onder de minima. 50% van de Scan is verrekenbaar bij doorgang naar Blauwdruk; de Blauwdruk is niet verrekenbaar met uitvoering." } },
    examples: { kicker: "Rekenvoorbeelden", title: "Zo werken de gepubliceerde regels.", cards: [["Bedrijf · 8 personen", "Start", <>€ 2.950 aansluiting + 8 × € 49 = <strong>€ 392 per maand</strong>. Het minimum van € 295 is hier niet van toepassing.</>], ["Woning · 140 m²", "AIOW Home", <>140 × € 95 = <strong>€ 13.300 aansluiting</strong>. 140 × € 1,25 valt onder het maandminimum, dus <strong>€ 225 per maand</strong>.</>], ["Villa · 300 m² · € 80.000 techbudget", "Smart Design", <>Blauwdruk: hoogste van € 3.750, € 9.600 en € 9.500 = <strong>€ 9.600</strong>. Regie: hoogste van € 2.250, € 4.000 en € 7.500 = <strong>€ 7.500</strong>.</>], ["Project · 4.000 m²", "Smart Design", <>Blauwdruk: 4.000 × € 12,50 = <strong>€ 50.000</strong>. Regie: 4.000 × € 7,50 = <strong>€ 30.000</strong>, vóór eventuele offerte-afspraken.</>]] as readonly (readonly [string, string, ReactNode])[] },
    exclusions: { kicker: "Altijd zichtbaar", title: "Wat niet in deze bedragen zit.", items: ["Btw", "Hardware, sensoren, bekabeling, montage en fysieke installatie", "Cloud-, AI-, telefonie-, media- en andere leverancierskosten", "Werk buiten vaste pakketscope of begrensde wijzigingsruimte", "Een definitieve technische toezegging vóór de scan"] },
    cta: { kicker: "Eerst afbakenen", title: "Neem één proces, gebouw of plan mee.", body: "De korte gestandaardiseerde kansenscan duurt maximaal circa 30 minuten. Voor organisaties vanaf 50 personen kan een betaalde Diepe Kansenscan passend zijn." },
  },
  en: {
    breadcrumb: "Breadcrumb", rates: "Rates", eyebrow: "Rates · v3.2", title: "What AIOW costs, before you book a conversation.",
    intro: "AI for business processes, buildings and homes — designed and managed by one party. We publish the calculation rules, minimums and exclusions. The scan then determines what fits technically and organisationally within your final scope.", view: "View the tables ↓", book: "Request a scan",
    noticeLabel: "Pricing boundary", notice: "An indication is not a final quote.", qualification: "All amounts are indications/starting prices excluding VAT, hardware and physical installation, cloud, AI and supplier usage. Final scope and price follow the opportunity scan.",
    business: { kicker: "Business processes", title: "Per person, with a hard monthly minimum.", table: { label: "Business rates — horizontally scrollable", caption: "Business rates", headings: ["Package", "Size", "Setup", "Per person / month", "Minimum / month"], rows: [["Start", "up to 10", "€ 2,950", "€ 49", "€ 295"], ["Growth", "11–50", "€ 7,500", "€ 59", "€ 795"], ["Accelerated", "51–250", "€ 19,500", "€ 69", "€ 2,950"], ["Private AI", "more than 250 / sensitive data", "from € 49,500", "€ 89", "€ 7,500"]], note: "Monthly price = the higher of people × rate or the package minimum. Private AI is a starting indication and is quoted after a technical scan." } },
    office: { kicker: "Building", title: "Smart Office per square metre.", table: { label: "Smart Office rates — horizontally scrollable", caption: "Smart Office rates", headings: ["Package", "Size", "Setup", "Management / month", "Minimum / month"], rows: [["Smart Office", "up to 2,000 m²", "€ 65/m², min. € 9,500", "€ 0.95/m²", "€ 495"], ["Smart Office XL", "more than 2,000 m²", "quote, from € 45/m²", "from € 0.75/m²", "€ 1,950"]], note: "Office XL explicitly remains an indication/quote. Existing technology, interfaces, partners and physical work are inventoried first." } },
    home: { kicker: "Home", title: "Home and Signature per square metre.", table: { label: "Home rates — horizontally scrollable", caption: "Home rates", headings: ["Package", "Setup", "Management / month", "Minimum / month"], rows: [["AIOW Home", "€ 95/m², min. € 7,500", "€ 1.25/m²", "€ 225"], ["AIOW Signature", "€ 165/m², min. € 19,500", "€ 1.95/m²", "€ 495"]], note: "Physical home installation depends on partners. Hardware, cabling, mounting, panel work and other physical work are not included." } },
    routes: { kicker: "Paying third parties", title: "Standard is transparent. Comfort is a formula.", standardLabel: "Standard · default", standardTitle: "You contract and pay third parties directly.", standardBody: "Subscriptions, cloud and AI providers, internet, alarm, media, telephony and hardware are in your name and use your payment method. AIOW configures and manages them with least-privilege access. AIOW does not advance any costs.", comfortLabel: "Comfort · optional", comfortTitle: "Arrange everything through one AIOW invoice.", comfortItems: ["Automatic direct debit is mandatory", "Subscriptions: provider cost price + 25%", "Provider price increases: passed through 1-to-1 plus the 25% margin", "Hardware: cost price + 15%", "Before ordering: full prepayment or a deposit of at least the hardware value", "AIOW never provides interest-free financing"], comfortBody: "Third-party costs are unknown in advance. We therefore do not publish or calculate a misleading fixed Comfort total on top of a package." },
    extra: { kicker: "Outside package scope", title: "Additional work and support.", table: { label: "Additional-work rates — horizontally scrollable", caption: "Additional-work rates", headings: ["Work", "Rate", "Condition"], rows: [["Direction & engineering", "€ 135/hour", "Per quarter-hour, notified in advance"], ["Urgent / outside office hours", "€ 195/hour", "After explicit agreement"], ["On-site visit", "€ 95 call-out fee + hourly rate", "In addition to travel/work agreements in the scope"]], note: "Work outside the fixed package scope and agreed change allowance is performed as a change order or at the hourly rate." } },
    advice: { kicker: "Advice", title: "A short scan is free. In-depth work is paid.", table: { label: "Advisory rates — horizontally scrollable", caption: "Advisory rates", headings: ["Service", "Rate", "Boundary"], rows: [["Short opportunity scan", "Free", "Approx. 30 min. maximum, standardised"], ["In-depth advice", "€ 175/hour", "Workshops, second opinions, architecture and strategy"], ["Half-day", "€ 650", "Defined in advance"], ["Day", "€ 1,200", "Defined in advance"], ["Deep Opportunity Scan · 50+", "from € 1,950", "Creditable against an engagement within 60 days"]] } },
    design: { kicker: "Separate premium design line", title: "AIOW Smart Design.", intro: "Paid advice and design for new construction, renovation and project development. This is not a calculator mode or a mandatory link to delivery: a Blueprint is a standalone product that the client may also give to another installer.", table: { label: "Smart Design rates — horizontally scrollable", caption: "Smart Design rates", headings: ["Service", "Per m² GFA", "Or tech budget", "Minimum"], rows: [["Scan", "€ 3.50/m²", "—", "€ 2,950"], ["Blueprint", "€ 12.50/m²", "12%", "€ 9,500"], ["Direction", "€ 7.50/m²", "5%", "€ 7,500"]], note: "The highest amount applies: per m², percentage of the estimated technology budget or minimum. Above 10 homes, a project scale is quoted, never below the minimums. 50% of the Scan is creditable when proceeding to Blueprint; the Blueprint is not creditable against delivery." } },
    examples: { kicker: "Calculation examples", title: "How the published rules work.", cards: [["Business · 8 people", "Start", <>€ 2,950 setup + 8 × € 49 = <strong>€ 392 per month</strong>. The € 295 minimum does not apply here.</>], ["Home · 140 m²", "AIOW Home", <>140 × € 95 = <strong>€ 13,300 setup</strong>. 140 × € 1.25 is below the monthly minimum, so <strong>€ 225 per month</strong>.</>], ["Villa · 300 m² · € 80,000 tech budget", "Smart Design", <>Blueprint: highest of € 3,750, € 9,600 and € 9,500 = <strong>€ 9,600</strong>. Direction: highest of € 2,250, € 4,000 and € 7,500 = <strong>€ 7,500</strong>.</>], ["Project · 4,000 m²", "Smart Design", <>Blueprint: 4,000 × € 12.50 = <strong>€ 50,000</strong>. Direction: 4,000 × € 7.50 = <strong>€ 30,000</strong>, before any quoted arrangements.</>]] as readonly (readonly [string, string, ReactNode])[] },
    exclusions: { kicker: "Always visible", title: "What these amounts exclude.", items: ["VAT", "Hardware, sensors, cabling, mounting and physical installation", "Cloud, AI, telephony, media and other supplier costs", "Work outside the fixed package scope or bounded change allowance", "A final technical commitment before the scan"] },
    cta: { kicker: "Define the boundary first", title: "Bring one process, building or plan.", body: "The short standardised opportunity scan takes approximately 30 minutes at most. For organisations with 50 or more people, a paid Deep Opportunity Scan may be appropriate." },
  },
} as const;

export function TariffsPage({ locale = "nl" }: { locale?: AiowLocale }) {
  const [booking, setBooking] = useState(false);
  const bookingTrigger = useRef<HTMLElement | null>(null);
  const t = content[locale];
  function openBooking(event: MouseEvent<HTMLButtonElement>) { bookingTrigger.current = event.currentTarget; setBooking(true); }
  const section = (id: string, item: { kicker: string; title: string; table: TableContent }, soft = false) => <section id={id} className={`${styles.section} ${soft ? styles.soft : ""}`}><div className={styles.sectionHead}><p>{item.kicker}</p><h2>{item.title}</h2></div><TariffTable table={item.table} /></section>;

  return <div className={`${shared.site} ${styles.tariffSite}`}><PublicHeader locale={locale} onBook={openBooking} /><main>
    <nav className={styles.breadcrumb} aria-label={t.breadcrumb}><Link href={locale === "en" ? "/en" : "/"}>AIOW</Link><span>/</span><span>{t.rates}</span></nav>
    <header className={styles.hero}><p className={shared.eyebrow}>{t.eyebrow}</p><h1>{t.title}</h1><p>{t.intro}</p><div><a href={locale === "en" ? "#business" : "#bedrijf"}>{t.view}</a><button className={shared.primaryButton} onClick={openBooking}>{t.book}</button></div></header>
    <section className={styles.notice} aria-label={t.noticeLabel}><strong>{t.notice}</strong><p className={styles.qualification}>{t.qualification}</p></section>
    {section(locale === "en" ? "business" : "bedrijf", t.business)}{section(locale === "en" ? "building" : "pand", t.office, true)}{section(locale === "en" ? "home" : "woning", t.home)}
    <section id="routes" className={`${styles.section} ${styles.soft}`}><div className={styles.sectionHead}><p>{t.routes.kicker}</p><h2>{t.routes.title}</h2></div><div className={styles.routeGrid}><article><span>{t.routes.standardLabel}</span><h3>{t.routes.standardTitle}</h3><p>{t.routes.standardBody}</p></article><article><span>{t.routes.comfortLabel}</span><h3>{t.routes.comfortTitle}</h3><ul>{t.routes.comfortItems.map((item) => <li key={item}>{item}</li>)}</ul><p>{t.routes.comfortBody}</p></article></div></section>
    {section(locale === "en" ? "additional-work" : "meerwerk", t.extra)}{section(locale === "en" ? "advice" : "advies", t.advice, true)}
    <section id="smart-design" className={styles.smartDesign}><div className={styles.designIntro}><p>{t.design.kicker}</p><h2>{t.design.title}</h2><p>{t.design.intro}</p></div><TariffTable table={t.design.table} /></section>
    <section id="voorbeelden" className={`${styles.section} ${styles.soft}`}><div className={styles.sectionHead}><p>{t.examples.kicker}</p><h2>{t.examples.title}</h2></div><div className={styles.examples}>{t.examples.cards.map(([label, title, body]) => <article key={label}><span>{label}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section id="uitsluitingen" className={styles.boundary}><div><p>{t.exclusions.kicker}</p><h2>{t.exclusions.title}</h2></div><ul>{t.exclusions.items.map((item) => <li key={item}>{item}</li>)}</ul></section>
    <section className={styles.cta}><p className={shared.eyebrow}>{t.cta.kicker}</p><h2>{t.cta.title}</h2><p>{t.cta.body}</p><button className={shared.primaryButton} onClick={openBooking}>{t.book}</button></section>
  </main><PublicFooter locale={locale} /><BookingModal open={booking} onClose={() => setBooking(false)} locale={locale} returnFocus={bookingTrigger.current} /></div>;
}
