"use client";

import Link from "next/link";
import { useRef, useState, type KeyboardEvent, type MouseEvent } from "react";
import { BookingModal } from "./BookingModal";
import { PublicHeader } from "./PublicHeader";
import shared from "./AiowV1Homepage.module.css";
import styles from "./TariffsPage.module.css";

const Qualification = () => <p className={styles.qualification}>Alle bedragen zijn indicaties/vanafprijzen excl. btw, hardware en fysieke installatie, cloud-, AI- en leveranciersgebruik. Definitieve scope en prijs volgen na de kansenscan.</p>;

function scrollTariffTable(event: KeyboardEvent<HTMLDivElement>) {
  if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return;
  event.preventDefault();
  event.currentTarget.scrollBy({ left: event.key === "ArrowRight" ? 120 : -120, behavior: "instant" });
}

export function TariffsPage() {
  const [booking, setBooking] = useState(false);
  const bookingTrigger = useRef<HTMLElement | null>(null);
  function openBooking(event: MouseEvent<HTMLButtonElement>) { bookingTrigger.current = event.currentTarget; setBooking(true); }

  return <div className={`${shared.site} ${styles.tariffSite}`}>
    <PublicHeader onBook={openBooking} />
    <main>
      <nav className={styles.breadcrumb} aria-label="Kruimelpad"><Link href="/">AIOW</Link><span>/</span><span>Tarieven</span></nav>
      <header className={styles.hero}><p className={shared.eyebrow}>Tarieven · v3.2</p><h1>Wat AIOW kost, vóórdat u een gesprek plant.</h1><p>AI voor bedrijfsprocessen, gebouwen en woningen — ontworpen en beheerd door één partij. We publiceren de rekenregels, minima en uitsluitingen. De scan bepaalt daarna wat technisch en organisatorisch in uw definitieve scope past.</p><div><a href="#bedrijf">Bekijk de tabellen ↓</a><button className={shared.primaryButton} onClick={openBooking}>Plan de kansenscan</button></div></header>

      <section className={styles.notice} aria-label="Prijsgrens"><strong>Een indicatie is geen eindofferte.</strong><Qualification /></section>

      <section id="bedrijf" className={styles.section}><div className={styles.sectionHead}><p>Bedrijfsprocessen</p><h2>Per persoon, met een hard minimum per maand.</h2></div><div className={styles.tableWrap} tabIndex={0} role="region" onKeyDown={scrollTariffTable} aria-label="Bedrijfstarieven — horizontaal scrollbaar"><table><caption>Bedrijfstarieven</caption><thead><tr><th scope="col">Pakket</th><th scope="col">Omvang</th><th scope="col">Aansluiting</th><th scope="col">Per persoon / maand</th><th scope="col">Minimum / maand</th></tr></thead><tbody><tr><th scope="row">Start</th><td>t/m 10</td><td>€ 2.950</td><td>€ 49</td><td>€ 295</td></tr><tr><th scope="row">Growth</th><td>11–50</td><td>€ 7.500</td><td>€ 59</td><td>€ 795</td></tr><tr><th scope="row">Accelerated</th><td>51–250</td><td>€ 19.500</td><td>€ 69</td><td>€ 2.950</td></tr><tr><th scope="row">Private AI</th><td>meer dan 250 / gevoelige data</td><td>vanaf € 49.500</td><td>€ 89</td><td>€ 7.500</td></tr></tbody></table></div><p className={styles.tableNote}>Maandprijs = het hoogste bedrag van personen × tarief of het pakketminimum. Private AI is een vanaf-indicatie en wordt na technische scan geoffreerd.</p></section>

      <section id="pand" className={`${styles.section} ${styles.soft}`}><div className={styles.sectionHead}><p>Pand</p><h2>Smart Office per vierkante meter.</h2></div><div className={styles.tableWrap} tabIndex={0} role="region" onKeyDown={scrollTariffTable} aria-label="Smart Office-tarieven — horizontaal scrollbaar"><table><caption>Smart Office-tarieven</caption><thead><tr><th scope="col">Pakket</th><th scope="col">Omvang</th><th scope="col">Aansluiting</th><th scope="col">Beheer / maand</th><th scope="col">Minimum / maand</th></tr></thead><tbody><tr><th scope="row">Smart Office</th><td>t/m 2.000 m²</td><td>€ 65/m², min. € 9.500</td><td>€ 0,95/m²</td><td>€ 495</td></tr><tr><th scope="row">Smart Office XL</th><td>meer dan 2.000 m²</td><td>offerte, vanaf € 45/m²</td><td>vanaf € 0,75/m²</td><td>€ 1.950</td></tr></tbody></table></div><p className={styles.tableNote}>Office XL blijft nadrukkelijk een indicatie/offerte. Bestaande techniek, interfaces, partners en fysieke werkzaamheden worden eerst opgenomen.</p></section>

      <section id="woning" className={styles.section}><div className={styles.sectionHead}><p>Woning</p><h2>Home en Signature per vierkante meter.</h2></div><div className={styles.tableWrap} tabIndex={0} role="region" onKeyDown={scrollTariffTable} aria-label="Woningtarieven — horizontaal scrollbaar"><table><caption>Woningtarieven</caption><thead><tr><th scope="col">Pakket</th><th scope="col">Aansluiting</th><th scope="col">Beheer / maand</th><th scope="col">Minimum / maand</th></tr></thead><tbody><tr><th scope="row">AIOW Home</th><td>€ 95/m², min. € 7.500</td><td>€ 1,25/m²</td><td>€ 225</td></tr><tr><th scope="row">AIOW Signature</th><td>€ 165/m², min. € 19.500</td><td>€ 1,95/m²</td><td>€ 495</td></tr></tbody></table></div><p className={styles.tableNote}>Fysieke woninginstallatie is partner-afhankelijk. Hardware, bekabeling, montage, paneelwerk en andere fysieke werkzaamheden zijn niet inbegrepen.</p></section>

      <section id="routes" className={`${styles.section} ${styles.soft}`}><div className={styles.sectionHead}><p>Betalen van derden</p><h2>Standaard is transparant. Comfort is een formule.</h2></div><div className={styles.routeGrid}><article><span>Standaard · default</span><h3>U contracteert en betaalt derden rechtstreeks.</h3><p>Abonnementen, cloud- en AI-providers, internet, alarm, media, telefonie en hardware staan op uw naam en betaalmethode. AIOW richt in en beheert met least-privilege toegang. AIOW schiet niets voor.</p></article><article><span>Comfort · optioneel</span><h3>Alles regelen via één AIOW-factuur.</h3><ul><li>Automatische incasso is verplicht</li><li>Abonnementen: providerkostprijs + 25%</li><li>Providerprijsstijgingen: 1-op-1 doorbelast plus de 25% marge</li><li>Hardware: kostprijs + 15%</li><li>Vóór bestelling: volledige vooruitbetaling of een aanbetaling van ten minste de hardwarewaarde</li><li>AIOW financiert nooit renteloos voor</li></ul><p>Derde-kosten zijn vooraf onbekend. Daarom publiceren of berekenen we geen misleidend vast Comfort-eindbedrag boven op een pakket.</p></article></div></section>

      <section id="meerwerk" className={styles.section}><div className={styles.sectionHead}><p>Buiten pakketscope</p><h2>Meerwerk en hulp.</h2></div><div className={styles.tableWrap} tabIndex={0} role="region" onKeyDown={scrollTariffTable} aria-label="Meerwerktarieven — horizontaal scrollbaar"><table><caption>Meerwerktarieven</caption><thead><tr><th scope="col">Werk</th><th scope="col">Tarief</th><th scope="col">Voorwaarde</th></tr></thead><tbody><tr><th scope="row">Regie & engineering</th><td>€ 135/uur</td><td>Per kwartier, vooraf gemeld</td></tr><tr><th scope="row">Spoed / buiten kantooruren</th><td>€ 195/uur</td><td>Na expliciete afstemming</td></tr><tr><th scope="row">Bezoek op locatie</th><td>€ 95 voorrijtarief + uurtarief</td><td>Naast reis-/werkafspraken in de scope</td></tr></tbody></table></div><p className={styles.tableNote}>Werk buiten de vaste pakketscope en buiten afgesproken wijzigingsruimte wordt als change order of op uurtarief uitgevoerd.</p></section>

      <section id="advies" className={`${styles.section} ${styles.soft}`}><div className={styles.sectionHead}><p>Advies</p><h2>Een korte scan is gratis. Verdieping is betaald werk.</h2></div><div className={styles.tableWrap} tabIndex={0} role="region" onKeyDown={scrollTariffTable} aria-label="Adviestarieven — horizontaal scrollbaar"><table><caption>Adviestarieven</caption><thead><tr><th scope="col">Dienst</th><th scope="col">Tarief</th><th scope="col">Grens</th></tr></thead><tbody><tr><th scope="row">Korte kansenscan</th><td>Gratis</td><td>Max. circa 30 min., gestandaardiseerd</td></tr><tr><th scope="row">Verdiepend advies</th><td>€ 175/uur</td><td>Workshops, second opinions, architectuur en strategie</td></tr><tr><th scope="row">Dagdeel</th><td>€ 650</td><td>Vooraf afgebakend</td></tr><tr><th scope="row">Dag</th><td>€ 1.200</td><td>Vooraf afgebakend</td></tr><tr><th scope="row">Diepe Kansenscan · 50+</th><td>vanaf € 1.950</td><td>Verrekenbaar bij opdracht binnen 60 dagen</td></tr></tbody></table></div></section>

      <section id="smart-design" className={styles.smartDesign}><div className={styles.designIntro}><p>Aparte premium ontwerplijn</p><h2>AIOW Smart Design.</h2><p>Betaald advies en ontwerp voor nieuwbouw, renovatie en projectontwikkeling. Dit is geen calculatorstand en geen verplichte koppeling aan uitvoering: een Blauwdruk is een zelfstandig product dat de klant ook aan een andere installateur kan geven.</p></div><div className={styles.tableWrap} tabIndex={0} role="region" onKeyDown={scrollTariffTable} aria-label="Smart Design-tarieven — horizontaal scrollbaar"><table><caption>Smart Design-tarieven</caption><thead><tr><th scope="col">Dienst</th><th scope="col">Per m² BVO</th><th scope="col">Of techbudget</th><th scope="col">Minimum</th></tr></thead><tbody><tr><th scope="row">Scan</th><td>€ 3,50/m²</td><td>—</td><td>€ 2.950</td></tr><tr><th scope="row">Blauwdruk</th><td>€ 12,50/m²</td><td>12%</td><td>€ 9.500</td></tr><tr><th scope="row">Regie</th><td>€ 7,50/m²</td><td>5%</td><td>€ 7.500</td></tr></tbody></table></div><p className={styles.tableNote}>Het hoogste bedrag geldt: per m², percentage van het geraamde technologiebudget of minimum. Bij meer dan 10 woningen volgt een projectstaffel via offerte, nooit onder de minima. 50% van de Scan is verrekenbaar bij doorgang naar Blauwdruk; de Blauwdruk is niet verrekenbaar met uitvoering.</p></section>

      <section id="voorbeelden" className={`${styles.section} ${styles.soft}`}><div className={styles.sectionHead}><p>Rekenvoorbeelden</p><h2>Zo werken de gepubliceerde regels.</h2></div><div className={styles.examples}><article><span>Bedrijf · 8 personen</span><h3>Start</h3><p>€ 2.950 aansluiting + 8 × € 49 = <strong>€ 392 per maand</strong>. Het minimum van € 295 is hier niet van toepassing.</p></article><article><span>Woning · 140 m²</span><h3>AIOW Home</h3><p>140 × € 95 = <strong>€ 13.300 aansluiting</strong>. 140 × € 1,25 valt onder het maandminimum, dus <strong>€ 225 per maand</strong>.</p></article><article><span>Villa · 300 m² · € 80.000 techbudget</span><h3>Smart Design</h3><p>Blauwdruk: hoogste van € 3.750, € 9.600 en € 9.500 = <strong>€ 9.600</strong>. Regie: hoogste van € 2.250, € 4.000 en € 7.500 = <strong>€ 7.500</strong>.</p></article><article><span>Project · 4.000 m²</span><h3>Smart Design</h3><p>Blauwdruk: 4.000 × € 12,50 = <strong>€ 50.000</strong>. Regie: 4.000 × € 7,50 = <strong>€ 30.000</strong>, vóór eventuele offerte-afspraken.</p></article></div></section>

      <section id="uitsluitingen" className={styles.boundary}><div><p>Altijd zichtbaar</p><h2>Wat niet in deze bedragen zit.</h2></div><ul><li>Btw</li><li>Hardware, sensoren, bekabeling, montage en fysieke installatie</li><li>Cloud-, AI-, telefonie-, media- en andere leverancierskosten</li><li>Werk buiten vaste pakketscope of begrensde wijzigingsruimte</li><li>Een definitieve technische toezegging vóór de scan</li></ul></section>

      <section className={styles.cta}><p className={shared.eyebrow}>Eerst afbakenen</p><h2>Neem één proces, gebouw of plan mee.</h2><p>De korte gestandaardiseerde kansenscan duurt maximaal circa 30 minuten. Voor organisaties vanaf 50 personen kan een betaalde Diepe Kansenscan passend zijn.</p><button className={shared.primaryButton} onClick={openBooking}>Plan de kansenscan</button></section>
    </main>
    <footer className={shared.footer}><Link href="/" className={shared.logo}><span>AIOW</span><i /></Link><p>AI Operating Workflows</p><div><Link href="/tarieven">Tarieven</Link><Link href="/privacy">Privacy</Link><Link href="/llms.txt">llms.txt</Link></div></footer>
    <BookingModal open={booking} onClose={() => setBooking(false)} returnFocus={bookingTrigger.current} />
  </div>;
}
