import Link from "next/link";
import { pageMetadata } from "@/lib/aiow-v1/seo";
import styles from "../info.module.css";

export const metadata = pageMetadata({ title: "Privacy bij AIOW", description: "Uitleg over de verwerking van gegevens in de AIOW-bookingintake.", path: "/privacy" });

export default function PrivacyPage() {
  return <div className={styles.page}><header className={styles.header}><Link className={styles.brand} href="/">AIOW</Link><Link className={styles.back} href="/">Terug naar home</Link></header><main className={styles.main}><p className={styles.eyebrow}>Privacy</p><h1>Alleen gegevens die nodig zijn voor je aanvraag.</h1><p className={styles.lead}>AIOW gebruikt persoonsgegevens uit de publieke intake uitsluitend om de aangevraagde scan te beoordelen, praktisch af te stemmen en misbruik van het formulier te beperken.</p><section id="booking" className={styles.section}><h2>Bookingintake</h2><ul><li>We vragen onderwerp, datum, tijdslot, naam, e-mailadres, optionele organisatie en optionele toelichting.</li><li>De aanvraag wordt pas geaccepteerd nadat de geconfigureerde intakevoorziening hem duurzaam heeft bevestigd. Zonder die voorziening geeft de site geen nepbevestiging.</li><li>De intakevoorziening ontvangt de ingevulde gegevens, een technisch request-ID, ontvangsttijd en idempotency key. Volledige persoonsgegevens worden niet in applicatielogs geschreven.</li><li>Een verkorte technische hash en tijdelijke tellers kunnen worden gebruikt om buitensporige formulierpogingen af te remmen.</li></ul></section><section className={styles.section}><h2>Bewaren en delen</h2><p>Bookinggegevens worden in de pilot maximaal 90 dagen bewaard, tenzij eerder verwijderen mogelijk is of een lopende klantrelatie of wettelijke verplichting langere bewaring rechtvaardigt. Gegevens worden niet verkocht. Alleen AIOW en de contractueel gekozen intake-/hostingdienst verwerken ze voor dit doel.</p></section><section className={styles.section}><h2>Je rechten en contact</h2><p>Je kunt vragen om inzage, correctie of verwijdering. Gebruik daarvoor <a href="mailto:info@aiow.io">info@aiow.io</a> of de contactgegevens uit je bestaande AIOW-relatie. Vermeld geen gevoelige inhoud die niet nodig is om je verzoek te vinden.</p></section></main><footer className={styles.footer}>Versie 2026-08-27 · van toepassing op de publieke AIOW-bookingintake.</footer></div>;
}
