import { createHash } from "node:crypto";
import { apiError,idempotency,internalPost,json,requestId,requireJson } from "@/lib/aiow-v1/commercial-route";
import { readBoundedJson,validateContractDefinition } from "@/lib/aiow-v1/commercial-api-runtime.mjs";
import { quoteRuntimeData } from "@/lib/aiow-v1/quote-contract.mjs";
import { generateQuotePdf } from "@/lib/aiow-v1/quote-pdf.mjs";
import { loadDurableCommittedQuote,loadDurablePreparedQuote } from "@/lib/aiow-v1/quote-prepared-store.mjs";
export const runtime="nodejs"; const LIMIT=16_384;
async function callAdapter(url:string,secret:string,body:unknown,rid:string,key:string){const response=await internalPost(url,secret,body,rid,key,process.env.AIOW_COMMERCIAL_TEST_MODE==="1");let payload=null;try{payload=await response.json();}catch{}return {response,payload};}
function pdfResponse(pdf:{bytes:Buffer;filename:string;mimeType:string;sha256:string},quoteNumber:string,rid:string){const body=pdf.bytes.buffer.slice(pdf.bytes.byteOffset,pdf.bytes.byteOffset+pdf.bytes.byteLength) as ArrayBuffer;return new Response(body,{status:200,headers:{"content-type":pdf.mimeType,"content-disposition":`attachment; filename="${pdf.filename}"`,"x-aiow-quote-number":quoteNumber,"x-aiow-request-id":rid,"x-aiow-pdf-sha256":pdf.sha256,"cache-control":"no-store"}});}
export async function POST(request:Request){const rid=requestId();if(!requireJson(request))return apiError("quote_prepare","invalid_request",rid,415);const key=idempotency(request);if(!key)return apiError("quote_prepare","invalid_request",rid,400);const url=process.env.AIOW_QUOTE_WEBHOOK_URL,secret=process.env.AIOW_QUOTE_WEBHOOK_SECRET;if(!url||!secret)return apiError("quote_prepare","unavailable",rid,503);let quote;try{quote=(await readBoundedJson(request,LIMIT)).value;}catch(error:any){return apiError("quote_prepare","invalid_request",rid,error?.status===413?413:400);}if(!validateContractDefinition("QuoteRequest",quote))return apiError("quote_prepare","invalid_request",rid,400);
 const receivedAt=new Date().toISOString(),prepare={schemaKind:"quote_prepare_request",requestId:rid,idempotencyKey:key,receivedAt,quote};let prepared:any;try{const {response,payload}=await callAdapter(url,secret,prepare,rid,key);if(response.status===409&&validateContractDefinition("QuotePrepareError",payload))return json(payload,409);if(!response.ok||!validateContractDefinition("QuotePrepareACK",payload))throw new Error("prepare rejected");prepared=payload;}catch{return apiError("quote_prepare","unavailable",rid,502);}
 const authorityRequestId=prepared.requestId,identity={requestId:authorityRequestId,idempotencyKey:key,leadId:prepared.leadId,commercialLeadId:prepared.commercialLeadId,quoteNumber:prepared.quoteNumber};let durable;try{durable=await loadDurablePreparedQuote(identity);}catch{return apiError("quote_commit","unavailable",authorityRequestId,503,"Prepared quote could not be loaded");}if(durable.state==="committed"){try{return pdfResponse(await loadDurableCommittedQuote({...identity,requestPayloadDigest:durable.requestPayloadDigest}),prepared.quoteNumber,authorityRequestId);}catch{return apiError("quote_commit","unavailable",authorityRequestId,503,"Committed quote could not be replayed");}}
 let pdf:Uint8Array;try{const {snapshot,normalized}=quoteRuntimeData(quote);pdf=await generateQuotePdf({quoteNumber:prepared.quoteNumber,snapshot,contact:normalized.contact});}catch{return apiError("quote_commit","unavailable",authorityRequestId,503,"Quote PDF failed");}const pdfSha256=createHash("sha256").update(pdf).digest("hex"),commit={schemaKind:"quote_commit_request",requestId:authorityRequestId,idempotencyKey:key,leadId:prepared.leadId,commercialLeadId:prepared.commercialLeadId,quoteNumber:prepared.quoteNumber,pdf:{filename:`${prepared.quoteNumber}.pdf`,mimeType:"application/pdf",base64:Buffer.from(pdf).toString("base64"),sha256:pdfSha256}};
 try{const {response,payload}=await callAdapter(url,secret,commit,authorityRequestId,key);if(response.status===409&&validateContractDefinition("QuoteCommitError",payload))return json(payload,409);if(!response.ok||!validateContractDefinition("QuoteCommitACK",payload)||payload.requestId!==authorityRequestId||payload.leadId!==prepared.leadId||payload.commercialLeadId!==prepared.commercialLeadId||payload.quoteNumber!==prepared.quoteNumber||payload.pdfSha256!==pdfSha256||payload.state!=="committed"||payload.pdfDeliveryPermitted!==true)throw new Error("commit rejected");return pdfResponse(await loadDurableCommittedQuote({...identity,requestPayloadDigest:durable.requestPayloadDigest}),prepared.quoteNumber,authorityRequestId);}catch{return apiError("quote_commit","unavailable",authorityRequestId,503,"Quote was not committed");}}
