import test from "node:test";
import assert from "node:assert/strict";
import { MAIL_OUTBOX_PATH, canonicalMailOutboxRequest, signMailOutboxRequest, verifyMailOutboxHttpRequest, verifyMailOutboxSignature } from "../../lib/aiow-v1/mail-outbox-auth.mjs";
const secret="s".repeat(40), now=Date.parse("2026-08-30T12:00:00.000Z"), timestamp=String(Math.floor(now/1000));
const bodyBytes=Buffer.from('{"limit":10}',"utf8");
const base={secret,method:"POST",path:MAIL_OUTBOX_PATH,timestamp,requestId:"123e4567-e89b-42d3-a456-426614174000",idempotencyKey:"mail-run-00000001",bodyBytes};
function request(url=`https://worker.aiow.io${MAIL_OUTBOX_PATH}`,body=bodyBytes,overrides={}){const signature=signMailOutboxRequest(base);return new Request(url,{method:"POST",headers:{"x-aiow-webhook-timestamp":timestamp,"x-aiow-request-id":base.requestId,"idempotency-key":base.idempotencyKey,"x-aiow-webhook-signature":signature,...overrides},body});}
test("mail run HMAC binds exact frozen method/path/timestamp/request/idempotency/body digest",()=>{const signature=signMailOutboxRequest(base);assert.match(signature,/^[0-9a-f]{64}$/);assert.equal(verifyMailOutboxSignature({...base,signature,now}),true);assert.equal(canonicalMailOutboxRequest(base),`POST\n${MAIL_OUTBOX_PATH}\n${timestamp}\n${base.requestId}\n${base.idempotencyKey}\n${"ca502dec04523cdc33afece69a9b600d5b9bd022d453791cc693b6b372f808ad"}`);assert.equal(verifyMailOutboxHttpRequest({request:request(),bodyBytes,secret,now}),true);});
test("mail run HMAC rejects tampered method, path, body, metadata, signature and stale timestamp",()=>{const signature=signMailOutboxRequest(base);for(const mutation of [{method:"GET"},{path:"/api/internal/mail-outbox/other"},{bodyBytes:Buffer.from('{"limit":11}')},{requestId:"123e4567-e89b-42d3-a456-426614174001"},{idempotencyKey:"mail-run-00000002"},{signature:"0".repeat(64)}])assert.equal(verifyMailOutboxSignature({...base,signature,...mutation,now}),false);assert.equal(verifyMailOutboxSignature({...base,signature,now:now+301_000}),false);});
test("mail run HTTP verifier requires HTTPS and exact registered path without query",()=>{assert.equal(verifyMailOutboxHttpRequest({request:request(`http://worker.aiow.io${MAIL_OUTBOX_PATH}`),bodyBytes,secret,now}),false);assert.equal(verifyMailOutboxHttpRequest({request:request(`https://worker.aiow.io${MAIL_OUTBOX_PATH}?x=1`),bodyBytes,secret,now}),false);assert.equal(verifyMailOutboxHttpRequest({request:request("https://worker.aiow.io/api/internal/mail-outbox/other"),bodyBytes,secret,now}),false);});
test("bearer-only requests cannot authenticate",()=>{const unsigned=new Request(`https://worker.aiow.io${MAIL_OUTBOX_PATH}`,{method:"POST",headers:{authorization:`Bearer ${secret}`},body:bodyBytes});assert.equal(verifyMailOutboxHttpRequest({request:unsigned,bodyBytes,secret,now}),false);});
