import test from "node:test";
import assert from "node:assert/strict";
import { executeMailOutboxRun, MailOutboxWorkerError } from "../../lib/aiow-v1/mail-outbox-worker.mjs";
const NOW=Date.parse("2026-08-30T12:00:00.000Z");
function item(n=0,attempts=1){return {id:`123e4567-e89b-42d3-a456-4266141740${20+n}`,commercialLeadId:`123e4567-e89b-42d3-a456-4266141740${30+n}`,kind:"internal_lead",revision:7,payloadSha256:String(n).repeat(64),attempts,leaseOwner:"worker-1",leaseToken:`123e4567-e89b-42d3-a456-4266141740${40+n}`,leaseExpiresAt:"2026-08-30T12:05:00.000Z",nextAttemptAt:null,createdAt:`2026-08-30T11:0${n}:00.000Z`};}
function job(i){return {schemaKind:"mail_job",jobId:i.id,commercialLeadId:i.commercialLeadId,kind:i.kind,from:"info@aiow.io",to:["info@aiow.io"],subject:"Nieuwe aanvraag",text:"Nieuwe aanvraag",html:"<p>Nieuwe aanvraag</p>",attachments:[],payloadSha256:i.payloadSha256,attempt:i.attempts,leaseOwner:i.leaseOwner,leaseToken:i.leaseToken,leaseExpiresAt:i.leaseExpiresAt};}
const accepted={schemaKind:"provider_accepted",category:"accepted",code:null,receipt:{provider:"microsoft_graph",httpStatus:202,graphRequestId:null,providerMessageId:null,acceptanceKind:"graph_http_202",attemptReceipt:"receipt",observedAt:"2026-08-30T12:00:00.000Z"}};
const transient={schemaKind:"provider_transient_pre_acceptance",category:"transient_pre_acceptance",code:"graph_5xx",receipt:{...accepted.receipt,httpStatus:503,acceptanceKind:null}};
function setup(items,send=async()=>accepted){const calls=[];return {calls,options:{limit:Math.max(items.length,1),workerId:"worker-1",now:()=>NOW,claim:async(args)=>{calls.push(["claim",args]);return {schemaKind:"outbox_batch_ack",operation:"claim",requestedLimit:Math.max(items.length,1),itemCount:items.length,items};},loadJobs:async()=>items.map(job),loadProviderGate:async()=>({}),finalize:async(name,args)=>calls.push([name,args]),send}};}
test("zero batch returns exact closed mail_run ACK and makes no provider/finalize call",async()=>{const s=setup([]);const result=await executeMailOutboxRun(s.options);assert.deepEqual(result,{schemaKind:"outbox_batch_ack",operation:"mail_run",requestedLimit:1,itemCount:0,items:[]});assert.equal(s.calls.length,1);});
test("one accepted job finalizes with the exact lease owner/token/digest/revision/result CAS",async()=>{const i=item();const s=setup([i]);const result=await executeMailOutboxRun(s.options);assert.equal(result.operation,"mail_run");assert.deepEqual(s.calls[1],["aiow_mail_outbox_sent_v2",{p_job_id:i.id,p_lease_owner:i.leaseOwner,p_lease_token:i.leaseToken,p_payload_digest:i.payloadSha256,p_expected_revision:i.revision,p_result:accepted}]);});
test("multi batch preserves claim order and dispatches each lease exactly once",async()=>{const items=[item(0),item(1),item(2)];const s=setup(items);const result=await executeMailOutboxRun(s.options);assert.deepEqual(result.items.map(x=>x.id),items.map(x=>x.id));assert.equal(s.calls.filter(x=>x[0]==="aiow_mail_outbox_sent_v2").length,3);});
test("429 retry scheduling honors Retry-After and attempt exhaustion is server-authored permanent",async()=>{let i=item(0,2);let s=setup([i],async(_job,_gate,options)=>{options.onRetryAfter(37);return transient;});await executeMailOutboxRun(s.options);assert.equal(s.calls[1][0],"aiow_mail_outbox_retry_v2");assert.equal(s.calls[1][1].p_next_attempt_at,"2026-08-30T12:00:37.000Z");i=item(0,5);s=setup([i],async()=>transient);await executeMailOutboxRun(s.options);assert.equal(s.calls[1][0],"aiow_mail_outbox_dead_v2");assert.equal(s.calls[1][1].p_result.code,"retry_exhausted");assert.equal(s.calls[1][1].p_result.category,"permanent_pre_acceptance");});
test("malformed durable job is permanent/dead without category crossing",async()=>{const i=item();const s=setup([i],async()=>({schemaKind:"provider_permanent_pre_acceptance",category:"permanent_pre_acceptance",code:"invalid_payload",receipt:{...accepted.receipt,httpStatus:400,acceptanceKind:null}}));s.options.loadJobs=async()=>[{...job(i),from:"attacker@example.com"}];await executeMailOutboxRun(s.options);assert.equal(s.calls[1][0],"aiow_mail_outbox_dead_v2");});
test("accepted finalize failure is quarantined through review and never resent",async()=>{const i=item();let finalizations=0;const s=setup([i]);s.options.finalize=async(name,args)=>{s.calls.push([name,args]);if(++finalizations===1)throw new Error("lost CAS");};await executeMailOutboxRun(s.options);assert.deepEqual(s.calls.slice(1).map(x=>x[0]),["aiow_mail_outbox_sent_v2","aiow_mail_outbox_review_v2"]);assert.equal(s.calls[2][1].p_result.category,"ambiguous");});
test("invalid claim cardinality, owner and requested limits fail closed",async()=>{const i=item();for(const mutate of [ack=>({...ack,itemCount:2}),ack=>({...ack,items:[{...i,leaseOwner:"other"}]})]){const s=setup([i]);const claim=s.options.claim;s.options.claim=async(args)=>mutate(await claim(args));await assert.rejects(()=>executeMailOutboxRun(s.options),MailOutboxWorkerError);}await assert.rejects(()=>executeMailOutboxRun({...setup([]).options,limit:51}),MailOutboxWorkerError);});
