import test from "node:test";
import assert from "node:assert/strict";
import { executeMailOutboxRun, MailOutboxWorkerError } from "../../lib/aiow-v1/mail-outbox-worker.mjs";
import { validateMailJobV2 } from "../../lib/aiow-v1/microsoft-graph-provider.mjs";
const NOW=Date.parse("2026-08-30T12:00:00.000Z");
function item(n=0,attempts=1){return {id:`123e4567-e89b-42d3-a456-4266141740${20+n}`,commercialLeadId:`123e4567-e89b-42d3-a456-4266141740${30+n}`,kind:"internal_lead",revision:7,payloadSha256:String(n).repeat(64),attempts,leaseOwner:"worker-1",leaseToken:`123e4567-e89b-42d3-a456-4266141740${40+n}`,leaseExpiresAt:"2026-08-30T12:05:00.000Z",nextAttemptAt:null,createdAt:`2026-08-30T11:0${n}:00.000Z`};}
function job(i){return {schemaKind:"mail_job",jobId:i.id,commercialLeadId:i.commercialLeadId,kind:i.kind,from:"info@aiow.io",to:["info@aiow.io"],subject:"Nieuwe aanvraag",text:"Nieuwe aanvraag",html:"<p>Nieuwe aanvraag</p>",attachments:[],payloadSha256:i.payloadSha256,attempt:i.attempts,leaseOwner:i.leaseOwner,leaseToken:i.leaseToken,leaseExpiresAt:i.leaseExpiresAt};}
const receipt={provider:"microsoft_graph",httpStatus:202,graphRequestId:null,providerMessageId:null,acceptanceKind:"graph_http_202",attemptReceipt:"receipt",observedAt:"2026-08-30T12:00:00.000Z"};
const accepted={schemaKind:"provider_accepted",category:"accepted",code:null,receipt};
const transient={schemaKind:"provider_transient_pre_acceptance",category:"transient_pre_acceptance",code:"graph_5xx",receipt:{...receipt,httpStatus:503,acceptanceKind:null}};
const permanent={schemaKind:"provider_permanent_pre_acceptance",category:"permanent_pre_acceptance",code:"invalid_payload",receipt:{...receipt,httpStatus:400,acceptanceKind:null}};
const ambiguous={schemaKind:"provider_ambiguous",category:"ambiguous",code:"unknown_acceptance",receipt:{...receipt,httpStatus:599,acceptanceKind:null}};
const states={aiow_mail_outbox_sent_v2:"sent",aiow_mail_outbox_retry_v2:"retry",aiow_mail_outbox_dead_v2:"dead",aiow_mail_outbox_review_v2:"review"};
function projection(i,name,args){return {schemaKind:"outbox_projection",id:i.id,commercialLeadId:i.commercialLeadId,kind:i.kind,revision:i.revision+1,payloadSha256:i.payloadSha256,attempts:i.attempts,state:states[name],leaseOwner:null,leaseToken:null,leaseExpiresAt:null,nextAttemptAt:name==="aiow_mail_outbox_retry_v2"?args.p_next_attempt_at:null,lastResult:args.p_result,cancellationReason:null};}
function setup(items,send=async()=>accepted){const calls=[];return {calls,options:{limit:Math.max(items.length,1),workerId:"worker-1",now:()=>NOW,claim:async(args)=>{calls.push(["claim",args]);return {schemaKind:"outbox_batch_ack",operation:"claim",requestedLimit:Math.max(items.length,1),itemCount:items.length,items};},loadJobs:async()=>items.map(job),loadProviderGate:async()=>({}),markDispatch:async(item)=>{calls.push(["dispatch",item.id]);},finalize:async(name,args)=>{calls.push([name,args]);const i=items.find(value=>value.id===args.p_job_id);return projection(i,name,args);},send}};}
test("zero batch returns exact closed mail_run ACK and makes no provider/finalize call",async()=>{const s=setup([]);const result=await executeMailOutboxRun(s.options);assert.deepEqual(result,{schemaKind:"outbox_batch_ack",operation:"mail_run",requestedLimit:1,itemCount:0,items:[]});assert.equal(s.calls.length,1);});
test("one accepted job marks dispatch then finalizes with exact CAS",async()=>{const i=item();const s=setup([i]);const result=await executeMailOutboxRun(s.options);assert.equal(result.operation,"mail_run");assert.deepEqual(s.calls[1],["dispatch",i.id]);assert.deepEqual(s.calls[2],["aiow_mail_outbox_sent_v2",{p_job_id:i.id,p_lease_owner:i.leaseOwner,p_lease_token:i.leaseToken,p_payload_digest:i.payloadSha256,p_expected_revision:i.revision,p_result:accepted}]);});
test("multi batch preserves claim order and marks each lease just before its provider call",async()=>{const items=[item(0),item(1),item(2)];const order=[];const s=setup(items,async(job)=>{order.push(`provider:${job.jobId}`);return accepted;});s.options.markDispatch=async(item)=>{order.push(`dispatch:${item.id}`);};const result=await executeMailOutboxRun(s.options);assert.deepEqual(result.items.map(x=>x.id),items.map(x=>x.id));assert.deepEqual(order,items.flatMap(item=>[`dispatch:${item.id}`,`provider:${item.id}`]));});
test("retry scheduling is exactly lease-bound and Retry-After cannot conflict",async()=>{for(const [attempt,expected] of [[1,"2026-08-30T12:01:00.000000Z"],[2,"2026-08-30T12:05:00.000000Z"],[3,"2026-08-30T12:30:00.000000Z"],[4,"2026-08-30T14:00:00.000000Z"]]){const i=item(0,attempt);const s=setup([i],async(_job,_gate,options)=>{options.onRetryAfter(37);return transient;});s.options.now=()=>NOW+29_000;await executeMailOutboxRun(s.options);const retry=s.calls.find(([name])=>name==="aiow_mail_outbox_retry_v2");assert.equal(retry[1].p_next_attempt_at,expected);}const i=item(0,5),s=setup([i],async()=>transient);await executeMailOutboxRun(s.options);const dead=s.calls.find(([name])=>name==="aiow_mail_outbox_dead_v2");assert.equal(dead[1].p_result.code,"retry_exhausted");});

test("crash boundaries never duplicate provider calls and dispatch precedes possible acceptance",async()=>{for(const point of ["beforeProviderCall","afterProviderResult","beforeFinalize"]){const i=item();let providerCalls=0;const s=setup([i],async()=>{providerCalls++;return accepted;});s.options[point]=async()=>{throw new Error(`crash:${point}`);};await assert.rejects(()=>executeMailOutboxRun(s.options),new RegExp(`crash:${point}`));assert.equal(providerCalls,point==="beforeProviderCall"?0:1);assert.equal(s.calls.filter(([name])=>name.startsWith("aiow_mail_outbox_")).length,0);assert.equal(s.calls.filter(([name])=>name==="dispatch").length,point==="beforeProviderCall"?0:1);}});
test("malformed durable job is classified locally and dead without dispatch or provider call",async()=>{const i=item();let providerCalls=0;const s=setup([i],async()=>{providerCalls++;return permanent;});s.options.loadJobs=async()=>[{...job(i),from:"attacker@example.com"}];await executeMailOutboxRun(s.options);assert.equal(providerCalls,0);assert.equal(s.calls.some(([name])=>name==="dispatch"),false);assert.equal(s.calls.find(([name])=>name==="aiow_mail_outbox_dead_v2")[0],"aiow_mail_outbox_dead_v2");});
test("valid jobs with any lease-bound identity mismatch never dispatch, call provider, or finalize",async()=>{const mutations=[
  value=>({...value,commercialLeadId:"123e4567-e89b-42d3-a456-426614174099"}),
  value=>({...value,kind:"internal_booking"}),
  value=>({...value,payloadSha256:"f".repeat(64)}),
  value=>({...value,attempt:2}),
  value=>({...value,leaseOwner:"worker-2"}),
  value=>({...value,leaseToken:"123e4567-e89b-42d3-a456-426614174099"}),
  value=>({...value,leaseExpiresAt:"2026-08-30T12:06:00.000Z"}),
];for(const mutate of mutations){const i=item();let providerCalls=0,finalizeCalls=0;const mismatched=mutate(job(i));assert.equal(validateMailJobV2(mismatched),true);const s=setup([i],async()=>{providerCalls++;return accepted;});s.options.loadJobs=async()=>[mismatched];s.options.finalize=async()=>{finalizeCalls++;throw new Error("must not finalize");};await assert.rejects(()=>executeMailOutboxRun(s.options),error=>error instanceof MailOutboxWorkerError&&error.code==="mail_job_lease_mismatch"&&error.status===503);assert.equal(providerCalls,0);assert.equal(finalizeCalls,0);assert.equal(s.calls.some(([name])=>name==="dispatch"),false);}});
test("accepted malformed or mismatched finalize ACK is quarantined through validated review and never resent",async()=>{for(const mutate of [()=>({}),p=>({...p,id:"123e4567-e89b-42d3-a456-426614174099"}),p=>({...p,state:"dead"}),p=>({...p,revision:p.revision+1}),p=>({...p,payloadSha256:"f".repeat(64)})]){const i=item();const s=setup([i]);let first=true;s.options.finalize=async(name,args)=>{s.calls.push([name,args]);if(first){first=false;return mutate(projection(i,name,args));}return projection(i,name,args);};await executeMailOutboxRun(s.options);assert.deepEqual(s.calls.map(x=>x[0]).filter(name=>name.startsWith("aiow_mail_outbox_")),["aiow_mail_outbox_sent_v2","aiow_mail_outbox_review_v2"]);assert.equal(s.calls.find(([name])=>name==="aiow_mail_outbox_review_v2")[1].p_result.category,"ambiguous");}});
test("accepted ambiguous finalize that cannot be quarantined fails closed",async()=>{const i=item();const s=setup([i]);s.options.finalize=async(name,args)=>{s.calls.push([name,args]);return {...projection(i,name,args),revision:i.revision};};await assert.rejects(()=>executeMailOutboxRun(s.options),error=>error instanceof MailOutboxWorkerError&&error.code==="finalize_conflict");assert.deepEqual(s.calls.map(x=>x[0]).filter(name=>name.startsWith("aiow_mail_outbox_")),["aiow_mail_outbox_sent_v2","aiow_mail_outbox_review_v2"]);});
test("every result RPC rejects malformed, wrong job/state/revision/digest projections",async()=>{const cases=[[transient,"aiow_mail_outbox_retry_v2"],[permanent,"aiow_mail_outbox_dead_v2"],[ambiguous,"aiow_mail_outbox_review_v2"]];for(const [result,rpc] of cases){for(const mutate of [()=>({}),p=>({...p,id:"123e4567-e89b-42d3-a456-426614174099"}),p=>({...p,state:"sent"}),p=>({...p,revision:p.revision+1}),p=>({...p,payloadSha256:"f".repeat(64)})]){const i=item();const s=setup([i],async()=>result);s.options.finalize=async(name,args)=>{s.calls.push([name,args]);return mutate(projection(i,name,args));};await assert.rejects(()=>executeMailOutboxRun(s.options),error=>error instanceof MailOutboxWorkerError&&error.code==="finalize_conflict");assert.equal(s.calls.find(([name])=>name===rpc)[0],rpc);}}});
test("invalid claim cardinality, owner and requested limits fail closed",async()=>{const i=item();for(const mutate of [ack=>({...ack,itemCount:2}),ack=>({...ack,items:[{...i,leaseOwner:"other"}]})]){const s=setup([i]);const claim=s.options.claim;s.options.claim=async(args)=>mutate(await claim(args));await assert.rejects(()=>executeMailOutboxRun(s.options),MailOutboxWorkerError);}await assert.rejects(()=>executeMailOutboxRun({...setup([]).options,limit:51}),MailOutboxWorkerError);});
