import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { buildProviderGateApprovalBindingDigestV1 } from "../../lib/aiow-v1/commercial-contract-validator.mjs";
import { buildCustomerBookingTemplateV2, buildMicrosoftGraphMessage, sendMicrosoftGraphJob, validateMailJobV2 } from "../../lib/aiow-v1/microsoft-graph-provider.mjs";

const NOW = Date.parse("2026-08-30T12:00:00.000Z");
const pdf = Buffer.from("%PDF-1.7\nproof");
const attachment = {filename:"AIOW-2026-0001.pdf",mimeType:"application/pdf",base64:pdf.toString("base64"),sha256:createHash("sha256").update(pdf).digest("hex")};
const job = {schemaKind:"mail_job",jobId:"123e4567-e89b-42d3-a456-426614174000",commercialLeadId:"123e4567-e89b-42d3-a456-426614174001",kind:"customer_quote",from:"info@aiow.io",to:["customer@example.com"],subject:"Uw offerte",text:"Beste klant\nUw offerte.",html:"<p>Beste klant</p>\n<p>Uw offerte.</p>",attachments:[attachment],payloadSha256:"a".repeat(64),attempt:1,leaseOwner:"worker-1",leaseToken:"123e4567-e89b-42d3-a456-426614174002",leaseExpiresAt:"2026-08-30T12:05:00.000Z"};
const gateBase = {schemaKind:"provider_gate_record",gateId:"mail_provider_production_v1",state:"activated",environment:"production",provider:"microsoft_graph",tenantId:"123e4567-e89b-42d3-a456-426614174010",applicationId:"123e4567-e89b-42d3-a456-426614174011",mailbox:"info@aiow.io",sender:"info@aiow.io",controlMailbox:"rbac-control@aiow.io",secretPresent:true,oauthClientCredentialsPresent:true,exchangeApplicationRole:"Application Mail.Send",exchangeRbacSenderInScope:true,exchangeRbacControlMailboxInScope:false,entraUnscopedMailSendAssigned:false,evidenceSha256:"b".repeat(64),revision:1,ownerApprovedBy:"richard",approvedAt:"2026-08-30T11:00:00.000Z",expiresAt:"2026-08-30T13:00:00.000Z",runtimeCapability:"mail_send",fallbackProvider:null};
const gate = {...gateBase,approvalBindingSha256:buildProviderGateApprovalBindingDigestV1(gateBase)};
const target = Object.fromEntries(["gateId","environment","provider","tenantId","applicationId","mailbox","sender","controlMailbox","runtimeCapability","fallbackProvider"].map((key)=>[key,gate[key]]));
const options = {clientSecret:"secret",target,now:()=>NOW,tokenUrl:"http://local/token",graphUrl:"http://local/send"};
const token = () => new Response(JSON.stringify({access_token:"token-123456",token_type:"Bearer",expires_in:3600}),{status:200});

test("Graph JSON preserves exact sender, CRLF body and verified PDF bytes",()=>{ assert.equal(validateMailJobV2(job),true); const value=buildMicrosoftGraphMessage(job); assert.equal(value.message.from.emailAddress.address,"info@aiow.io"); assert.equal(value.message.attachments[0].contentBytes,pdf.toString("base64")); assert.ok(!/(?<!\r)\n/.test(value.message.body.content)); assert.throws(()=>buildMicrosoftGraphMessage({...job,attachments:[{...attachment,sha256:"0".repeat(64)}]}),/invalid/); });
test("category crossing, header injection and oversized Graph requests fail closed",()=>{ assert.equal(validateMailJobV2({...job,kind:"internal_lead"}),false); assert.equal(validateMailJobV2({...job,subject:"ok\r\nBcc: bad@example.com"}),false); const huge={...job,html:"x".repeat(49_999),attachments:[{...attachment,base64:Buffer.alloc(1_499_997).toString("base64"),sha256:createHash("sha256").update(Buffer.alloc(1_499_997)).digest("hex")}]}; assert.throws(()=>buildMicrosoftGraphMessage(huge)); });
test("OAuth client credentials and Graph 202 empty body produce explicit accepted receipt",async()=>{ const calls=[]; const fetchImpl=async(url,init)=>{calls.push([url,init]);return calls.length===1?token():new Response(null,{status:202,headers:{"request-id":"graph-request-1"}});}; const result=await sendMicrosoftGraphJob(job,gate,{...options,fetchImpl}); assert.equal(String(calls[0][1].body),"client_id=123e4567-e89b-42d3-a456-426614174011&client_secret=secret&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&grant_type=client_credentials"); assert.equal(calls[1][1].headers.authorization,"Bearer token-123456"); assert.deepEqual({category:result.category,status:result.receipt.httpStatus,id:result.receipt.providerMessageId,kind:result.receipt.acceptanceKind},{category:"accepted",status:202,id:null,kind:"graph_http_202"}); });
test("401/403 permanent, 429 Retry-After and 5xx transient are classified pre-acceptance",async()=>{ for(const [status,category,code] of [[401,"permanent_pre_acceptance","oauth_authentication_failed"],[403,"permanent_pre_acceptance","exchange_rbac_denied"],[503,"transient_pre_acceptance","graph_5xx"]]) { let count=0; const fetchImpl=async()=>++count===1?token():new Response("{}",{status}); const result=await sendMicrosoftGraphJob(job,gate,{...options,fetchImpl}); assert.equal(result.category,category); assert.equal(result.code,code); } let retryAfter=0,count=0; const result=await sendMicrosoftGraphJob(job,gate,{...options,onRetryAfter:(value)=>retryAfter=value,fetchImpl:async()=>++count===1?token():new Response("{}",{status:429,headers:{"retry-after":"37"}})}); assert.equal(result.code,"throttled_429"); assert.equal(retryAfter,37); });
test("OAuth token stage classifies 429/5xx transient with bounded Retry-After and definitive failures permanent",async()=>{for(const status of [500,503]){const result=await sendMicrosoftGraphJob(job,gate,{...options,fetchImpl:async()=>new Response("{}",{status})});assert.equal(result.category,"transient_pre_acceptance");assert.equal(result.code,"graph_5xx");}for(const status of [400,401,403]){const result=await sendMicrosoftGraphJob(job,gate,{...options,fetchImpl:async()=>new Response(JSON.stringify({error:"invalid_client"}),{status})});assert.equal(result.category,"permanent_pre_acceptance");assert.equal(result.code,"oauth_authentication_failed");}for(const [header,expected] of [["37",37],["99999",3600],["0",1],["nonsense",0]]){let retryAfter=0;const result=await sendMicrosoftGraphJob(job,gate,{...options,onRetryAfter:value=>retryAfter=value,fetchImpl:async()=>new Response("{}",{status:429,headers:{"retry-after":header}})});assert.equal(result.category,"transient_pre_acceptance");assert.equal(result.code,"throttled_429");assert.equal(retryAfter,expected);}});
test("customer booking template is deterministic and validator enforces pending human confirmation truth",()=>{for(const locale of ["nl","en"]){const template=buildCustomerBookingTemplateV2({locale,customerName:"Ada",preference:"31 augustus 2026, 10:00"});assert.deepEqual(template,buildCustomerBookingTemplateV2({locale,customerName:"Ada",preference:"31 augustus 2026, 10:00"}));const booking={...job,kind:"customer_booking",to:["ada@example.com"],attachments:[],...template};assert.equal(validateMailJobV2(booking),true);for(const claim of ["Your appointment is confirmed.","Booking confirmed.","Confirmed appointment.","Uw afspraak is bevestigd.","Bevestigde afspraak.","Definitief ingepland.","De afspraak staat vast."])assert.equal(validateMailJobV2({...booking,text:`${booking.text}\n${claim}`}),false);assert.equal(validateMailJobV2({...booking,text:booking.text.replace(locale==="nl"?"Een medewerker bevestigt de afspraak afzonderlijk.":"A member of our team will confirm the appointment separately.","")}),false);}});
test("disconnect after Graph request body is ambiguous and never retryable",async()=>{ let count=0; const result=await sendMicrosoftGraphJob(job,gate,{...options,fetchImpl:async()=>{if(++count===1)return token();throw new Error("socket lost");}}); assert.equal(result.category,"ambiguous"); assert.equal(result.code,"connection_lost_after_dispatch"); });
test("expired, revoked, target mismatch, missing RBAC and unscoped Entra grants prevent all HTTP",async()=>{ for(const mutant of [{...gate,state:"revoked"},{...gate,expiresAt:"2026-08-30T12:00:00.000Z"},{...gate,exchangeRbacSenderInScope:false},{...gate,exchangeRbacControlMailboxInScope:true},{...gate,entraUnscopedMailSendAssigned:true}]) { let calls=0; const bound={...mutant,approvalBindingSha256:buildProviderGateApprovalBindingDigestV1(mutant)}; const result=await sendMicrosoftGraphJob(job,bound,{...options,fetchImpl:async()=>{calls++;return token();}}); assert.equal(result.category,"permanent_pre_acceptance"); assert.equal(calls,0); } let calls=0; const result=await sendMicrosoftGraphJob(job,gate,{...options,target:{...target,mailbox:"other@aiow.io"},fetchImpl:async()=>{calls++;return token();}}); assert.equal(result.code,"exchange_rbac_denied"); assert.equal(calls,0); });
