import { createHash } from "node:crypto";
import { apiError,json,requestId as newRequestId,requireJson } from "@/lib/aiow-v1/commercial-route";
import { commercialRpc,readBoundedJson,serviceConfigured,validIdempotencyKey,validRequestId,validateContractDefinition,verifyHmac } from "@/lib/aiow-v1/commercial-api-runtime.mjs";
import { quoteMails } from "@/lib/aiow-v1/quote-contract.mjs";
import { loadDurablePreparedQuote } from "@/lib/aiow-v1/quote-prepared-store.mjs";
export const runtime="nodejs";const LIMIT=2*1024*1024;
function failure(kind:"quote_prepare"|"quote_commit",code:string,rid:string,status:number){return apiError(kind,code,rid,status);}
export async function POST(request:Request){const fallback=newRequestId(),secret=process.env.AIOW_QUOTE_WEBHOOK_SECRET;if(!secret||!serviceConfigured())return failure("quote_prepare","unavailable",fallback,503);if(!requireJson(request))return failure("quote_prepare","invalid_request",fallback,415);let parsed;try{parsed=await readBoundedJson(request,LIMIT);}catch(error:any){return failure("quote_prepare","invalid_request",fallback,error?.status===413?413:400);}const rid=request.headers.get("x-aiow-request-id")??"",key=request.headers.get("idempotency-key")??"",timestamp=request.headers.get("x-aiow-webhook-timestamp")??"",signature=request.headers.get("x-aiow-webhook-signature")??"",url=new URL(request.url),kind=parsed.value?.schemaKind==="quote_commit_request"?"quote_commit":"quote_prepare";if(!validRequestId(rid)||!validIdempotencyKey(key)||!verifyHmac({secret,signature,method:"POST",path:`${url.pathname}${url.search}`,timestamp,requestId:rid,idempotencyKey:key,bodyBytes:parsed.bytes}))return failure(kind,"unauthenticated",validRequestId(rid)?rid:fallback,401);
 try{if(kind==="quote_prepare"){if(!validateContractDefinition("QuotePrepareRequest",parsed.value)||parsed.value.requestId!==rid||parsed.value.idempotencyKey!==key)return failure(kind,"invalid_request",rid,400);const q=parsed.value.quote,ack=await commercialRpc("aiow_quote_prepare_v1",{p_request_id:rid,p_idempotency_key:key,p_received_at:parsed.value.receivedAt,p_country:q.country,p_quote:q,p_contact:q.contact,p_consent:q.consent,p_source:q.source});if(!validateContractDefinition("QuotePrepareACK",ack))throw new Error("malformed prepare ACK");return json(ack,200);}
 if(!validateContractDefinition("QuoteCommitRequest",parsed.value)||parsed.value.requestId!==rid||parsed.value.idempotencyKey!==key)return failure(kind,"invalid_request",rid,400);const saved=await loadDurablePreparedQuote({requestId:rid,idempotencyKey:key,leadId:parsed.value.leadId,commercialLeadId:parsed.value.commercialLeadId,quoteNumber:parsed.value.quoteNumber});const pdfBytes=Buffer.from(parsed.value.pdf.base64,"base64");if(createHash("sha256").update(pdfBytes).digest("hex")!==parsed.value.pdf.sha256)return failure(kind,"invalid_request",rid,400);const {snapshot,customerMail,internalMail}=quoteMails(saved.quote,parsed.value.quoteNumber,saved.receivedAt);const ack=await commercialRpc("aiow_quote_commit_v1",{p_request_id:rid,p_idempotency_key:key,p_quote_number:parsed.value.quoteNumber,p_lead_id:parsed.value.leadId,p_pdf_filename:parsed.value.pdf.filename,p_pdf_mime_type:parsed.value.pdf.mimeType,p_pdf_base64:parsed.value.pdf.base64,p_pdf_sha256:parsed.value.pdf.sha256,p_customer_mail:customerMail,p_internal_mail:internalMail,p_quote:snapshot,p_contact:saved.quote.contact,p_source:saved.quote.source,p_country:saved.quote.country});if(!validateContractDefinition("QuoteCommitACK",ack)||ack.requestId!==rid||ack.pdfSha256!==parsed.value.pdf.sha256)throw new Error("malformed commit ACK");return json(ack,200);
 }catch(error:any){console.error("[quote-adapter] failure",{kind,requestId:rid,code:String(error?.code??"unknown").slice(0,80),status:Number.isInteger(error?.status)?error.status:null,pgCode:typeof error?.payload?.code==="string"?error.payload.code.slice(0,20):null,pgMessage:typeof error?.payload?.message==="string"?error.payload.message.slice(0,120):null});const conflict=error?.status===409,invalid=error?.status===400;return failure(kind,conflict?"idempotency_conflict":invalid?"invalid_request":"unavailable",rid,conflict?409:invalid?400:503);}}
