export type SeoPageData = {
  slug: string;
  type: "service" | "region";
  title: string;
  h1: string;
  description: string;
  intro: string;
  intentAnswer: string;
  keywords: string[];
  audiences: string[];
  useCases: string[];
  privacy: string;
  faqs: { q: string; a: string }[];
};

export const CTA = "Plan een gratis quick check";

export const seoPages: Record<string, SeoPageData> = {

  "ai-installateur-nederland": {
    slug: "ai-installateur-nederland",
    type: "service",
    title: "AI-installateur voor bedrijven in Nederland",
    h1: "AI-installateur voor bedrijven in Nederland",
    description: "AIOW is de AI-installateur voor Nederlandse bedrijven: veilige AI-systemen, agents, lokale/private AI, koppelingen, governance en menselijke approvals.",
    intro: "Een AI-installateur helpt niet alleen met advies, maar installeert een werkend AI-systeem rond processen, data, tools, rechten en mensen. AIOW focust volledig op Nederlandse bedrijven.",
    intentAnswer: "Een AI-installateur voor bedrijven ontwerpt, bouwt en beheert praktische AI-oplossingen: van AI-scan en proceskeuze tot agents, documentverwerking, lokale/private AI, cloud-routing, logging en menselijke goedkeuring.",
    keywords: ["AI installateur Nederland", "AI-installateur bedrijf", "AI instalateur", "AI oplossing installeren", "AI implementatie Nederland"],
    audiences: ["MKB-directie", "operations teams", "installatiebedrijven en technische dienstverleners", "logistiek, finance en backoffice"],
    useCases: ["AI-systeem installeren rond inbox, offertes, planning en documenten.", "AI-agents inrichten met rollen, geheugen, logging en approvalregels.", "Lokale/private AI installeren op eigen of private infrastructuur waar data gevoelig is.", "Cloudmodellen zoals GPT/Claude veilig routeren volgens bedrijfsbeleid."],
    privacy: "AIOW installeert AI niet als losse tool, maar als gecontroleerde werklaag. Per workflow bepalen we wat lokaal blijft, wat naar cloudmodellen mag, wie mag goedkeuren en welke logs nodig zijn.",
    faqs: [
      { q: "Wat doet een AI-installateur?", a: "Een AI-installateur vertaalt bedrijfsprocessen naar werkende AI-systemen met koppelingen, beveiliging, modelkeuze, governance en menselijke controle." },
      { q: "Is AIOW een AI-installateur of consultant?", a: "AIOW doet beide, maar de focus ligt op bouwen en installeren: een veilige AI-werklaag die in het bedrijf gebruikt kan worden." },
      { q: "Voor welke bedrijven is dit bedoeld?", a: "Voor Nederlandse MKB-bedrijven, logistieke teams, installatiebedrijven, backoffice, finance, support en technische organisaties." },
      { q: "Kan AI lokaal geïnstalleerd worden?", a: "Ja, waar dat zinvol is kan AIOW lokale/private AI ontwerpen op eigen of private infrastructuur." },
      { q: "Hoe start je veilig?", a: "Met een AI-systeemscan: één proces kiezen, datagrens bepalen, risico's zichtbaar maken en een kleine pilot bouwen." },
    ],
  },
  "ai-oplossingen-bedrijven": {
    slug: "ai-oplossingen-bedrijven",
    type: "service",
    title: "AI-oplossingen voor bedrijven in Nederland",
    h1: "AI-oplossingen voor bedrijven in Nederland",
    description: "Concrete AI-oplossingen voor Nederlandse bedrijven: klantcontact, offertes, planning, documenten, finance, logistiek en interne kennis.",
    intro: "Bedrijven zoeken geen AI-hype, maar oplossingen die dagelijks werk rustiger, sneller en veiliger maken. AIOW bouwt AI-oplossingen rond één concreet proces tegelijk.",
    intentAnswer: "AI-oplossingen voor bedrijven zijn praktische systemen die informatie lezen, samenvatten, vergelijken, routeren, concepten maken en taken voorbereiden met duidelijke menselijke controle.",
    keywords: ["AI oplossingen bedrijven", "AI oplossing bedrijf Nederland", "AI automatisering bedrijf", "AI systeem bedrijf", "AI voor MKB"],
    audiences: ["MKB-bedrijven", "zakelijke dienstverleners", "logistieke bedrijven", "teams met veel mail, documenten en planning"],
    useCases: ["Klantcontact samenvatten, prioriteren en conceptantwoorden voorbereiden.", "Offertes en proposals voorbereiden met klant- en documentcontext.", "Planning, taken en overdracht zichtbaar maken per eigenaar.", "Documenten doorzoeken, vergelijken en signaleren waar informatie ontbreekt."],
    privacy: "Elke AI-oplossing krijgt een datagrens: welke informatie mag gebruikt worden, welke modelroute past, wat moet lokaal blijven en wanneer is menselijke approval verplicht.",
    faqs: [
      { q: "Welke AI-oplossingen zijn geschikt voor bedrijven?", a: "Vooral processen met veel herhaling, tekst, documenten, klantvragen, planning of overdracht zijn geschikt voor een eerste AI-oplossing." },
      { q: "Bouwt AIOW maatwerk of gebruikt het bestaande tools?", a: "Beide kan. We starten vanuit het proces en kiezen daarna bestaande tools, lokale AI, cloudmodellen of maatwerk waar dat verstandig is." },
      { q: "Kan AI gekoppeld worden aan bestaande software?", a: "Ja, maar pas nadat de workflow veilig en bewezen is. Eerst klein testen, daarna koppelen." },
      { q: "Is dit bedoeld voor de Nederlandse markt?", a: "Ja. AIOW focust op Nederlandse bedrijven, Nederlandse zoekintentie, AVG-bewuste keuzes en praktische MKB-processen." },
      { q: "Wat is de eerste stap?", a: "Een AI-systeemscan om kansen, risico's, data en quick wins concreet te maken." },
    ],
  },
  "ai-agents-bedrijven": {
    slug: "ai-agents-bedrijven",
    type: "service",
    title: "AI-agents voor Nederlandse bedrijven",
    h1: "AI-agents voor Nederlandse bedrijven",
    description: "AI-agents voor bedrijven: taken lezen, routeren, schrijven, overdragen en laten goedkeuren met logging, rollen en veilige datagrens.",
    intro: "AI-agents worden pas waardevol als ze in een gecontroleerd systeem werken: met duidelijke taken, tools, geheugen, rechten, logs en menselijke approvals.",
    intentAnswer: "AI-agents voor bedrijven zijn digitale werkers die afgebakende taken uitvoeren, zoals triage, samenvatten, concepten maken, gegevens ophalen en overdracht voorbereiden, zonder onbeheerd gevoelige acties te doen.",
    keywords: ["AI agents bedrijven", "AI agent bedrijf Nederland", "AI medewerkers MKB", "AI workflow agents", "agentic AI Nederland"],
    audiences: ["operations", "support", "sales/admin", "finance en documentteams"],
    useCases: ["Inbox-agent die urgentie, eigenaar en conceptantwoord voorbereidt.", "Document-agent die contracten, offertes of procedures samenvat.", "Planning-agent die open acties en deadlines zichtbaar maakt.", "Approval-agent die externe acties eerst langs mensen routeert."],
    privacy: "Agents krijgen geen onbeperkte vrijheid. AIOW ontwerpt rechten, logs, veilige routes, local/cloud beleid en approval gates voordat agents worden ingezet.",
    faqs: [
      { q: "Wat is een AI-agent?", a: "Een AI-agent is een AI-systeem dat een afgebakende taak met context en tools kan uitvoeren, bijvoorbeeld samenvatten, routeren of een concept voorbereiden." },
      { q: "Zijn AI-agents veilig voor bedrijven?", a: "Alleen als ze beperkt, gelogd en gecontroleerd zijn. AIOW bouwt agents met rollen, datagrens en menselijke approvals." },
      { q: "Kunnen agents mails versturen of systemen aanpassen?", a: "Dat kan technisch, maar bij AIOW blijven externe, publieke, destructieve of gevoelige acties achter expliciete menselijke goedkeuring." },
      { q: "Welke processen zijn geschikt voor agents?", a: "Triage, samenvatten, concepten, documentcontrole, overdracht, rapportages en signalering zijn goede startpunten." },
      { q: "Hoe begin je met AI-agents?", a: "Start met één proces en een AI-systeemscan, niet met tien agents tegelijk." },
    ],
  },
  "ai-implementatie-bedrijf": {
    slug: "ai-implementatie-bedrijf",
    type: "service",
    title: "AI-implementatie voor bedrijven",
    h1: "AI-implementatie voor bedrijven",
    description: "AI-implementatie voor Nederlandse bedrijven: van scan en roadmap naar veilige pilot, lokale/private AI, agents, training en beheer.",
    intro: "Goede AI-implementatie begint niet bij een tool, maar bij werk: welk proces moet sneller, veiliger of consistenter worden en welke data mag daarvoor gebruikt worden?",
    intentAnswer: "AI-implementatie voor bedrijven is het proces van kansen kiezen, data classificeren, modelroutes bepalen, een veilige pilot bouwen, medewerkers trainen en daarna pas opschalen.",
    keywords: ["AI implementatie bedrijf", "AI implementatie Nederland", "AI implementatie MKB", "AI project bedrijf", "AI roadmap bedrijf"],
    audiences: ["directie", "IT en operations", "MKB management", "teams die ChatGPT al gebruiken zonder beleid"],
    useCases: ["AI-roadmap maken voor eerste 90 dagen.", "Shadow AI omzetten naar beheerde processen.", "Pilot bouwen met meetbare impact en menselijke review.", "Team trainen in veilig gebruik, prompting, approvals en escalatie."],
    privacy: "Implementatie betekent ook beleid: rollen, datagrens, logging, bewaartermijnen, modelkeuze en menselijke review worden onderdeel van het systeem.",
    faqs: [
      { q: "Hoe implementeer je AI veilig in een bedrijf?", a: "Begin met één proces, bepaal data en risico's, bouw een kleine pilot, meet resultaat en schaal pas daarna op." },
      { q: "Is een AI-roadmap nodig?", a: "Ja, maar kort en praktisch. De roadmap moet keuzes maken over proces, data, model, eigenaar en risico." },
      { q: "Kan AIOW medewerkers trainen?", a: "Ja. Training hoort bij implementatie, vooral rond veilig gebruik, approvals en wat AI juist niet mag doen." },
      { q: "Hoe voorkom je losse AI-tools?", a: "Door AI in één werklaag te plaatsen met beleid, logging, eigenaarschap en duidelijke use-cases." },
      { q: "Wat levert de eerste pilot op?", a: "Bewijs: tijdwinst, risico's, kwaliteit, adoption en wat nodig is voor de volgende stap." },
    ],
  },
  "ai-integratie-mkb": {
    slug: "ai-integratie-mkb",
    type: "service",
    title: "AI-integratie voor MKB-bedrijven",
    h1: "AI-integratie voor MKB-bedrijven",
    description: "Praktische AI-integratie voor Nederlandse MKB-bedrijven: inbox, planning, offertes, kennis, administratie en operations met menselijke controle.",
    intro: "AIOW bouwt AI-systemen rond het echte werk van MKB-teams: documenten, inboxen, planning, sales, administratie en operationele overdracht.",
    intentAnswer: "AI-integratie voor MKB betekent niet één losse chatbot, maar een bestuurbaar systeem dat repetitief werk herkent, informatie veilig ophaalt, concepten voorbereidt en taken overdraagt aan mensen met duidelijke goedkeuring.",
    keywords: ["AI integratie MKB", "AI systeem bedrijf", "AI automatisering bedrijf", "AI agents bedrijfsprocessen"],
    audiences: ["directie en operations", "sales en administratie", "klantcontact", "planning en backoffice"],
    useCases: ["Inbox triage met prioriteit, samenvatting en conceptantwoord.", "Offertes voorbereiden op basis van eerdere documenten en klantcontext.", "Interne kennisbank voor procedures, contracten en productinformatie.", "Dagelijkse operations-briefing met open acties, risico's en eigenaar."],
    privacy: "We bepalen per proces wat lokaal kan blijven, wat naar goedgekeurde cloudmodellen mag en waar menselijke review verplicht blijft. Gevoelige of externe acties blijven achter expliciete goedkeuring.",
    faqs: [
      { q: "Wat is AI-integratie voor MKB?", a: "Het koppelen van AI aan bestaande bedrijfsprocessen zoals mail, documenten, planning, offertes en klantopvolging, met duidelijke rollen en controle." },
      { q: "Wat kost AI-integratie voor MKB?", a: "Dat hangt af van scope, data en koppelingen. Een gratis quick check bepaalt of een betaalde AI-systeemscan of directe Starter-installatie logisch is." },
      { q: "Is dit anders dan een chatbot?", a: "Ja. Een chatbot beantwoordt vragen; een AI-systeem routeert werk, bewaart context, gebruikt tools en laat mensen goedkeuren." },
      { q: "Welke processen kun je veilig automatiseren?", a: "Vooral voorbereidende stappen: zoeken, samenvatten, concepten maken, vergelijken, signaleren en opvolging klaarzetten." },
      { q: "Blijft bedrijfsdata privé?", a: "AIOW ontwerpt per proces lokale, private of hybride routes. We doen geen absolute claims zonder technische review." },
    ],
  },
  "ai-automatisering-logistiek-transport": {
    slug: "ai-automatisering-logistiek-transport",
    type: "service",
    title: "AI-automatisering voor logistiek en transport",
    h1: "AI-automatisering voor logistiek en transport",
    description: "AI-systemen voor logistiek, transport, warehouse en import/export: shipment exceptions, douanedocs, supplier follow-up en operations briefings.",
    intro: "AIOW helpt logistieke en transportbedrijven met AI rond tijdkritische informatie, documentstromen en operationele overdracht.",
    intentAnswer: "AI kan logistiek en transport helpen door zendingsexcepties sneller te signaleren, mails en documenten samen te vatten, douane- en import/exportinformatie te structureren en planners met concrete vervolgstappen te ondersteunen.",
    keywords: ["AI automatisering logistiek", "AI voor transportbedrijf", "AI voor import export", "AI voor warehouse"],
    audiences: ["transportplanning", "import/export teams", "warehouse operations", "customer service logistics"],
    useCases: ["Shipment exceptions uit mail en portals omzetten naar prioriteitenlijst.", "Douane-, pakbon- en transportdocumenten samenvatten en controleren op ontbrekende velden.", "Supplier follow-up voorbereiden met context uit eerdere communicatie.", "Shift handover en operations briefing genereren uit open tickets, routes en deadlines."],
    privacy: "Logistieke data kan commercieel gevoelig zijn. We scheiden klant-, zending- en documentstromen en kiezen lokaal/private routes waar dat nodig is.",
    faqs: [
      { q: "Hoe helpt AI bij transportplanning?", a: "AI kan uitzonderingen, deadlines en ontbrekende informatie signaleren zodat planners sneller de juiste acties zien." },
      { q: "Kan AI douanedocumenten verwerken?", a: "AI kan documenten samenvatten en velden controleren, maar finale compliance blijft bij bevoegde mensen." },
      { q: "Werkt dit met bestaande systemen?", a: "Meestal starten we naast bestaande mail-, document- en planningtools en koppelen pas wanneer de workflow bewezen is." },
      { q: "Is AI veilig voor klant- en zendingdata?", a: "Dat vereist proceskeuze. AIOW ontwerpt lokale, private of hybride verwerking per datastroom." },
      { q: "Wat levert de AI-systeemscan op?", a: "Een shortlist van processen met impact, haalbaarheid, risico's en een voorstel voor een eerste veilige pilot." },
    ],
  },
  "lokale-private-ai": {
    slug: "lokale-private-ai",
    type: "service",
    title: "Lokale en private AI voor bedrijven",
    h1: "Lokale en private AI voor bedrijven",
    description: "Lokale en private AI op private AI-infrastructuur: minder databeweging, meer controle en hybride modelrouting waar passend.",
    intro: "Niet elk AI-proces hoort standaard in de cloud. AIOW onderzoekt waar lokale of private AI zinvol is voor privacy, snelheid en controle.",
    intentAnswer: "Lokale en private AI betekent dat bepaalde modellen, geheugenlagen of documentverwerking op eigen of private infrastructuur draaien, terwijl cloudmodellen alleen worden gebruikt wanneer dat expliciet past bij beleid en taak.",
    keywords: ["lokale AI oplossing bedrijf", "private AI server bedrijf"],
    audiences: ["privacygevoelige MKB-teams", "technische bedrijven", "directie/IT", "documentintensieve organisaties"],
    useCases: ["Interne documentzoekmachine op geselecteerde bedrijfsinformatie.", "Lokale samenvatting van gevoelige notities of procedures.", "Modelrouter: lokaal voor basiswerk, cloud voor taken die extra kwaliteit vragen.", "Beheerde private AI-omgeving voor pilots."],
    privacy: "Lokale AI kan databeweging verminderen, maar lost niet automatisch alle privacy- en securityvragen op. We ontwerpen rechten, logging, bewaartermijnen en menselijke approval mee.",
    faqs: [
      { q: "Hoe werkt lokale/private AI-infrastructuur?", a: "Een lokaal model draait op de machine zelf en kan geselecteerde taken uitvoeren zonder standaard cloudverwerking." },
      { q: "Is lokale AI altijd beter dan cloud-AI?", a: "Nee. Lokaal geeft controle, cloud kan beter zijn voor kwaliteit of schaal. Vaak is hybride het verstandigst." },
      { q: "Kan AIOW private AI servers inrichten?", a: "Ja, als onderdeel van een systeemontwerp met duidelijke scope, beheer en veiligheidsafspraken." },
      { q: "Wat blijft menselijk goedgekeurd?", a: "Externe, publieke, destructieve of gevoelige acties blijven achter expliciete approval gates." },
      { q: "Is dit GDPR-proof?", a: "We ontwerpen GDPR-bewust, maar finale juridische beoordeling moet apart worden goedgekeurd." },
    ],
  },
  "ai-systeemscan": {
    slug: "ai-systeemscan",
    type: "service",
    title: "AI quick check en systeemscan voor uw bedrijf",
    h1: "AI quick check en systeemscan voor uw bedrijf",
    description: "Plan een gratis AI quick check en ontdek of een betaalde AI-systeemscan of Persoonlijke AI Starter past bij uw bedrijf.",
    intro: "Start laagdrempelig met een gratis quick check. Als er echte scope, data en risico's uitgewerkt moeten worden, volgt een betaalde AI-systeemscan of directe Starter-installatie.",
    intentAnswer: "De gratis quick check bepaalt eerst of AI zinvol is. Een betaalde AI-systeemscan werkt daarna proces, data, approvals, lokale/cloud route en eerste veilige pilot concreet uit.",
    keywords: ["AI systeemscan", "gratis AI scan bedrijf", "AI roadmap MKB", "AI automatisering scan"],
    audiences: ["MKB-directie", "operations managers", "logistieke teams", "founders en consultants"],
    useCases: ["Herhaalwerk inventariseren in mail, documenten, planning en administratie.", "Privacy- en datagrensen bepalen voordat AI wordt aangesloten.", "Een eerste pilot kiezen op basis van impact, haalbaarheid en risico.", "Roadmap maken van scan naar architectuur, build, training en beheer."],
    privacy: "De scan is bedoeld om risico's vroeg zichtbaar te maken. WhatsApp is nu de veilige contactroute; live formulieren, analytics en externe automatisering blijven uit tot hun bestemmingen gecontroleerd zijn.",
    faqs: [
      { q: "Wat krijg ik uit de gratis quick check?", a: "Een eerste inschatting van kans, urgentie en beste route: Persoonlijke AI Starter, betaalde AI-systeemscan of later opschalen." },
      { q: "Moet ik al weten welke AI-tool ik wil?", a: "Nee. De scan begint bij werk en risico, niet bij tools." },
      { q: "Hoe lang duurt een AI-systeemscan?", a: "Dat hangt af van scope, maar de eerste intake kan compact blijven en vooral prioriteiten scherp maken." },
      { q: "Wordt er al iets live gekoppeld?", a: "Nee. Het formulier blijft veilig uitgeschakeld; contact loopt via WhatsApp en externe acties vragen altijd expliciete goedkeuring." },
      { q: "Voor wie is de scan bedoeld?", a: "Voor Nederlandse MKB-bedrijven, logistieke teams, zakelijke dienstverleners en technische organisaties die praktisch met AI willen starten." },
    ],
  },

  "ai-governance-checklist": {
    slug: "ai-governance-checklist",
    type: "service",
    title: "AI governance checklist voor Nederlandse bedrijven",
    h1: "AI governance checklist voor Nederlandse bedrijven",
    description: "Praktische AI governance checklist voor MKB en B2B-teams: dataclassificatie, modelkeuze, logging, menselijke approvals, risico's en pilot-KPI's.",
    intro: "AI wordt pas bedrijfswaardig wanneer duidelijk is welke data gebruikt mag worden, welke modellen passen, wie mag goedkeuren en hoe fouten worden teruggedraaid. Deze checklist maakt governance concreet voordat een AI-pilot live gaat.",
    intentAnswer: "Een AI governance checklist helpt bedrijven AI veilig te starten door proces, dataklassen, modelroute, menselijke approvals, logging, bewaartermijnen, security, evaluaties en rollback-afspraken vooraf vast te leggen.",
    keywords: ["AI governance checklist", "AI beleid bedrijf", "AI dataclassificatie", "AI approvals", "AI risico MKB", "AI pilot governance"],
    audiences: ["MKB-directie", "operations en IT", "privacy- en complianceverantwoordelijken", "teams die AI-tools al gebruiken zonder beleid"],
    useCases: ["Bepalen welke bedrijfsdata lokaal, private of cloud verwerkt mag worden.", "Approval gates ontwerpen voor externe, financiële, juridische of klantgerichte output.", "Logging en evaluatiecriteria vastleggen voordat agents of workflows live gaan.", "Een AI-pilot beoordelen op impact, risico, adoptie en beheersbaarheid."],
    privacy: "Governance is geen los document maar een werklaag: rechten, datagrens, modelrouting, logging, bewaartermijnen, menselijke review en rollback horen in de AI-oplossing zelf. AIOW kiest best-route-first: lokaal/private AI waar dat controle bewijst, cloud waar dat aantoonbaar beter is.",
    faqs: [
      { q: "Wat hoort in een AI governance checklist?", a: "Minimaal: procesdoel, dataclassificatie, modelroute, toegangsrechten, logging, menselijke approvals, evaluatiecriteria, security-afspraken, bewaartermijnen en rollback." },
      { q: "Wanneer is lokale of private AI nodig?", a: "Wanneer data, beleid, latency, kosten of controle daar aantoonbaar voordeel van hebben. AIOW kiest niet standaard lokaal of cloud, maar de beste route per workflow." },
      { q: "Welke AI-acties moeten menselijk goedgekeurd blijven?", a: "Publieke, externe, financiële, juridische, destructieve of klantgevoelige acties blijven achter expliciete menselijke approval totdat risico en kwaliteit bewezen zijn." },
      { q: "Hoe voorkom je shadow AI in een bedrijf?", a: "Door één beheerde AI-werklaag te maken met duidelijke tools, datagrens, logging, training en escalatiepad in plaats van losse accounts en prompts." },
      { q: "Is deze checklist juridisch advies?", a: "Nee. Dit is een praktische implementatiechecklist. Juridische of formele AVG-beoordeling moet door bevoegde specialisten worden bevestigd." },
    ],
  },

  "sector/installatiebedrijven": {
    slug: "sector/installatiebedrijven",
    type: "service",
    title: "AI voor installatiebedrijven",
    h1: "AI voor installatiebedrijven",
    description: "AI-oplossingen voor installatiebedrijven: werkbonnen, planning, offertes, klantvragen, storingen en monteursinformatie met menselijke controle.",
    intro: "Installatiebedrijven hebben veel terugkerende communicatie, planning, documentatie en storingsinformatie. AIOW bouwt AI rond dat dagelijkse werk.",
    intentAnswer: "AI voor installatiebedrijven helpt met werkbonnen samenvatten, klantvragen prioriteren, offertes voorbereiden, monteursinformatie vindbaar maken en planning/storingen naar de juiste eigenaar routeren.",
    keywords: ["AI installatiebedrijven", "AI voor installateurs", "AI automatisering installatiebedrijf", "AI werkbonnen", "AI planning monteurs"],
    audiences: ["installatiebedrijven", "serviceplanning", "werkvoorbereiding", "monteurs en backoffice"],
    useCases: ["Werkbonnen en servicerapporten samenvatten.", "Klantvragen en storingen prioriteren op urgentie.", "Offertes voorbereiden met eerdere klanthistorie en productinformatie.", "Monteursinformatie en procedures vindbaar maken."],
    privacy: "Klant-, adres- en installatiegegevens worden per workflow geclassificeerd. Externe communicatie en aanpassingen blijven achter menselijke approval.",
    faqs: [
      { q: "Hoe kan AI een installatiebedrijf helpen?", a: "Met planning, klantvragen, werkbonnen, storingen, offertes en interne kennis voor monteurs en backoffice." },
      { q: "Kan AI werkbonnen automatisch verwerken?", a: "AI kan samenvatten en signaleren; definitieve verwerking of klantcommunicatie blijft gecontroleerd." },
      { q: "Werkt dit met bestaande planningssoftware?", a: "We starten vaak naast bestaande tools en koppelen pas wanneer de workflow bewezen veilig en nuttig is." },
      { q: "Is klantdata veilig?", a: "AIOW bepaalt vooraf welke data lokaal, private of cloud verwerkt mag worden en waar approval nodig is." },
    ],
  },
  "sector/finance-administratie": {
    slug: "sector/finance-administratie",
    type: "service",
    title: "AI voor finance en administratie",
    h1: "AI voor finance en administratie",
    description: "AI voor finance, administratie en backoffice: facturen, inbox, rapportages, afwijkingen, debiteuren en managementbriefings.",
    intro: "Finance- en administratieteams winnen vooral tijd wanneer AI informatie structureert, afwijkingen signaleert en conceptacties voorbereidt.",
    intentAnswer: "AI voor finance en administratie ondersteunt bij factuurtriage, documentcontrole, rapportagevoorbereiding, debiteurenopvolging, afwijkingssignalen en duidelijke menselijke goedkeuring.",
    keywords: ["AI finance administratie", "AI administratiekantoor", "AI factuurverwerking", "AI backoffice", "AI debiteurenbeheer"],
    audiences: ["finance teams", "administratiekantoren", "controllers", "backoffice"],
    useCases: ["Facturen en bijlagen samenvatten en controleren op ontbrekende velden.", "Debiteurenopvolging voorbereiden met context.", "Managementbriefing maken van open posten en risico's.", "Administratieve inbox triage met prioriteit en eigenaar."],
    privacy: "Financiële data blijft gevoelig. AIOW gebruikt dataclassificatie, logging en approval gates voordat AI aan documenten of systemen wordt gekoppeld.",
    faqs: [
      { q: "Kan AI facturen verwerken?", a: "AI kan helpen met lezen, controleren en samenvatten; finale boeking of betaling blijft menselijk/goedgekeurd." },
      { q: "Is AI veilig voor financiële data?", a: "Alleen met juiste datagrens, rechten, logging en modelkeuze. Dat ontwerpen we in de scan." },
      { q: "Wat is een goede eerste pilot?", a: "Inboxtriage, factuurcontrole of managementbriefing zijn vaak veilige eerste stappen." },
      { q: "Vervangt AI administrateurs?", a: "Nee, het ondersteunt voorbereiding, signalering en overzicht." },
    ],
  },
  "sector/legal-zakelijke-dienstverlening": {
    slug: "sector/legal-zakelijke-dienstverlening",
    type: "service",
    title: "AI voor legal en zakelijke dienstverlening",
    h1: "AI voor legal en zakelijke dienstverlening",
    description: "AI voor legal, consultants en zakelijke dienstverleners: dossiers, contracten, klantcommunicatie, kennisbanken en approvals.",
    intro: "Zakelijke dienstverleners werken met vertrouwelijke documenten, deadlines en klantcontext. AIOW bouwt AI-systemen die helpen zonder controle te verliezen.",
    intentAnswer: "AI voor legal en zakelijke dienstverlening helpt met dossiers samenvatten, contracten vergelijken, interne kennis zoeken, klantupdates voorbereiden en gevoelige output langs menselijke review routeren.",
    keywords: ["AI legal Nederland", "AI zakelijke dienstverlening", "AI contracten", "AI kennisbank consultants", "AI dossier samenvatten"],
    audiences: ["legal teams", "consultants", "accountants", "professionele dienstverleners"],
    useCases: ["Dossiers en klantcontext samenvatten.", "Contracten vergelijken op verschillen en risico's.", "Kennisbank maken voor procedures en templates.", "Klantupdates voorbereiden met verplichte review."],
    privacy: "Vertrouwelijke klantdocumenten vereisen strikte scope, lokale/private routes waar nodig en menselijke goedkeuring voor externe output.",
    faqs: [
      { q: "Kan AI juridische documenten beoordelen?", a: "AI kan samenvatten en verschillen signaleren; juridische beoordeling blijft bij bevoegde professionals." },
      { q: "Kan dit met vertrouwelijke dossiers?", a: "Alleen met een gekozen lokale/private/hybride route, rechten en duidelijke logging." },
      { q: "Wat levert dit op?", a: "Sneller overzicht, minder zoekwerk en betere voorbereiding voor mensen." },
      { q: "Hoe voorkomt AIOW hallucinaties?", a: "Door scope, bronverwijzingen, menselijke review en geen onbeheerde externe acties." },
    ],
  },
  "sector/bouw-vastgoed": {
    slug: "sector/bouw-vastgoed",
    type: "service",
    title: "AI voor bouw en vastgoed",
    h1: "AI voor bouw en vastgoed",
    description: "AI voor bouw, vastgoed en projectteams: offertes, planning, projectdocumenten, klantvragen, opleverpunten en kennisborging.",
    intro: "Bouw- en vastgoedteams hebben veel documentstromen, planning, leverancierscommunicatie en projectoverdracht. AIOW maakt die processen overzichtelijker met veilige AI.",
    intentAnswer: "AI voor bouw en vastgoed kan projectdocumenten samenvatten, opleverpunten structureren, offertes voorbereiden, klantvragen prioriteren en planningsoverzichten maken met duidelijke menselijke controle.",
    keywords: ["AI bouwbedrijf", "AI vastgoed", "AI projectdocumenten", "AI offertes bouw", "AI opleverpunten"],
    audiences: ["bouwbedrijven", "vastgoedbeheerders", "projectleiders", "werkvoorbereiding"],
    useCases: ["Projectdocumenten en mailwisselingen samenvatten.", "Opleverpunten structureren naar urgentie en eigenaar.", "Offertes en klantreacties voorbereiden.", "Dagelijkse projectbriefing met risico's en deadlines."],
    privacy: "Project-, klant- en leveranciersdata wordt per workflow afgebakend. AI bereidt voor; finale besluiten en communicatie blijven bij mensen.",
    faqs: [
      { q: "Waar helpt AI in bouwprojecten?", a: "Bij documentoverzicht, planning, overdracht, offertevoorbereiding en het signaleren van open punten." },
      { q: "Kan AI opleverpunten beheren?", a: "AI kan structureren en prioriteren; formele afhandeling blijft in bestaande systemen en bij verantwoordelijken." },
      { q: "Werkt dit naast bestaande software?", a: "Ja, eerst naast bestaande tools; integraties volgen pas na een veilige pilot." },
      { q: "Is dit geschikt voor kleine bouwbedrijven?", a: "Ja, vooral wanneer er veel mail, offertes en projectdocumenten zijn." },
    ],
  },


  "werkwijze-ai-implementatie": {
    slug: "werkwijze-ai-implementatie",
    type: "service",
    title: "Werkwijze AI-implementatie",
    h1: "AIOW werkwijze voor veilige AI-implementatie",
    description: "Hoe AIOW AI implementeert: AI-systeemscan, dataclassificatie, modelrouting, pilot, approvals, logging, training en beheer.",
    intro: "Bedrijven hebben geen behoefte aan losse AI-demo's, maar aan een beheersbare route van proces naar werkende AI. Deze pagina legt de AIOW-werkwijze uit.",
    intentAnswer: "AIOW implementeert AI via een vaste route: proces- en datascan, risico-indeling, modelkeuze, kleine pilot, logging, menselijke approval gates, teamtraining en beheerafspraken.",
    keywords: ["AI implementatie werkwijze", "AI implementatie stappen", "AI systeemscan", "AI pilot bedrijf", "AI governance implementatie"],
    audiences: ["directie", "MKB", "operations", "IT", "teams die AI veilig willen invoeren"],
    useCases: ["AI-kansen prioriteren zonder hype.", "Eerste pilot kiezen met laag risico en hoge waarde.", "Lokale/private/cloud modelroutes bepalen.", "AI-agents veilig in processen plaatsen."],
    privacy: "Privacy en governance zitten vanaf stap één in het proces: dataclassificatie, minimale toegang, logging, rechten en menselijke approvals.",
    faqs: [
      { q: "Hoe start AIOW een AI-implementatie?", a: "Met een AI-systeemscan van processen, data, risico's, quick wins en mogelijke eerste pilots." },
      { q: "Hoe lang duurt een eerste pilot?", a: "Dat hangt af van data en koppelingen, maar de insteek is klein starten en snel bewijs verzamelen." },
      { q: "Waarom niet meteen alles automatiseren?", a: "Omdat veilige AI stap voor stap moet groeien: eerst bewijzen, meten en governance vastzetten." },
      { q: "Wat levert de werkwijze op?", a: "Een beheersbare AI-werklaag in plaats van losse tools zonder eigenaarschap." },
    ],
  },
  "veiligheid-governance-ai": {
    slug: "veiligheid-governance-ai",
    type: "service",
    title: "AI veiligheid en governance",
    h1: "AI veiligheid, privacy en governance voor bedrijven",
    description: "AIOW ontwerpt veilige AI met dataclassificatie, modelrouting, logging, rechten, menselijke approvals en lokale/private AI waar nodig.",
    intro: "De grootste AI-risico's zitten niet in het model alleen, maar in data, rechten, onbeheerde acties en onduidelijke verantwoordelijkheid. AIOW maakt die grenzen expliciet.",
    intentAnswer: "Veilige AI-governance betekent dat een bedrijf vooraf bepaalt welke data AI mag gebruiken, welk model past, welke acties review nodig hebben, wie eigenaar is en hoe logging/beheer werkt.",
    keywords: ["AI governance", "AI veiligheid bedrijven", "AI privacy Nederland", "private AI governance", "AI dataclassificatie"],
    audiences: ["directie", "IT", "privacy officers", "operations", "MKB"],
    useCases: ["Dataclassificatie voor AI-workflows.", "Approval gates voor externe of gevoelige acties.", "Logging en rechten voor AI-agents.", "Modelrouting tussen lokaal, private en cloud."],
    privacy: "AIOW behandelt privacy als architectuurkeuze: minimale toegang, broncontrole, lokale/private routes waar nodig en geen onbeheerde publieke of gevoelige acties.",
    faqs: [
      { q: "Wat maakt AI veilig voor bedrijven?", a: "Duidelijke datagrens, beperkte rechten, logging, menselijke review en passende modelkeuze." },
      { q: "Wanneer is lokale/private AI nodig?", a: "Wanneer data gevoelig is, controle belangrijk is of beleid cloudgebruik beperkt." },
      { q: "Zijn AI-agents riskanter dan chatbots?", a: "Ja, omdat agents taken en tools kunnen gebruiken. Daarom zijn rechten en approvals cruciaal." },
      { q: "Kan AIOW AI-beleid technisch afdwingen?", a: "Ja, via modelrouting, workflowgrenzen, logging en approval gates." },
    ],
  },
  "sector/zorg": {
    slug: "sector/zorg",
    type: "service",
    title: "AI voor zorgorganisaties",
    h1: "AI voor zorgorganisaties",
    description: "Veilige AI voor zorgorganisaties: cliëntvragen, interne kennis, planning, rapportages, administratie en privacybewuste ondersteuning.",
    intro: "Zorgorganisaties hebben hoge werkdruk en gevoelige informatie. AIOW bouwt AI die administratieve druk verlaagt zonder medische of privacygevoelige grenzen te overschrijden.",
    intentAnswer: "AI voor zorgorganisaties helpt vooral bij administratieve ondersteuning, kennisvindbaarheid, planningsoverzicht, cliëntcommunicatie voorbereiden en rapportages samenvatten met menselijke controle.",
    keywords: ["AI zorg Nederland", "AI zorgorganisatie", "AI administratie zorg", "AI cliëntcommunicatie", "private AI zorg"],
    audiences: ["zorgorganisaties", "zorgadministratie", "planning", "management en backoffice"],
    useCases: ["Interne procedures en protocollen vindbaar maken.", "Administratieve rapportages samenvatten.", "Planning en overdracht voorbereiden.", "Cliëntvragen categoriseren zonder automatische medische beoordeling."],
    privacy: "Zorgdata vraagt strikte dataclassificatie, minimale gegevensverwerking, logging en menselijke goedkeuring. AIOW automatiseert geen medische beslissingen.",
    faqs: [
      { q: "Kan AI veilig in de zorg?", a: "Ja, maar alleen met duidelijke datagrens, minimale verwerking, logging en menselijke review." },
      { q: "Doet AIOW medische diagnose?", a: "Nee. AIOW richt zich op ondersteunende workflows, administratie, kennis en voorbereiding." },
      { q: "Wat is een veilige eerste pilot?", a: "Een interne kennisbank of administratieve samenvatting zonder directe cliëntbeslissingen." },
      { q: "Kan dit lokaal of private draaien?", a: "Ja, lokale/private of hybride AI is mogelijk afhankelijk van data en eisen." },
    ],
  },
  "sector/marketing-agencies": {
    slug: "sector/marketing-agencies",
    type: "service",
    title: "AI voor marketingbureaus en agencies",
    h1: "AI voor marketingbureaus en agencies",
    description: "AI voor marketingbureaus: briefing, content, SEO/GEO, klantupdates, rapportages, planning en agency operations met reviewflows.",
    intro: "Agencies kunnen AI inzetten voor sneller denkwerk, betere rapportages en schaalbare klantcommunicatie, zolang kwaliteit en merkcontrole bewaakt blijven.",
    intentAnswer: "AI voor marketingbureaus helpt met briefinganalyse, contentvoorstellen, SEO/GEO research, rapportages, klantupdates, planning en interne kennis, met menselijke review voor externe output.",
    keywords: ["AI marketingbureau", "AI agency Nederland", "AI content bureau", "AI SEO GEO", "AI klantupdates"],
    audiences: ["marketingbureaus", "creative agencies", "SEO bureaus", "contentteams"],
    useCases: ["Briefings samenvatten en omzetten naar taken.", "SEO/GEO kansen structureren.", "Klantupdates en rapportages voorbereiden.", "Merk- en tone-of-voice kennisbanken bouwen."],
    privacy: "Klantdata, strategie en campagnegegevens blijven binnen afgesproken modelroutes. Publicatie en klantcommunicatie blijven achter approval.",
    faqs: [
      { q: "Kan AI agency-output verbeteren?", a: "Ja, vooral door research, structuur, varianten en rapportages te versnellen." },
      { q: "Hoe voorkom je generieke AI-content?", a: "Door merkcontext, bronnen, menselijke redactie en kwaliteitschecks te verplichten." },
      { q: "Kan AIOW SEO/GEO workflows bouwen?", a: "Ja, inclusief research, contentclusters, llms.txt, schema en rapportageflows." },
      { q: "Blijft klantcommunicatie gecontroleerd?", a: "Ja, externe output blijft met menselijke goedkeuring." },
    ],
  },
  "sector/klantcontact-support": {
    slug: "sector/klantcontact-support",
    type: "service",
    title: "AI voor klantcontact en support",
    h1: "AI voor klantcontact en support",
    description: "AI voor klantcontact: inboxtriage, ticket-samenvattingen, kennisbank, conceptantwoorden, escalatie en kwaliteitscontrole.",
    intro: "Supportteams verliezen veel tijd aan herhaling, zoeken en overdracht. AIOW bouwt AI die agents helpt zonder klanten onbeheerd te laten antwoorden.",
    intentAnswer: "AI voor klantcontact ondersteunt met tickettriage, samenvattingen, kennisbank-antwoorden, conceptreacties, escalatieherkenning en kwaliteitscontrole met menselijke approval.",
    keywords: ["AI klantcontact", "AI support", "AI ticket triage", "AI klantenservice", "AI chatbot vs agent"],
    audiences: ["supportteams", "klantenservice", "operations", "CX managers"],
    useCases: ["Tickets samenvatten en prioriteren.", "Conceptantwoorden maken met bronverwijzing.", "Escalaties en sentiment signaleren.", "Supportkennisbank actueel en vindbaar maken."],
    privacy: "Klantgegevens en externe antwoorden worden via dataclassificatie en approval gates behandeld. AI adviseert; mensen blijven verantwoordelijk.",
    faqs: [
      { q: "Vervangt AI supportmedewerkers?", a: "Nee, het ondersteunt triage, samenvatting en conceptantwoorden." },
      { q: "Kan AI automatisch klanten antwoorden?", a: "Alleen wanneer risico laag en beleid duidelijk is; meestal adviseren we review voor externe antwoorden." },
      { q: "Werkt dit met bestaande ticketsystemen?", a: "Ja, eerst naast de workflow en later eventueel gekoppeld." },
      { q: "Wat is de snelste winst?", a: "Tickettriage en samenvattingen leveren vaak snel tijdwinst op." },
    ],
  },
  "sector/hr-recruitment": {
    slug: "sector/hr-recruitment",
    type: "service",
    title: "AI voor HR en recruitment",
    h1: "AI voor HR en recruitment",
    description: "AI voor HR en recruitment: vacatureteksten, kandidaatcommunicatie, onboarding, beleid, documentatie en interne kennis met fairness checks.",
    intro: "HR werkt met gevoelige persoonsgegevens en belangrijke menselijke beslissingen. AIOW bouwt AI die voorbereidt en structureert, niet blind beslist.",
    intentAnswer: "AI voor HR en recruitment helpt met vacatureteksten, kandidaatcommunicatie voorbereiden, onboardingmateriaal, beleidsvragen, documentatie en planning, met menselijke beoordeling en biasbewaking.",
    keywords: ["AI HR", "AI recruitment Nederland", "AI vacatureteksten", "AI onboarding", "AI personeelsbeleid"],
    audiences: ["HR teams", "recruiters", "people operations", "MKB directie"],
    useCases: ["Vacatureteksten en intakevragen voorbereiden.", "Kandidaatcommunicatie structureren.", "Onboarding en beleid vindbaar maken.", "HR-inbox triage met gevoelige datagrens."],
    privacy: "Persoonsgegevens en selectieprocessen vragen fairness, dataminimalisatie en menselijke besluitvorming. AIOW automatiseert geen onbeheerde selectie." ,
    faqs: [
      { q: "Kan AI sollicitanten selecteren?", a: "AIOW adviseert geen onbeheerde selectie; AI kan voorbereiden, samenvatten en structureren." },
      { q: "Is HR-data geschikt voor AI?", a: "Alleen met strikte datagrens, rechten en logging." },
      { q: "Waar levert AI HR snel waarde?", a: "Vacatureteksten, onboarding, beleidsvragen en inboxtriage." },
      { q: "Hoe voorkom je bias?", a: "Door menselijke review, scopebeperking en duidelijke criteria." },
    ],
  },
  "sector/ecommerce-retail": {
    slug: "sector/ecommerce-retail",
    type: "service",
    title: "AI voor e-commerce en retail",
    h1: "AI voor e-commerce en retail",
    description: "AI voor e-commerce en retail: productcontent, klantenservice, voorraadvragen, retouren, SEO/GEO en operationele dashboards.",
    intro: "E-commerce en retail draaien op snelheid, productinformatie en klantvragen. AIOW bouwt AI die content en support versnelt met controle op merk en data.",
    intentAnswer: "AI voor e-commerce helpt met productcontent, klantenservice, retourvragen, SEO/GEO teksten, interne kennis, voorraadvragen en managementoverzichten met reviewflows.",
    keywords: ["AI ecommerce", "AI retail Nederland", "AI productcontent", "AI klantenservice webshop", "AI SEO webshop"],
    audiences: ["webshops", "retailers", "e-commerce teams", "customer service"],
    useCases: ["Productteksten en FAQ's voorbereiden.", "Klantvragen en retouren categoriseren.", "SEO/GEO productclusters maken.", "Dagelijkse operatiebriefings genereren."],
    privacy: "Klant- en orderdata wordt per use case afgebakend. Publicatie en klantcommunicatie blijven onder menselijke controle.",
    faqs: [
      { q: "Kan AI productteksten maken?", a: "Ja, met merkregels, productdata en menselijke review." },
      { q: "Kan AI klantenservice versnellen?", a: "Ja, vooral met samenvattingen, conceptantwoorden en kennisbankantwoorden." },
      { q: "Werkt dit met webshopsystemen?", a: "We starten naast bestaande systemen en koppelen pas na een veilige pilot." },
      { q: "Helpt dit SEO?", a: "Ja, door betere structuur, FAQ's, productclusters en GEO-vriendelijke antwoorden." },
    ],
  },
  "vergelijking/private-ai-vs-cloud-ai": {
    slug: "vergelijking/private-ai-vs-cloud-ai",
    type: "service",
    title: "Private AI vs cloud AI voor bedrijven",
    h1: "Private AI vs cloud AI voor bedrijven",
    description: "Private AI of cloud AI? Wanneer kiest een bedrijf voor lokale/private modellen, cloudmodellen of hybride AI-routing.",
    intro: "De beste AI-keuze is zelden zwart-wit. AIOW bepaalt per taak en dataklasse of private, lokale, cloud of hybride AI het veiligst en nuttigst is.",
    intentAnswer: "Private AI past bij gevoelige data, controle, governance of beperkte databeweging. Cloud AI past vaak bij hogere modelkwaliteit en complexe taken. Hybride routing combineert beide per workflow.",
    keywords: ["private AI vs cloud AI", "private AI bedrijf", "cloud AI bedrijf", "hybride AI", "lokale AI Nederland"],
    audiences: ["directie", "IT", "privacygevoelige bedrijven", "MKB"],
    useCases: ["Dataklassen bepalen.", "Modelrouter per taak ontwerpen.", "Private AI voor gevoelige documenten.", "Cloud AI voor niet-gevoelige complexe taken."],
    privacy: "AIOW koppelt modelkeuze aan dataclassificatie, logging, rechten en menselijke approvals.",
    faqs: [
      { q: "Is private AI altijd beter?", a: "Nee, private AI geeft meer controle maar kan minder krachtig zijn dan top cloudmodellen." },
      { q: "Wanneer kies je cloud AI?", a: "Wanneer data dat toestaat en hogere modelkwaliteit belangrijk is." },
      { q: "Wat is hybride AI?", a: "Een route waarbij per taak het juiste modeltype wordt gekozen." },
      { q: "Hoe beslist AIOW dit?", a: "Via een scan van processen, data, risico's en gewenste output." },
    ],
  },
  "vergelijking/ai-agent-vs-chatbot": {
    slug: "vergelijking/ai-agent-vs-chatbot",
    type: "service",
    title: "AI-agent vs chatbot",
    h1: "AI-agent vs chatbot: wat is het verschil?",
    description: "Het verschil tussen een AI-agent en chatbot voor bedrijven: taken, tools, approvals, risico's en veilige implementatie.",
    intro: "Veel bedrijven noemen alles een chatbot. Een AI-agent is iets anders: die kan taken voorbereiden, tools gebruiken en workflows volgen, mits veilig begrensd.",
    intentAnswer: "Een chatbot voert vooral gesprekken. Een AI-agent kan binnen een workflow informatie ophalen, taken voorbereiden, systemen aanroepen en vervolgstappen voorstellen, met menselijke approvals voor risicoacties.",
    keywords: ["AI agent vs chatbot", "AI agents bedrijven", "AI chatbot bedrijf", "AI agent implementatie", "AI workflows"],
    audiences: ["MKB", "supportteams", "operations", "IT/directie"],
    useCases: ["Supportagent met kennisbank en ticketcontext.", "Backoffice-agent voor documenten en taakvoorbereiding.", "Sales-agent die leads samenvat en opvolging klaarzet.", "Operations-agent met dagelijkse briefing."],
    privacy: "Agents hebben meer risico dan chatbots. Daarom ontwerpt AIOW scope, rechten, logging en approval gates expliciet.",
    faqs: [
      { q: "Wat is het verschil tussen een AI-agent en chatbot?", a: "Een chatbot praat; een agent kan taken binnen een workflow voorbereiden en tools gebruiken." },
      { q: "Zijn AI-agents veilig?", a: "Alleen met beperkte rechten, logging, datagrens en menselijke goedkeuring voor gevoelige acties." },
      { q: "Wanneer heb je een agent nodig?", a: "Wanneer AI niet alleen moet antwoorden maar ook werk moet voorbereiden of routeren." },
      { q: "Kan AIOW agents bouwen?", a: "Ja, met focus op bedrijfsprocessen, veiligheid en beheer." },
    ],
  },
  "vergelijking/ai-installateur-vs-ai-consultant": {
    slug: "vergelijking/ai-installateur-vs-ai-consultant",
    type: "service",
    title: "AI-installateur vs AI-consultant",
    h1: "AI-installateur vs AI-consultant: wat heeft uw bedrijf nodig?",
    description: "Het verschil tussen een AI-installateur en AI-consultant: advies, implementatie, agents, lokale/private AI, governance en beheer.",
    intro: "Veel bedrijven krijgen AI-advies, maar hebben uiteindelijk een werkend systeem nodig. Deze pagina legt uit wanneer advies genoeg is en wanneer installatie nodig wordt.",
    intentAnswer: "Een AI-consultant adviseert vooral over kansen, strategie en training. Een AI-installateur bouwt en installeert een werkend AI-systeem met koppelingen, data-afspraken, modelroutes, agents, logging en menselijke approvals.",
    keywords: ["AI installateur vs AI consultant", "AI consultant Nederland", "AI implementatiepartner", "AI advies bedrijf", "AI installeren bedrijf"],
    audiences: ["directie", "MKB", "operations", "teams na eerste AI-advies"],
    useCases: ["Na een AI-workshop een echte pilot bouwen.", "Losse ChatGPT-initiatieven onder beleid brengen.", "Agents en lokale/private AI installeren.", "Governance, logging en approvals inrichten."],
    privacy: "Advies zonder implementatie lost datarisico niet op. AIOW vertaalt beleid naar technische routes en approval gates.",
    faqs: [
      { q: "Wat is het verschil tussen AI-advies en AI-installatie?", a: "Advies vertelt wat mogelijk is; installatie maakt het werkend, veilig en beheerbaar in processen." },
      { q: "Wanneer heb je een AI-installateur nodig?", a: "Wanneer AI daadwerkelijk gekoppeld wordt aan werk, data, documenten, agents of bedrijfsprocessen." },
      { q: "Doet AIOW ook strategie?", a: "Ja, maar altijd gekoppeld aan een praktische scan, pilot en veilige implementatie." },
      { q: "Kan een consultant genoeg zijn?", a: "Voor bewustwording of training soms wel; voor operationele AI is implementatie nodig." },
    ],
  },
  "vergelijking/lokale-ai-vs-chatgpt": {
    slug: "vergelijking/lokale-ai-vs-chatgpt",
    type: "service",
    title: "Lokale AI vs ChatGPT voor bedrijven",
    h1: "Lokale AI vs ChatGPT voor bedrijven",
    description: "Wanneer kiest een bedrijf lokale/private AI en wanneer ChatGPT, Claude of cloudmodellen? AIOW ontwerpt veilige hybride modelrouting.",
    intro: "Lokale AI en ChatGPT zijn geen vijanden. De beste bedrijfsoplossing gebruikt vaak een hybride route: lokaal waar nodig, cloud waar het mag.",
    intentAnswer: "Lokale AI is nuttig wanneer data gevoelig is, verwerking dichtbij moet blijven of controle belangrijker is dan maximale modelkwaliteit. ChatGPT/Claude/cloudmodellen zijn vaak sterker voor complexe taal- en redeneertaken, mits beleid dat toestaat.",
    keywords: ["lokale AI vs ChatGPT", "private AI vs ChatGPT", "lokale AI bedrijf", "ChatGPT bedrijf veilig", "hybride AI routing"],
    audiences: ["privacygevoelige bedrijven", "IT/directie", "MKB met ChatGPT-gebruik", "technische teams"],
    useCases: ["Lokaal samenvatten van gevoelige documenten.", "Cloudmodellen gebruiken voor niet-gevoelige complexe taken.", "Modelrouter ontwerpen per dataklasse en taak.", "Goedkeuring eisen voordat output extern gaat."],
    privacy: "De keuze is per proces. AIOW bepaalt datagrens, modelroute, logging en approval voordat lokale of cloud-AI wordt aangesloten.",
    faqs: [
      { q: "Is lokale AI veiliger dan ChatGPT?", a: "Niet automatisch. Lokale AI vermindert databeweging, maar vereist nog steeds rechten, beheer, logging en scope." },
      { q: "Is ChatGPT geschikt voor bedrijven?", a: "Ja, mits gebruik past binnen beleid, dataklasse en menselijke controle." },
      { q: "Wat is hybride AI-routing?", a: "Per taak kiezen of lokaal, private of cloud-AI gebruikt wordt." },
      { q: "Wat adviseert AIOW?", a: "Begin bij proces en data, niet bij model. Daarna kiezen we de veiligste route." },
    ],
  },
};

export const regionPages: Record<string, SeoPageData> = {
  "haarlem": {
    slug: "regio/haarlem",
    type: "region",
    title: "AI-integratie voor bedrijven in Haarlem",
    h1: "AI-integratie voor bedrijven in Haarlem",
    description: "AI-integratie en AI-automatisering voor bedrijven in Haarlem: MKB, zakelijke dienstverlening, zorg, bouw en creatieve bedrijven.",
    intro: "AIOW helpt bedrijven in Haarlem AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Haarlem helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Haarlem", "AI automatisering Haarlem", "AI bedrijf Haarlem", "AI oplossingen Haarlem"],
    audiences: ["MKB", "zakelijke dienstverlening", "zorg en welzijn", "creatieve bedrijven"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Haarlem?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Haarlem op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },
  "leiden": {
    slug: "regio/leiden",
    type: "region",
    title: "AI-integratie voor bedrijven in Leiden",
    h1: "AI-integratie voor bedrijven in Leiden",
    description: "AI-integratie en AI-automatisering voor bedrijven in Leiden: kennisorganisaties, life sciences, zorg, onderwijs en zakelijke dienstverlening.",
    intro: "AIOW helpt bedrijven in Leiden AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Leiden helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Leiden", "AI automatisering Leiden", "AI bedrijf Leiden", "AI oplossingen Leiden"],
    audiences: ["life sciences", "zorg", "onderwijs", "kennisorganisaties"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Leiden?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Leiden op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },
  "amersfoort": {
    slug: "regio/amersfoort",
    type: "region",
    title: "AI-integratie voor bedrijven in Amersfoort",
    h1: "AI-integratie voor bedrijven in Amersfoort",
    description: "AI-integratie en AI-automatisering voor bedrijven in Amersfoort: MKB, zakelijke dienstverlening, bouw, installatie en backoffice.",
    intro: "AIOW helpt bedrijven in Amersfoort AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Amersfoort helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Amersfoort", "AI automatisering Amersfoort", "AI bedrijf Amersfoort", "AI oplossingen Amersfoort"],
    audiences: ["MKB", "bouw en installatie", "backoffice", "dienstverleners"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Amersfoort?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Amersfoort op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },
  "zwolle": {
    slug: "regio/zwolle",
    type: "region",
    title: "AI-integratie voor bedrijven in Zwolle",
    h1: "AI-integratie voor bedrijven in Zwolle",
    description: "AI-integratie en AI-automatisering voor bedrijven in Zwolle: regionale MKB-bedrijven, logistiek, zorg, onderwijs en administratie.",
    intro: "AIOW helpt bedrijven in Zwolle AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Zwolle helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Zwolle", "AI automatisering Zwolle", "AI bedrijf Zwolle", "AI oplossingen Zwolle"],
    audiences: ["MKB", "logistiek", "zorg", "administratie"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Zwolle?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Zwolle op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },
  "nijmegen": {
    slug: "regio/nijmegen",
    type: "region",
    title: "AI-integratie voor bedrijven in Nijmegen",
    h1: "AI-integratie voor bedrijven in Nijmegen",
    description: "AI-integratie en AI-automatisering voor bedrijven in Nijmegen: zorg, onderwijs, kenniswerk, MKB en zakelijke dienstverlening.",
    intro: "AIOW helpt bedrijven in Nijmegen AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Nijmegen helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Nijmegen", "AI automatisering Nijmegen", "AI bedrijf Nijmegen", "AI oplossingen Nijmegen"],
    audiences: ["zorg", "onderwijs", "MKB", "kenniswerk"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Nijmegen?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Nijmegen op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },
  "tilburg": {
    slug: "regio/tilburg",
    type: "region",
    title: "AI-integratie voor bedrijven in Tilburg",
    h1: "AI-integratie voor bedrijven in Tilburg",
    description: "AI-integratie en AI-automatisering voor bedrijven in Tilburg: logistiek, productie, e-commerce, MKB en klantcontact.",
    intro: "AIOW helpt bedrijven in Tilburg AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Tilburg helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Tilburg", "AI automatisering Tilburg", "AI bedrijf Tilburg", "AI oplossingen Tilburg"],
    audiences: ["logistiek", "productie", "e-commerce", "klantcontact"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Tilburg?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Tilburg op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },
  "den-bosch": {
    slug: "regio/den-bosch",
    type: "region",
    title: "AI-integratie voor bedrijven in Den Bosch",
    h1: "AI-integratie voor bedrijven in Den Bosch",
    description: "AI-integratie en AI-automatisering voor bedrijven in Den Bosch: MKB, bouw, installatie, finance, zakelijke dienstverlening en overheidstoeleveranciers.",
    intro: "AIOW helpt bedrijven in Den Bosch AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Den Bosch helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Den Bosch", "AI automatisering Den Bosch", "AI bedrijf Den Bosch", "AI oplossingen Den Bosch"],
    audiences: ["MKB", "bouw en installatie", "finance", "zakelijke dienstverlening"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Den Bosch?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Den Bosch op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },
  "maastricht": {
    slug: "regio/maastricht",
    type: "region",
    title: "AI-integratie voor bedrijven in Maastricht",
    h1: "AI-integratie voor bedrijven in Maastricht",
    description: "AI-integratie en AI-automatisering voor bedrijven in Maastricht: hospitality, zorg, onderwijs, internationale dienstverlening en MKB.",
    intro: "AIOW helpt bedrijven in Maastricht AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Maastricht helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Maastricht", "AI automatisering Maastricht", "AI bedrijf Maastricht", "AI oplossingen Maastricht"],
    audiences: ["hospitality", "zorg", "onderwijs", "MKB"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Maastricht?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Maastricht op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },
  "enschede": {
    slug: "regio/enschede",
    type: "region",
    title: "AI-integratie voor bedrijven in Enschede",
    h1: "AI-integratie voor bedrijven in Enschede",
    description: "AI-integratie en AI-automatisering voor bedrijven in Enschede: techniek, maakindustrie, onderwijs, startups en MKB.",
    intro: "AIOW helpt bedrijven in Enschede AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Enschede helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Enschede", "AI automatisering Enschede", "AI bedrijf Enschede", "AI oplossingen Enschede"],
    audiences: ["techniek", "maakindustrie", "onderwijs", "startups"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Enschede?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Enschede op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },
  "almere": {
    slug: "regio/almere",
    type: "region",
    title: "AI-integratie voor bedrijven in Almere",
    h1: "AI-integratie voor bedrijven in Almere",
    description: "AI-integratie en AI-automatisering voor bedrijven in Almere: groeiend MKB, e-commerce, klantcontact, bouw en backoffice.",
    intro: "AIOW helpt bedrijven in Almere AI praktisch en veilig inzetten rond documenten, klantvragen, planning, administratie en interne kennis.",
    intentAnswer: "AI-integratie in Almere helpt bedrijven terugkerend kenniswerk structureren met AI-agents, lokale/private AI waar nodig, modelrouting en menselijke approvals.",
    keywords: ["AI integratie Almere", "AI automatisering Almere", "AI bedrijf Almere", "AI oplossingen Almere"],
    audiences: ["MKB", "e-commerce", "klantcontact", "bouw"],
    useCases: ["Inbox en klantvragen prioriteren.", "Documenten samenvatten en doorzoekbaar maken.", "Offertes, planning en overdracht voorbereiden.", "Interne kennisbank en dagelijkse briefings opzetten."],
    privacy: "AIOW start met dataclassificatie en bepaalt per workflow of lokale, private, cloud of hybride AI veilig is. Externe en gevoelige acties blijven achter menselijke goedkeuring.",
    faqs: [
      { q: "Is AIOW beschikbaar voor bedrijven in Almere?", a: "Ja, AIOW werkt NL-first en ondersteunt bedrijven in Almere op afstand en waar nodig op locatie." },
      { q: "Welke AI-pilot past vaak als eerste?", a: "Inboxtriage, document-samenvatting, interne kennisbank of planningsoverzicht zijn meestal veilige eerste pilots." },
      { q: "Kan dit met bestaande software?", a: "Ja, AIOW begint vaak naast bestaande tools en koppelt pas na bewijs en veiligheidsafspraken." },
      { q: "Hoe blijft AI beheersbaar?", a: "Door scope, logging, rechten, modelrouting en menselijke approval gates." },
    ],
  },

  "den-haag": {
    slug: "regio/den-haag",
    type: "region",
    title: "AI-integratie voor bedrijven in Den Haag",
    h1: "AI-integratie voor bedrijven in Den Haag",
    description: "AI-integratie voor Haagse bedrijven, zakelijke dienstverleners, overheidstoeleveranciers, legal, finance en kennisorganisaties.",
    intro: "Den Haag heeft veel kenniswerk, documentstromen, compliance en publieke context. AIOW bouwt AI-systemen met beleid, privacy en menselijke review.",
    intentAnswer: "AI-integratie in Den Haag helpt bedrijven met documentanalyse, dossieroverzicht, klantcommunicatie, compliancevoorbereiding en interne kennis, zonder gevoelige acties onbeheerd te automatiseren.",
    keywords: ["AI integratie Den Haag", "AI automatisering Den Haag", "AI bedrijf Den Haag"],
    audiences: ["legal en compliance", "zakelijke dienstverleners", "overheidstoeleveranciers", "kennisorganisaties"],
    useCases: ["Dossiers samenvatten.", "Compliance-signalen voorbereiden.", "Klantcommunicatie klaarzetten met review.", "Interne kennisbank bouwen."],
    privacy: "Voor Haagse kennis- en complianceprocessen ontwerpen we strikte datagrens, logging en approval gates.",
    faqs: [
      { q: "Welke Haagse bedrijven passen bij AIOW?", a: "Teams met veel documenten, klantcontext, compliance of interne kennis." },
      { q: "Kan AI met gevoelige dossiers werken?", a: "Alleen met juiste lokale/private/hybride route en menselijke review." },
      { q: "Wat is een veilige eerste pilot?", a: "Dossier- of inboxtriage met beperkte data en duidelijke eigenaar." },
      { q: "Is dit ook voor overheid?", a: "AIOW richt zich primair op bedrijven; publieke of gereguleerde context vraagt aparte beoordeling." },
    ],
  },
  breda: {
    slug: "regio/breda",
    type: "region",
    title: "AI-automatisering voor bedrijven in Breda",
    h1: "AI-automatisering voor bedrijven in Breda",
    description: "AI-automatisering voor Bredase MKB-bedrijven, logistiek, bouw, zakelijke dienstverlening, sales en backoffice.",
    intro: "Bredase bedrijven kunnen AI praktisch inzetten voor klantcontact, offertes, planning, documenten en teamoverdracht.",
    intentAnswer: "AI-automatisering in Breda helpt MKB-teams om terugkerend werk rond mail, offertes, planning en administratie sneller en veiliger voor te bereiden.",
    keywords: ["AI automatisering Breda", "AI integratie Breda", "AI oplossingen Breda"],
    audiences: ["MKB", "logistiek", "bouw en installatie", "sales/backoffice"],
    useCases: ["Offertes voorbereiden.", "Klantvragen prioriteren.", "Planning en overdracht samenvatten.", "Documenten doorzoekbaar maken."],
    privacy: "We starten met één proces en bepalen per datastroom lokale/private/cloud verwerking.",
    faqs: [
      { q: "Waar start AI in een Bredaas MKB-bedrijf?", a: "Meestal bij inbox, offertes, planning of interne kennis." },
      { q: "Moeten systemen vervangen worden?", a: "Nee, eerst veilig naast bestaande tools." },
      { q: "Kan dit met WhatsApp of mail?", a: "Voorbereiding kan; externe verzending blijft goedgekeurd." },
      { q: "Wat is de eerste stap?", a: "Een AI-systeemscan." },
    ],
  },
  groningen: {
    slug: "regio/groningen",
    type: "region",
    title: "AI-oplossingen voor bedrijven in Groningen",
    h1: "AI-oplossingen voor bedrijven in Groningen",
    description: "AI-oplossingen voor Groningse bedrijven: MKB, energie, zakelijke dienstverlening, support, administratie en operations.",
    intro: "AIOW helpt Groningse bedrijven AI praktisch inzetten rond werkprocessen, documenten, klantvragen en interne kennis.",
    intentAnswer: "AI-oplossingen in Groningen zijn vooral nuttig voor herhaalwerk in support, administratie, planning, interne kennis en documentstromen.",
    keywords: ["AI oplossingen Groningen", "AI integratie Groningen", "AI automatisering Groningen"],
    audiences: ["MKB", "energie en techniek", "supportteams", "administratie"],
    useCases: ["Supportvragen samenvatten.", "Interne kennisbank bouwen.", "Planningsoverzicht genereren.", "Documenten vergelijken."],
    privacy: "AIOW bepaalt per proces wat lokaal/private/cloud kan en waar review verplicht is.",
    faqs: [
      { q: "Is AIOW actief in Groningen?", a: "AIOW werkt NL-first en kan Groningse bedrijven ondersteunen op afstand en waar nodig op locatie." },
      { q: "Welke processen passen?", a: "Support, administratie, documenten en planning." },
      { q: "Is lokale AI mogelijk?", a: "Ja, als data en workload dat rechtvaardigen." },
      { q: "Hoe start je?", a: "Met een AI-systeemscan." },
    ],
  },
  arnhem: {
    slug: "regio/arnhem",
    type: "region",
    title: "AI-integratie voor bedrijven in Arnhem",
    h1: "AI-integratie voor bedrijven in Arnhem",
    description: "AI-integratie voor Arnhemse bedrijven: MKB, zorgtoeleveranciers, zakelijke dienstverlening, techniek en backoffice.",
    intro: "AIOW bouwt veilige AI-werklagen voor Arnhemse bedrijven die meer grip willen op mail, documenten, planning en klantopvolging.",
    intentAnswer: "AI-integratie in Arnhem helpt bedrijfsprocessen structureren met agents, lokale/private AI waar nodig en menselijke approvals voor gevoelige acties.",
    keywords: ["AI integratie Arnhem", "AI automatisering Arnhem", "AI bedrijf Arnhem"],
    audiences: ["MKB", "techniek", "zakelijke dienstverlening", "backoffice"],
    useCases: ["Klantopvolging voorbereiden.", "Documenten samenvatten.", "Interne procedures vindbaar maken.", "Dagelijkse briefing genereren."],
    privacy: "De datagrens wordt per workflow ontworpen voordat AI wordt aangesloten.",
    faqs: [
      { q: "Voor welke Arnhemse bedrijven is dit?", a: "Voor teams met veel repetitief kennis-, document- of communicatiewerk." },
      { q: "Kan AI lokale data gebruiken?", a: "Ja, met lokale/private of hybride route waar passend." },
      { q: "Wat blijft menselijk?", a: "Externe, publieke, gevoelige of destructieve acties." },
      { q: "Hoe snel starten?", a: "Met een compacte AI-systeemscan." },
    ],
  },
  amsterdam: {
    slug: "regio/amsterdam",
    type: "region",
    title: "AI-integratie voor bedrijven in Amsterdam",
    h1: "AI-integratie voor bedrijven in Amsterdam",
    description: "AI-integratie voor Amsterdamse agencies, consultants, finance/legal/admin teams, founders en professionele dienstverleners.",
    intro: "AIOW helpt Amsterdamse bedrijven AI-systemen bouwen rond kenniswerk, klantopvolging, documentstromen en snelle teams.",
    intentAnswer: "AI-integratie in Amsterdam is vooral waardevol voor professionele diensten, agencies, finance/legal/admin teams en founders die veel kennis, communicatie en planning moeten coördineren zonder grip te verliezen.",
    keywords: ["AI integratie Amsterdam", "AI automatisering Amsterdam", "AI systeem bedrijf Amsterdam"],
    audiences: ["agencies", "consultants", "finance en legal", "founders en Zuidas-teams"],
    useCases: ["Client briefings en projectupdates samenvatten.", "Kennisbank voor proposals, contracten en interne werkwijzen.", "Sales/admin follow-up klaarzetten met menselijke review.", "Founder dashboard met acties, risico's en prioriteiten."],
    privacy: "Voor professionele diensten scheiden we klantcontext, vertrouwelijke documenten en publieke output met duidelijke approval gates.",
    faqs: [
      { q: "Voor welke Amsterdamse bedrijven past AIOW?", a: "Vooral kennisintensieve teams zoals agencies, consultants, zakelijke dienstverleners en founders." },
      { q: "Kan AI klantcommunicatie voorbereiden?", a: "Ja, concepten en samenvattingen kunnen worden voorbereid; verzending blijft goedgekeurd door mensen." },
      { q: "Kan AIOW met vertrouwelijke documenten werken?", a: "Alleen met een gekozen lokale/private/hybride route en duidelijke toegangsregels." },
      { q: "Wat is een goede eerste pilot?", a: "Inbox, projectbriefings of interne kenniszoekmachine zijn vaak veilige startpunten." },
    ],
  },
  rotterdam: {
    slug: "regio/rotterdam",
    type: "region",
    title: "AI-integratie voor bedrijven in Rotterdam",
    h1: "AI-integratie voor bedrijven in Rotterdam",
    description: "AI-integratie voor Rotterdamse haven, transport, maritime, industrie en documentintensieve operations.",
    intro: "AIOW bouwt AI-systemen voor Rotterdamse bedrijven waar planning, compliance, transportdocumenten en klantcommunicatie samenkomen.",
    intentAnswer: "AI-integratie in Rotterdam kan haven-, transport-, maritime- en industriële teams helpen om documentflows, planning, compliance-signalen en klantopvolging sneller en consistenter te verwerken.",
    keywords: ["AI integratie Rotterdam", "AI haven logistiek", "AI automatisering transport Rotterdam"],
    audiences: ["havenlogistiek", "maritime", "transport", "industrie en compliance"],
    useCases: ["Transport- en compliance-documenten controleren op ontbrekende informatie.", "Operations briefing voor planner, warehouse en klantcontact.", "Supplier/customer follow-up voorbereiden.", "Incidenten en uitzonderingen prioriteren."],
    privacy: "We behandelen operationele en commerciële data als gevoelig en kiezen per workflow welke informatie lokaal, private of cloud verwerkt mag worden.",
    faqs: [
      { q: "Kan AI helpen in havenlogistiek?", a: "Ja, vooral bij documentoverzicht, uitzonderingen, planning en overdracht tussen teams." },
      { q: "Vervangt dit planners?", a: "Nee. Het systeem ondersteunt planners met samenvattingen, signalen en conceptacties." },
      { q: "Kan AI compliance beslissingen nemen?", a: "Nee, AI kan voorbereiden en signaleren; finale beoordeling blijft menselijk." },
      { q: "Hoe starten we veilig?", a: "Met een afgebakende scan en pilot rond één document- of communicatieflow." },
    ],
  },
  "schiphol-haarlemmermeer": {
    slug: "regio/schiphol-haarlemmermeer",
    type: "region",
    title: "AI voor logistiek en bedrijven rond Schiphol en Haarlemmermeer",
    h1: "AI voor logistiek en bedrijven rond Schiphol en Haarlemmermeer",
    description: "AI voor air freight, import/export, warehousing, customs en zendingsexcepties rond Schiphol en Haarlemmermeer.",
    intro: "Rond Schiphol draait veel werk om snelheid, documentnauwkeurigheid en uitzonderingen. AIOW ontwerpt AI-systemen die dat werk overzichtelijker maken.",
    intentAnswer: "AI rond Schiphol en Haarlemmermeer kan import/exportbedrijven, air freight, warehouse en customs-teams ondersteunen met zendingsexcepties, documentcontrole, inbox triage en snelle operationele briefings.",
    keywords: ["AI logistiek Schiphol", "AI automatisering transport", "AI import export Haarlemmermeer"],
    audiences: ["air freight", "import/export", "warehousing", "customs en transport"],
    useCases: ["Shipment exceptions uit mails en documenten detecteren.", "Air freight documentsets samenvatten voor snelle review.", "Customs follow-up voorbereiden zonder finale compliance te automatiseren.", "Warehouse en transportplanning briefen op urgentie."],
    privacy: "Zending-, klant- en douanedata blijft onder strikte procesafspraken. We automatiseren geen compliancebesluiten zonder menselijke eigenaar.",
    faqs: [
      { q: "Kan AI helpen met import/export?", a: "Ja, door documentsets te structureren, ontbrekende informatie te signaleren en opvolging klaar te zetten." },
      { q: "Is AI geschikt voor douaneprocessen?", a: "AI kan ondersteunen, maar finale beoordeling en aangiftes horen bij bevoegde mensen/systemen." },
      { q: "Wat is een shipment exception workflow?", a: "Een proces dat vertragingen, ontbrekende documenten of afwijkingen signaleert en naar de juiste eigenaar routeert." },
      { q: "Kan dit lokaal draaien?", a: "Voor bepaalde document- en samenvattingstaken kan lokale/private AI zinvol zijn; dat beoordelen we in de scan." },
    ],
  },
  utrecht: {
    slug: "regio/utrecht",
    type: "region",
    title: "AI-automatisering voor MKB in Utrecht",
    h1: "AI-automatisering voor MKB in Utrecht",
    description: "AI-automatisering voor Utrechtse MKB-bedrijven: operations, sales/admin, interne kennis en teamcoördinatie.",
    intro: "Voor centraal-Nederlandse MKB-teams kan AI vooral helpen om dagelijkse communicatie, administratie en overdracht rustiger te maken.",
    intentAnswer: "AI-automatisering voor MKB in Utrecht richt zich op praktische processen zoals inbox, sales/admin, interne kennis, planning en teamcoördinatie, niet op hype of losse tools.",
    keywords: ["AI integratie Utrecht", "AI automatisering MKB Utrecht", "AI systeem bedrijf Utrecht"],
    audiences: ["MKB operations", "sales/admin", "business services", "managementteams"],
    useCases: ["Dagelijkse takenlijst uit mail, CRM-notities en planning.", "Sales follow-up en offertes voorbereiden.", "Interne procedures vindbaar maken voor nieuwe medewerkers.", "Managementbriefing met open risico's en volgende acties."],
    privacy: "We starten met informatie die veilig geanalyseerd kan worden en ontwerpen daarna pas koppelingen of lokale/private verwerking.",
    faqs: [
      { q: "Welke Utrechtse bedrijven passen bij AIOW?", a: "MKB-teams met veel terugkerende communicatie, administratie, planning of interne kennisvragen." },
      { q: "Moeten we onze systemen vervangen?", a: "Nee. AIOW start meestal naast bestaande tools en integreert pas waar dat bewezen nuttig is." },
      { q: "Hoe snel is een eerste pilot mogelijk?", a: "Na de scan kan een kleine pilot vaak snel worden ontworpen, maar timing hangt af van data en koppelingen." },
      { q: "Is analytics ingeschakeld?", a: "Nee. Analytics en niet-noodzakelijke cookies blijven uit totdat ze veilig en privacybewust zijn geconfigureerd." },
    ],
  },
  "eindhoven-brainport": {
    slug: "regio/eindhoven-brainport",
    type: "region",
    title: "Private AI en AI-systemen voor Brainport-bedrijven",
    h1: "Private AI en AI-systemen voor Brainport-bedrijven",
    description: "Private AI en AI-systemen voor Eindhoven/Brainport: technische documentatie, manufacturing, R&D workflows en lokale hardware.",
    intro: "Brainport-bedrijven werken met technische kennis, IP, documentatie en hardware-context. AIOW ontwerpt AI-systemen met controle en privacy als uitgangspunt.",
    intentAnswer: "Private AI voor Brainport-bedrijven kan technische teams ondersteunen met documentzoekfuncties, R&D-samenvattingen, manufacturing-kennis en lokale/hybride AI-routes zonder gevoelige informatie onnodig te verplaatsen.",
    keywords: ["private AI Eindhoven", "AI systeem maakindustrie", "lokale AI Brainport"],
    audiences: ["maakindustrie", "R&D teams", "hardwarebedrijven", "technical operations"],
    useCases: ["Technische documentatie doorzoekbaar maken voor engineers en support.", "R&D-notities samenvatten met lokale/private verwerking waar zinvol.", "Manufacturing issues structureren naar oorzaak, eigenaar en next step.", "Modelrouting ontwerpen tussen lokale hardware en goedgekeurde cloudmodellen."],
    privacy: "Voor technische/IP-gevoelige data is lokale of private AI vaak relevanter. We doen eerst scope, rechten en dataclassificatie voordat iets wordt gekoppeld.",
    faqs: [
      { q: "Waarom private AI voor Brainport?", a: "Technische bedrijven hebben vaak gevoelige documentatie, IP en proceskennis die niet standaard naar publieke tools hoort." },
      { q: "Kan AI helpen met technische documentatie?", a: "Ja, met zoeken, samenvatten, vergelijken en het klaarzetten van antwoorden voor menselijke review." },
      { q: "Draait dit in eigen of private infrastructuur?", a: "Dat kan binnen eigen of private infrastructuur, afhankelijk van workload, beleid en beheer." },
      { q: "Wat is een veilige eerste stap?", a: "Een afgebakende document- of supportworkflow met beperkte data en duidelijke evaluatiecriteria." },
    ],
  },
};

export const allSeoPages = { ...seoPages, ...regionPages };
