#!/usr/bin/env python3
"""First-pass text replacement: ORYZO reference -> AIOW/Debbie/AI Key.
Keeps layout/HTML/CSS/JS structure intact; only visible copy/meta text changes.
"""
from pathlib import Path

p = Path('public/oryzo-reference/index.html')
s = p.read_text()
replacements = {
    'ORYZO AI — local mirror': 'AIOW AI Key — local mirror',
    'Made for mugs. Built for tables.': 'Built for agents. Made for work.',
    'Designed to lift, insulate, and grip in all the right ways. Oryzo makes the simplest moment feel considered.': 'Designed to unlock, route, and verify AI work in all the right places. AIOW makes every agent action feel intentional.',
    'Designed\nby Lusion,\nthe award-winning\ndesign studio.': 'Designed\nby AIOW,\nwith Debbie as\nthe operating layer.',
    "The world's most\nunnecessarily\nsophisticated cork coaster.": 'The AI Key that turns scattered tools\ninto one trusted operating system.',
    'isn’t just\na coaster.': 'isn’t just\na website.',
    'Oryzo isn’t just a\ncoaster. It’s the result\nof unprecedented AI*\nbreakthroughs.': 'AIOW isn’t just a\nlanding page. It’s the start\nof an AI operating\nworkflow.',
    'Powered by AI': 'Powered by Debbie',
    'Oryzo-1': 'AI Key-1',
    'ORYZO-1': 'AI KEY-1',
    'Try to hover hand': 'Turn the key',
    'AI fills in the gaps.': 'Debbie routes the work.',
    'We said high five.\nIt heard six.': 'You give the signal.\nThe system clicks.',
    '* Adobe\nIllustrator': '* AI\nWORKFLOW',
    "So portable,\nit's wearable": 'So modular,\nit scales',
    'Warning\nThis stunt was performed by professionals.\nDo not attempt this at home.': 'Signal\nHuman approval stays in the loop.\nNo black-box autopilot.',
    'Hey\noryzo\n, can you put on a bikini?': 'Hey\nDebbie\n, route this to the right agent.',
    'AI SLOP IDEAS\nFOR THIS\nWINTER': 'AI WORKFLOWS\nFOR REAL\nOPERATIONS',
    'We Are So\nCooked!': 'We Are So\nBack.',
    "Oryzo is taking everyone's jobs...\nand replacing them with AI!": 'Debbie is taking scattered AI tasks...\nand turning them into operating flow.',
    'An open-weight model designed to be\nlightweight and easy to carry.': 'A visible operating layer designed to be\nmodular, inspectable, and trusted.',
    'Rise above mediocrity': 'Unlock better execution',
    'Elevate your coffee experience': 'Unlock your AI workflow',
    'Handles Extremes with Ease': 'Handles complexity with calm',
    'From piping-hot mugs to ice-cold drinks - Oryzo stays perfectly stable. Your coffee table already tapped out three sips ago.': 'From intake to execution, AIOW keeps work stable. Your spreadsheet tapped out three tools ago.',
    'Thermodynamic stability': 'Operational stability',
    'Perfectly Round, Seriously': 'Perfectly Routed, Seriously',
    'Our engineers recalibrated its circumference with disturbing levels of attention to detail - just because we could.': 'Every request gets routed, checked, and handed off with disturbing levels of attention to detail.',
    'Now 37.9% More Circular': 'Now 37.9% More Aligned',
    'Constant lift via geometry': 'Constant flow via routing',
    'THERMAL DIFFUSION MODEL (TDM)': 'TRUSTED DELEGATION MODEL (TDM)',
    'Circularity (circle = 1.0)': 'Alignment (signal = 1.0)',
    'RoPE: Roundness Optimization & Perimeter Engineering': 'RoPE: Routing, Ownership & Proof Engineering',
    'Secure communications simplified': 'Secure execution simplified',
    'Smart flip\nencryption': 'Smart key\nauthorization',
    'Write a message. Flip. Instantly secure - until\nsomeone flips it back. Genius.': 'Give intent. Seat the key. Actions unlock only when the proof layer says yes.',
    'Encode Message': 'Lock Action',
    'Decode Message': 'Unlock Action',
    'Precision Grip, Zero Drama': 'Precise Control, Zero Drama',
    'Grip-locked Antislip\ntechnology': 'Key-locked approval\ntechnology',
    'Micro-textured cork so grippy your drink files\na restraining order against gravity. Spills?\nConsider them politely discouraged.': 'Human gates and audit trails so clear your agents stop drifting. Chaos? Politely discouraged.',
    'Friction coefficient (est):': 'Trust coefficient (est):',
    '100% Plant-based': '100% Human-led',
    'Vegan-friendly': 'Agent-friendly',
    'sustainability': 'governance',
    'Pure cork sourced sustainably.\nCompletely vegan - no cows were harmed,\nbut it might be full of "bull"sh*t.': 'Built for durable AI operations.\nNo mystery automations, no hidden handoffs,\nno theatre.',
    'Average\nage of first\nharvest': 'Average\ntime to first\nworkflow',
    'Cork oaks are typically first harvested at around 25 years, once the bark is thick enough to remove safely.': 'A first useful AI workflow should be visible fast, then strengthened with proof and ownership.',
    'Harvesting\ninterval': 'Review\ninterval',
    'After each harvest, the bark takes about 9 years to regrow, making cork a renewable material.': 'Every workflow keeps improving through review loops, not random prompt piles.',
    'Power draw\nwhile in use': 'Control lost\nwhile in use',
    'No compute. No tokens. So you can say “please” and “thank you” as much as you want, guilt free.': 'No blind autonomy. You keep the seat, the key, and the final turn.',
    'People all around the world love Oryzo': 'Teams around the system trust Debbie',
    'Do not take our word for it, see what people say after living with Oryzo.': 'Do not take our word for it; the proof is in the workflows that keep running.',
    'Rating & Reviews': 'Signals & Proof',
    'ORYZO in use': 'AIOW in use',
    'Runs on the edge Refuses the cloud': 'Runs with proof Refuses the chaos',
    'ON-DEVICE.': 'ON-CHAIN READY.',
    'Always On': 'Always Routed',
    '24/7 UPTIME. NO POWER REQUIRED.': '24/7 CONTEXT. NO GUESSWORK REQUIRED.',
    'Runs on RTX 3090': 'Runs on your stack',
    'NO MORE OOM ON ANY CONSUMER GPUS': 'NO MORE CHAOS ACROSS YOUR AI TOOLS',
    'PERFECT BY DESIGN': 'PROOF BY DESIGN',
    'Drop-Tested': 'Stress-Tested',
    'TEST CONDITIONS: HARD SURFACE': 'TEST CONDITIONS: REAL OPERATIONS',
    'DAMAGE: THE FLOOR ;)': 'DAMAGE: THE BOTTLENECK ;)',
    'Legacy Support': 'Human Support',
    'SUPPORTING BACKWARD COMPATIBILITY SINCE THE 5TH MILLENNIUM BCE': 'SUPPORTING HUMAN JUDGMENT SINCE BEFORE THE CLOUD',
    'CHOOSE YOU OWN': 'CHOOSE YOUR LAYER',
    'ORYZO Pro Max': 'AIOW Pro Max',
    'ORYZO Pro': 'AIOW Pro',
    'ORYZO': 'AIOW',
    'New AIOW': 'New AIOW',
    'One coaster. One job. Done beautifully.': 'One key. One workflow. Done visibly.',
    'Twice the cork. Twice the commitment. Still effortless.': 'More routing. More context. Still calm.',
    'Three layers of confidence. For people who like their coffee slightly above it all.': 'Maximum proof. Maximum orchestration. For teams that need AI to actually operate.',
    'STACK: 1': 'LAYER: 1',
    'STACK: 2': 'LAYER: 2',
    'STACK: 3': 'LAYER: 3',
    'LIFT: 1 COASTER THICK': 'UNLOCK: SINGLE WORKFLOW',
    'LIFT: 2 COASTERS THICK': 'UNLOCK: MULTI-AGENT FLOW',
    'LIFT: 3 COASTERS THICK': 'UNLOCK: FULL OPS LAYER',
    'MATERIAL: CORK': 'MATERIAL: CONTEXT',
    'CONNECTIVITY: NONE': 'CONNECTIVITY: CONTROLLED',
    'PAIRING: NOT REQUIRED': 'PAIRING: HUMAN-APPROVED',
    'UPDATES: NEVER': 'UPDATES: CONTINUOUS',
    'BEST FOR: DAILY MUGS AND QUIET DESKS': 'BEST FOR: DAILY AI WORKFLOWS',
    'BEST FOR: TALLER CUPS AND EXTRA STABILITY': 'BEST FOR: TEAMS AND HANDOFFS',
    'BEST FOR: MAXIMUM LIFT AND MAXIMUM PRESENCE': 'BEST FOR: OPERATING AI AT COMPANY SCALE',
    'OUR SOTA OPEN WEIGHT MODEL': 'OUR VISIBLE OPERATING MODEL',
    'Paper': 'Blueprint',
    'MODEL (.OBJ)': 'KEY MAP',
    'Code coming soon': 'Agents coming online',
    'Abstract': 'Operating thesis',
    'We present Oryzo-1, an open-weight 3D model of a cork coaster for rendering, simulation, and gloriously unnecessary research. Oryzo-1 faithfully reproduces key coaster behaviors - table protection, perfect circularity, and passive thermal moderation under everyday beverage conditions. Released in clean OBJ format with baseline results on our own WoodenBench (a standardized evaluation suite conducted on a single desk and very possibly rigged by us). Limitations include heavy dependency on gravity, mugs, and human deployment.': 'We present AI Key-1, a visible operating model for routing AI work through intent, ownership, proof, and human approval. It turns scattered prompts, tools, agents, and automations into one inspectable workflow layer. Limitations include heavy dependency on strategy, context, and humans who know what good looks like.',
    'Acknowledgements': 'Acknowledgements',
    'This website was single-shot espresso’d into existence by the creative team at Lusion.': 'This operating layer is built by Team Debbie for AIOW: strategy, orchestration, review, and the key that makes AI work visible.',
    'Peer Review': 'Operator Review',
    '"Oryzo-1 A0B is the best model out there. Trust me bro."': '"The key finally makes the agents feel like a system, not a circus."',
    '- Anonymous LocalLLaMA Reddit user': '- Debbie operator note',
    'WE CAUGHT YOUR ATTENTION WITH A NON-EXISTENT PRODUCT.': 'WE CAUGHT YOUR ATTENTION WITH A VISIBLE AI KEY.',
    'IF WE CAN SELL A COASTER, IMAGINE WHAT WE CAN DO FOR YOUR BRAND.': 'IF WE CAN MAKE AI FEEL THIS TANGIBLE, IMAGINE WHAT WE CAN DO FOR YOUR OPERATIONS.',
    'lusion.co': 'aiow.com',
    'BUILT BY ': 'BUILT BY ',
    'LUSION': 'AIOW',
    'WITH LOVE ': 'WITH DEBBIE ',
    'SHARE WITH FRIENDS': 'SHARE WITH BUILDERS',
    'IF YOU LIKE IT': 'IF YOU GET IT',
    "SUBSCRIBE TO LUSION'S NEWSLETTER:": "SUBSCRIBE TO AIOW UPDATES:",
    'Subscribe to newsletter': 'Subscribe to updates',
    'business@lusion.co': 'business@aiow.com',
    'hello@lusion.co': 'hello@aiow.com',
    'GENERAL ENQUIRES:': 'GENERAL ENQUIRIES:',
}

missing=[]
for old,new in replacements.items():
    if old not in s:
        missing.append(old)
    s=s.replace(old,new)
p.write_text(s)
print('replacements', len(replacements), 'missing', len(missing))
for m in missing[:40]: print('MISS', repr(m))
